[FE] 비회원 로그인 페이지와 약속 조회/수정 페이지를 연결
woowacourse-teams/2024-momo pull request #105
Opened 2024-07-29 14:33 UTC by Yoonkyoungme

## 관련 이슈

- resolves: #101 

## 작업 내용

- 링크 공유, 로그인 페이지에 대한 라우팅 경로를 정의하고,해당 컴포넌트를 연결

## 특이 사항

- 라우팅 경로명 재설정 필요 (합치는 과정에서 임의로 설정하였습니다. 추후 리팩터링 시 더 적합한 path명으로 변경해봅시다!)

## 리뷰 요구사항 (선택)

2024-07-30 01:26 UTC, Largopie requested changes
PR 감사합니다 빙봉!
사소한 부분들에 대해서만 리뷰 남겼습니다 :)
반영 부탁드려요!

2024-07-30 01:26 UTC, Largopie commented on frontend/src/components/Time/Picker/TimePickerContainer.tsx
> +  console.log(meetingSchedules);
[P1]

여기 콘솔 붙어있네요!

2024-07-30 01:26 UTC, Largopie commented on frontend/src/components/Time/Picker/TimePickerContainer.tsx
> +    <></>
[P2]

Fragment로 return하게 되면 렌더링이 발생하는 것으로 알고 있습니다.
렌더링 하지 않으려면 return null로 해주어야할 것 같아요!

https://ko.react.dev/learn/conditional-rendering#conditionally-returning-nothing-with-null

2024-07-30 02:37 UTC, hwinkr requested changes
페이지 연결한다고 고생했습니다 빙봉!!

간단한 코멘트 몇개 남겼으니 수정 후 다시 요청 부탁드릴게요~

2024-07-30 02:37 UTC, hwinkr commented on frontend/src/apis/getHeaders.ts
> +  const token = getCookie('token');
[P3] 
token 상수화가 필요할 것 같습니다!

2024-07-30 02:37 UTC, hwinkr commented on frontend/src/apis/getHeaders.ts
> +  const token = getCookie('token');
쿼리키 상수화 하듯이 하면 될 것 같아요

2024-07-30 02:37 UTC, hwinkr commented on frontend/src/components/Time/Picker/TimePickerContainer.tsx
> +import { getMeetingMySchedule } from '@apis/getMeetingSchedules';
[Comment]

오늘 약속 참여자 자신의 스케쥴을 조회하는 API 엔드포인트가 `me`로 변경되었는데, getMeetingMySchedule함수 이름도 getMeetingMeSchedule로 변경하는 것이 좋을까요? 🤔 
함수명 자체는 어색한 것 같은데 백엔드 엔드포이트와 맞추려면 어쩔수 없나 싶기도 하네요~
빙봉은 어떻게 생각하시나요

2024-07-30 02:37 UTC, hwinkr commented on frontend/src/components/Time/Picker/TimePickerContainer.tsx
> +  const uuid = params.uuid!;
[P2]

현재 `useParams`를 많은 컴포넌트들에서 호출하고 있고, 호출한 후의 역할이 서버에서 전달해주는 uuid를 찾는 역할이니 커스텀 훅 `useUUID`를 만들어서 중복을 줄여보는 것은 어떨까요?

2024-07-31 01:07 UTC, Yoonkyoungme reviewed
@hwinkr @Largopie 코멘트 감사합니다😊 반영한 코멘트는 🚀 이모지 달아두었습니다.

@hwinkr 
> [P2]
> 
> 현재 useParams를 많은 컴포넌트들에서 호출하고 있고, 호출한 후의 역할이 서버에서 전달해주는 uuid를 찾는 역할이니 커스텀 훅 useUUID를 만들어서 중복을 줄여보는 것은 어떨까요?

→ 이 부분은 추후 작업할 브랜치에서 작업하겠습니다!

2024-07-31 01:09 UTC, hwinkr commented on frontend/src/components/Time/Picker/TimePickerContainer.tsx
> +import { getMeetingMySchedule } from '@apis/getMeetingSchedules';
좋아요~ 그렇게 하는게 좋을 것 같아요 프론트엔드에서는 `my`로 하시죠!

2024-07-31 01:09 UTC, hwinkr approved these changes
빙봉뱅봉~

2024-07-31 01:10 UTC, Largopie approved these changes
리뷰 반영 감사해요 🙌

2024-07-31 01:12 UTC, merged