[BE] 약속 잠금 기능 추가
woowacourse-teams/2024-momo pull request #119
Opened 2024-07-30 10:53 UTC by ikjo39

## 관련 이슈

- resolves: #112 

## 작업 내용

- 약속 필드 내 `boolean` 타입의 잠금 여부를 추가하였습니다.
- 기존 스케줄 생성시 약속이 잠금일 경우 예외가 발생하도록 검증을 추가하였습니다.

## 특이 사항

- 해당 PR이 머지되면 잠금 취소 기능도 추가할 예정입니다.

## 리뷰 요구사항 (선택)

> 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?

`Meeting` 객체 내 중복된 잠금 시도시 예외가 발생하도록 로직이 짜여져있는데요.
불필요한 검증일지 궁금합니다!

2024-07-30 16:24 UTC, hw0603 reviewed
고생하셨습니다~ 👏

PR 본문에서 언급해 주신 부분을 포함하여 논의해 볼 만한 부분 코멘트 남겨 두었어요.

단순히 칼럼 하나로 락을 관리하면 동시성 문제가 필연적으로 발생할 것 같은데, 새벽이라 깔끔한 예시가 생각이 안 나네요😅 내일 오전에 추가 코멘트로 남기겠습니다!

2024-07-30 16:24 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +    private void validateMeetingLocked(Meeting meeting) {
```suggestion
private void validateMeetingUnlocked(Meeting meeting) {
```

2024-07-30 16:24 UTC, hw0603 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +    @DisplayName("약속을 잠글 때 만남이 존재하지 않으면 404를 반환한다.")
```suggestion
@DisplayName("존재하지 않는 약속을 잠금 시도하면 404 Not Found를 반환한다.")
```

2024-07-30 16:47 UTC, seokmyungham requested changes
다온 고생하셨습니다 🔥
받으면 행운이 깃드는 제 RC를 드리겠습니다 😊
동시성 관련해서는 내일 같이 이야기 나눠봐요

2024-07-30 16:47 UTC, seokmyungham commented on backend/src/main/java/kr/momo/domain/meeting/Meeting.java
> +        }
매우 동의합니다.

2024-07-30 16:47 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +    @PostMapping("/api/v1/meetings/{uuid}/lock")
현재 요청대로라면 `PUT`보다는 `PATCH`가 적절할 것 같습니다.

2024-07-30 16:47 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +    }
참가자 내부에서 예외를 발생시키도록 변경하는게 좋을 것 같습니다.

2024-07-30 16:47 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +    }
이 부분도 위와 마찬가지로, 약속에게 정보를 묻는 것 이상으로 자신의 상태를 스스로 검증할 수 있도록 개선할 수 있을 것 같습니다.

2024-07-31 01:00 UTC, ikjo39 commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +    @PostMapping("/api/v1/meetings/{uuid}/lock")
CORS 기본 설정에서 `PATCH`가 열려있지 않음을 염두하여 `POST`로 설정하였는데요.
의도에 맞게 HTTP 메서드를 설정하고, CORS 재설정 관련 이슈를 올려야겠네요 :)

2024-07-31 01:06 UTC, ikjo39 commented on backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
> +    ACCESS_DENIED(HttpStatus.FORBIDDEN, "접근이 거부되었습니다.");
이 부분도 토의해보고 싶었는데 빼먹었네요 😅
`ACCESS_DENIED`를 사용자에게 얼마나 표현해야할지 의구심이 들었어요.
권한 관련 문제임을 사용자에게 노출해도 될까? 생각하였는데요.
`FORBIDDEN` 상태 코드를 반환하기로 결정한 시점에서 좀 더 명확한 메세지도 괜찮겠다 생각도 드네요 :)
페드로는 어떻게 생각하시나요?

2024-07-31 01:14 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +    }
재즈와 1:1 대화를 직접 나눠본 대로 적절한 객체에게 책임을 부여하는 것이 서비스의 불필요한 책임을 방지하고 뚱뚱함도 예방할 수 있을 것 같아요!
반영해보겠습니다.

2024-07-31 01:17 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/meeting/Meeting.java
> +        }
불필요한 검증이 맞았군요 👍 
반영하겠습니다.

2024-07-31 03:38 UTC, ehBeak requested changes
다온 고생 많으셨어요 👍
네이밍과 관련해서 리뷰 남김니다! 확인해 보시고 괜찮다면 반영 부탁드려요~!

2024-07-31 03:38 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +    }
오전에 같이 이야기한 것 처럼 해당 로직이 서비스 플로우에 포함되어있기 때문에 저는 이대로 두는 것에 찬성입니다.
도메인 자체의 책임보다는 서비스의 책임에 더 가깝지 않나 싶네요..!

2024-07-31 04:20 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +    }
위의 답변과 동일합니다!

2024-07-31 04:21 UTC, hw0603 commented on backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
> +    ACCESS_DENIED(HttpStatus.FORBIDDEN, "접근이 거부되었습니다.");
물론 서버의 상세한 오류 메시지를 사용자에게 모두 노출할 필요는 없겠지만, 어떤 이유로 인해서 예외가 발생했는지를 전달하여 사용자의 다음 행동을 정상 플로우로 유도하는 것도 중요하다고 생각합니다.

개인적으로는
```sugggestion
주최자만 잠금을 설정할 수 있습니다.
```
정도의 메시지는 괜찮은 것 같아요. 이렇게 쓴다면 Enum의 키 값도 수정되어야 하겠네요 :)

2024-07-31 04:46 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/attendee/Attendee.java
> +    }
배키 말에 동의합니다! 
권한의 의미를 담고 싶었는데요. 오히려 혼란을 유발할거 같아 단순히 `isHost()`메서드명을 따라해도 괜찮단 생각이 드네요.

2024-07-31 04:52 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +    }
오늘 다시 확인해보니 비즈니스 로직 검증사항에 더 가까운 것 같네요 👍👍

2024-07-31 04:57 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +    }
우선 정책상 중복 잠금 요청을 검증하는 로직이 없어져 해당 테스트는 사라지게 되었어요 🥲

요청을 두번 보낸 이유는 잠겨 있는 약속을 만들려면 테스트를 위한 생성자를 만들어야 했기에 `MeetingFixture`에 반영하지 않았어요. 하지만 생성자는 테스트를 위해서는 열어도 된다는 관점도 있던터라 배키의 방식도 일리 있다고 생각되네요!
한번 얘기 나눠봐도 좋을것 같아요

2024-07-31 04:58 UTC, ikjo39 commented
리뷰 모두 반영해보았습니다! 
반영하며 느낀 점은 Controller Test의 `@DIsplayName`에 대한 컨벤션도 있어야겠다 생각이 드네요 :)
고려해볼 사항 있다면 코멘트 부탁드려요~

2024-07-31 05:03 UTC, hw0603 approved these changes

2024-07-31 05:11 UTC, seokmyungham approved these changes

2024-07-31 05:43 UTC, seunghye218 approved these changes
약속 조회 시 잠금 상태에 대한 정보도 잘 추가되어있네요! 고생했어요 다온👍

2024-07-31 07:15 UTC, ehBeak approved these changes
RC 반영하시느라 고생 많으셨어요 다온~!!👍

`DisplayName`에 대한 컨벤션은 따로 이야기 나누어요 :)

2024-07-31 07:17 UTC, merged