[BE] 약속 잠금 해제 기능 추가
woowacourse-teams/2024-momo pull request #127
Opened 2024-07-31 08:24 UTC by ikjo39

## 관련 이슈

- resolves: #120 

## 작업 내용

- 약속 잠금 해제 기능을 구현하였어요 :)

2024-07-31 11:23 UTC, seunghye218 approved these changes
기능의 중요한 동작들을 꼼꼼히 테스트 했네요👍

2024-07-31 14:40 UTC, ehBeak reviewed
코드를 읽기 쉽게 작성해 주셔서 직관적으로 파악하기 좋았어요 😊
간단하게 코멘트만 남겨요! 고생 많으셨습니다~

2024-07-31 14:40 UTC, ehBeak commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +                .extract().jsonPath().getString("data.token");
로그인을 요청하고 토큰을 얻는 로직이 각 테스트마다 중복해서 존재하네요..! 함수로 따로 분리해서 사용하면 어떨까요?👍

2024-07-31 15:12 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +                .extract().jsonPath().getString("data.token");
배키 의견에 동의합니다! 관련 로직 메서드 분리하도록 할게요 :)

2024-08-01 01:18 UTC, seunghye218 approved these changes
배키의 리뷰를 적용한 뒤 한걸음 더 간결해졌네요. 저도 테스트에서 토큰 얻는 코드가 중복되고 있었는데 참고해야겠네요~

2024-08-01 01:18 UTC, seokmyungham submitted a review, later dismissed
다온 고생하셨습니다 🌞

2024-08-01 01:20 UTC, ehBeak approved these changes
🎉🎉

2024-08-01 06:42 UTC, hw0603 requested changes
수고하셨습니다 다온!
코멘트 몇 가지 남겨 두었어요~

2024-08-01 06:42 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +                .orElseThrow(() -> new MomoException(AttendeeErrorCode.NOT_FOUND_ATTENDEE));
`Enum` 값을 보니 404를 내리는 것 같은데, 400이 더 적절할 것 같아요!

2024-08-01 06:42 UTC, hw0603 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +        String token = getToken(attendee, meeting);
메서드 추출 👍

2024-08-01 06:42 UTC, hw0603 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +    @DisplayName("존재하지 않는 약속을 잠금 해제 시도하면 404 Not Found를 반환한다.")
위에 언급한 것과 같이 `400 Bad Request`는 어떨까요?

2024-08-01 07:58 UTC, seunghye218 approved these changes
상황에 맞는 예외 코드가 잘 적용됐네요 👍

2024-08-01 08:08 UTC, hw0603 approved these changes

2024-08-01 08:13 UTC, ehBeak approved these changes
굿굿👍

2024-08-01 08:18 UTC, seokmyungham approved these changes

2024-08-01 08:18 UTC, merged