[BE] 약속 일정 확정 API 추가
woowacourse-teams/2024-momo pull request #128
Opened 2024-07-31 11:15 UTC by seunghye218

## 관련 이슈

- resolves: #118 

## 작업 내용

- ConfirmedSchedule 도메인 추가

- 일정 확정 검증 순서
    1. uuid에 해당하는 약속 존재
    2. 호스트 권한인 참여자가 요청하였는지
    3. 약속이 잠금 상태인지
    4. 날짜가 약속에 속한 날짜인지
    5. 시간 범위 올바른지, 약속에 속한 시간 범위 인지

- 자세한 내용은 백로그에 기록

## 특이 사항

- 해당하는 참가자의 스케줄이 존재하지 않더라도 확정 일정이 약속의 범위에 포함되면 일정 확정 가능

## 리뷰 요구사항 (선택)

- DB 테이블 연관관계 설계
- 객체 및 메서드 이름
- 스케줄이 거대해져 패키지 분리함
- `private validateHostPermission` 가 서로 다른 서비스에서 중복적으로 발생. 참가자가 책임지자는 재즈의 의견 적용할지
- ***endTime 저장 시 30분 차감하는 로직이 일정 확정 기능에도 영향이 있음. 비슷하면서도 다른 코드들이 생겨나 헷갈림. 확실하게 정해야할듯

2024-07-31 16:29 UTC, ikjo39 reviewed
마크 기능 구현하느라 고생하셨습니다 👍
몇 가지 리뷰 남겼으니 확인 부탁드려요!

추가로 PR 본문에 대해 드리고 싶은 말도 남겨보아요.
PR 본문을 읽어보며 개인적으로 마크의 설계 의도, 컨텍스트 설명이 부족하다 느꼈어요.
일부분은 코드를 따라가봐야 이해되서 좀 당황스럽기도 했는데요.
작업한 결과를 나열하기보단 보다 문장 형태로 명확하고 근거와 함께 적어주시면 리뷰할 때 보다 수월할 거 같아요!
수고스럽겠지만 PR 본문도 함께 관리해야하는 문서로서 제안드립니다. 🙏

2024-08-01 01:14 UTC, seunghye218 commented on backend/src/test/java/kr/momo/controller/confirmschdule/ConfirmScheduleControllerTest.java
> +
제 코드 스타일 적용으로는 안잡히네요. 다른 플러그인이 필요한 걸까요?

2024-08-01 02:05 UTC, seunghye218 commented on backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
> +    NOT_FOUND_MEETING(HttpStatus.NOT_FOUND, "존재하지 않는 약속 정보 입가니다."),
맥에서 발생하는 키보드 오류가 빨리 고쳐졌으면 좋겠네요🥲

2024-08-01 02:19 UTC, seunghye218 commented on backend/src/main/java/kr/momo/service/confirmschedule/ConfirmScheduleService.java
> +    public void confirmSchedule(String uuid, long attendeeId, @Valid ScheduleConfirmRequest request) {
메서드 생성하면서 잘못 붙였네요. 지우도록 하겠습니다~

2024-08-01 02:20 UTC, seunghye218 commented on backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
> +    GUEST_MARK("mark", "mark!123", Role.GUEST);
나만 없었어서 서운해~

2024-08-01 02:25 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/confirmedschedule/ConfirmedSchedule.java
확정 일정에 필요한 정보로 약속에 대한 날짜, 시작 시간, 끝 시간이 있습니다. 
연관관계에 대해서 약속 당 하나의 확정 일정이 필요하기 때문에 약속-확정일정 일대일 연관 관계 맵핑했어요.
일단 확정 일정 당 하나의 날짜가 필요하다 생각하여 가능날짜-확정 일정 일대일 연관 관계 맵핑했는데 여행 같은 약속의 경우 여러 날짜가 가능합니다. 추가적으로 추천 일정이 밤12시에 걸쳐 이어진 시간이라면 일대다 관계가 되어야할 것 같아요. 이 부분은 논의가 필요할 것 같습니다!

2024-08-01 05:57 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/timeslot/TimeslotInterval.java
> +        }
`getValidatedTimeslot()` 메서드는 검증과 함께 timeSlot을 반환하게 됩니다. `Meeting` 객체와 마찬가지로 `ConfirmSchedule` 객체도 시작 시간과 끝 시간을 `TimeInterval` 객체로 저장하게 되는데 끝시간은 백엔드의 `TimeSlot` 도메인에 맞게 30분을 줄여 저장하게 됩니다. 여기서 제시한 메서드를 사용하면 애매한 부분이 생깁니다. `endTime`에 30분을 감소시켜 해당 메서드를 호출해야 하는데 이 로직이 서비스에 노출되게 됩니다. 

```java
// service
Timeslot startTimeSlot = meeting.getValidatedTimeslot(request.startTime());
Timeslot endTimeSlot = meeting.getValidatedTimeslot(request.endTime().minusMinutes(30));
```

 이에 대한 책임은 `Meeting` 객체가 가져한다고 생각하여 따로 검증하는 메서드를 만들게 되었습니다. 이에 대해 다온은 어떻게 생각하시나요~?

2024-08-01 06:20 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/meeting/Meeting.java
> +
메서드 리팩터링 했습니다~

2024-08-01 08:17 UTC, seokmyungham requested changes
마크 고생하셨습니다. 😊
받으면 행운이 깃들고 열정이 샘솟는 제 RC를 드립니다. 🎉
궁금한 점 있으면 언제든지 코멘트 남겨주세요!!

2024-08-01 08:17 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/confirmschedule/ConfirmScheduleService.java
> +        confirmedScheduleRepository.save(new ConfirmedSchedule(meeting, date, request.startTime(), request.endTime()));
save() 호출 밖에서 객체 생성을 했으면 좋겠습니다. (개인적인 바람)

2024-08-01 08:17 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/confirmschedule/ConfirmScheduleService.java
> +        });
현재 약속이 확정 상태인지를 확인하기 위해서 저장소를 참조해야하는 게 정말 마음이 아프네요,,,
지금은 대안이 딱히 떠오르지 않아 어쩔 수 없을 것 같아요 😥 ERD를 수정해야 할 수도 있겠습니다..

그래도 현재 코드보다는 `exists`로 존재 여부만 확인해서 검증을 하는게 성능상 유리할 것 같습니다.

2024-08-01 08:52 UTC, seunghye218 commented on backend/src/main/java/kr/momo/controller/confirmschdule/ConfirmScheduleController.java
> +        return ResponseEntity.created(URI.create("/api/v1/meetings/" + uuid + "/confirmed-schedule")).build();
추후 일정 확정 조회 API 엔드포인트를 빙봉과 상의했었고 새로 생성된 리소스 위치가 위와 같기 때문이라 그렇습니다. 조회 엔드포인트가 어색하다는 의미일까요?

2024-08-01 09:00 UTC, seunghye218 commented on backend/src/main/java/kr/momo/service/confirmschedule/ConfirmScheduleService.java
> +        });
좋은데요? exists 메서드를 적용해보도록 수정해보겠습니다!

2024-08-01 09:23 UTC, ehBeak requested changes
마크 고생 많으셨어요! 리뷰 남깁니다~~ 👍

2024-08-01 09:23 UTC, ehBeak commented on backend/src/main/java/kr/momo/exception/code/ConfirmedScheduleErrorCode.java
> +    CONFIRMED_SCHEDULE_EXISTS(HttpStatus.BAD_REQUEST, "이미 확정된 약속입니다.");
대부분의 에러코드 상수명을 {이유}_{도메인명} (ex. `NOT_FOUND_MEETING`) 이런 식으로 작성했더라고요! 
사소하지만..ㅎㅎ 맞춰서 통일하는 것이 좋을 것 같아요~

추가로, 이미 존재하기 때문에 발생한 에러코드니까 `ALREADY_EXIST_CONFIRMED_SCHEDULE`처럼 의도를 명확히 하면 어떨까요?

2024-08-01 09:23 UTC, ehBeak commented on backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
> +    GUEST_MARK("mark", "mark!123", Role.GUEST);
🥲🥲🥲

2024-08-01 09:23 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/confirmschedule/ConfirmScheduleService.java
> +        });
confirmedScheduleRepository.findByMeeting(meeting)
```suggestion
        confirmedScheduleRepository.findByMeeting(meeting)
                .ifPresent(ignore -> new MomoException(ConfirmedScheduleErrorCode.CONFIRMED_SCHEDULE_EXISTS));
```
중괄호 빼면 좋을 것 같아요👍

2024-08-01 09:23 UTC, ehBeak commented on backend/src/test/java/kr/momo/controller/confirmschdule/ConfirmScheduleControllerTest.java
> +        meeting = meetingRepository.save(meeting);
setUp()에서 meeting을 저장했지만, meeting.lock()한 다음에 변경감지를 사용할 수 없어서 다시 값을 저장하네요..! 좀 어색하게 느껴집니다. 방법은 잘 모르겠어서 코멘트만 남겨요!

2024-08-01 12:51 UTC, seunghye218 commented on backend/src/main/java/kr/momo/service/confirmschedule/ConfirmScheduleService.java
> +            throw new MomoException(AttendeeErrorCode.ACCESS_DENIED);
MeetingService에서도 위와 같이 사용하던데 같이 수정해볼게요~

2024-08-01 13:02 UTC, seunghye218 commented on backend/src/main/java/kr/momo/controller/confirmschdule/ConfirmScheduleController.java
> +    @PostMapping("/api/v1/meetings/{uuid}/confirmed-schedule")
confirm 쪽이 더 좋은 엔드포인트라 생각이 드네요!

2024-08-01 13:06 UTC, seunghye218 commented on backend/src/main/java/kr/momo/controller/confirmschdule/ConfirmScheduleController.java
> +        return ResponseEntity.created(URI.create("/api/v1/meetings/" + uuid + "/confirmed-schedule")).build();
아래 리뷰를 적용하여 어색함이 줄었다고 생각하는데 어떤가요?

2024-08-01 13:10 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/confirmedschedule/ConfirmedSchedule.java
> +        this.timeslotInterval = new TimeslotInterval(startTime, endTime.minusMinutes(30));
Meeting의 생성자를 보시면 위와 같고 말씀하신 의미 그대로 사용하고 있습니다. 
13:00 ~ 13:30 으로 요청이 들어온다면 startTime = 13:00, endTime = 13:00 으로 저장되는 것이 맞아요.

2024-08-01 13:15 UTC, seunghye218 commented on backend/src/main/java/kr/momo/exception/code/ConfirmedScheduleErrorCode.java
> +    CONFIRMED_SCHEDULE_EXISTS(HttpStatus.BAD_REQUEST, "이미 확정된 약속입니다.");
말씀하신대로 명확하게 의도를 드러내도록 변경해볼게요~👍

2024-08-01 13:17 UTC, seunghye218 commented on backend/src/main/java/kr/momo/service/confirmschedule/ConfirmScheduleService.java
> +        });
재즈의 리뷰를 반영하며 수정하였습니다

2024-08-01 13:23 UTC, seunghye218 commented on backend/src/test/java/kr/momo/controller/confirmschdule/ConfirmScheduleControllerTest.java
> +        meeting = meetingRepository.save(meeting);
저도 다른 방법이 떠오르지 않네요... 잠금 상태에 조회 및 저장 방법에 의논을 나눠보면 좋을 것 같아요~

2024-08-01 13:52 UTC, hw0603 reviewed
다른 분들이 이미 변경점들을 많이 짚어 주셔서 일반 코멘트로 남겨요!

> 참가자가 주최자가 아니라면 예외를 발생하는 validateHostPermission 메서드가 서로 다른 서비스에서 중복적으로 발생합니다. 참가자가 책임지자는 재즈의 의견 적용할지 생각이 궁금합니다.

Host가 아닐 때 어떤 예외를 터트려야 할지 서비스 플로우마다 다를 수 있지 않을까요? 일괄적으로 도메인이 그 예외를 지정해서 던지는 것은 서비스 문맥에 따라 어색한 상황이 발생할 수 있을 것 같아요

> 가능날짜-확정 일정 일대일 연관 관계에 대해 의문점이 있습니다. 여행 같은 약속의 경우 여러 날짜가 가능하고 추천 일정이 밤12시에 걸쳐 이어진 시간이라면 일대다 관계가 되어야할 것 같아요. 어떻게 생각하시는지 궁금합니다.

제 경험상 여행과 같은 일정을 잡는 경우 보통 시간을 생략하고 날짜만 투표받는 경우가 대부분이였는데요, 저희 초기 목표 기능 중에 날짜만 투표받는 기능도 있었던 것으로 기억해요.
현재는 후순위 구현 사항이 되었으니 우선 언급해 주신 부분은 잠시 보류하는 것도 괜찮을 것 같아요.
하지만... 밤12시에 걸쳐 이어진 시간이라면... 이 부분은 어떻게 해결할지 의논이 필요해 보이네요😲

> endTime 저장 시 30분 차감하는 로직이 일정 확정 기능에도 영향이 있습니다. 비슷하면서도 다른 코드들이 생겨나 헷갈릴 수 있고 차후 반복될 것으로 예상됩니다. [BE] 하루의 마지막 타임슬롯이 포함된 일정 등록 시 오류가 발생해요 :(  #88 이슈와 관련되어 있으며 회의에서 확실하게 정하고 넘어가야 나중에 유지보수하기 편해질 것 같습니다.

이 부분은 우선적으로 리팩토링 진행해 보겠습니다🥲

2024-08-01 15:43 UTC, ikjo39 reviewed
마크 리뷰 반영하시느라 수고많으셨어요!
다만 팀원들과 몇가지 조율할 논제들이 있어보여 댓글로 의견 남기도록 하겠습니다.

2024-08-01 15:43 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/confirmschdule/ConfirmScheduleControllerTest.java
> +        meeting = meetingRepository.save(meeting);
당장은 두가지의 해결 방안이 떠오르는데 둘 다 만족스럽진 않네요 😅
추가적인 논의가 필요할듯해 보입니다.
1. protected로 `Meeting`에 `isLocked` 생성자를 열어두고,`MeetingFixture`의 `isLocked` 필드를 추가한 뒤 `src/test/java/kr/momo/domain/meeting` 하위로 Fixture를 옮긴다.
2. 아래와 같은 로직을 Fixture 아래 추가한다.
```java
public enum MeetingFixture {

//...//
    public Meeting createThenLock() {
        Meeting meeting = new Meeting(name, uuid, firstTime, lastTime);
        meeting.lock();
        return meeting;
    }
}
```

2024-08-01 15:43 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/confirmedschedule/ConfirmedSchedule.java
> 하지만 여행 같은 약속의 경우 여러 날짜가 가능합니다. 

이 경우엔 시간들이 의미 없어지니 주최자가 약속 생성시 탭 기능을 이용해 시간 값이 없도록 설정할 수 있게끔 확장하는 것도 고려해볼 수 있을 거 같아요!
지금은 시간이 있는 약속 설정만 가능하게끔 초점을 맞춰보는 것도 좋아보입니다.
> 추가적으로 추천 일정이 밤12시에 걸쳐 이어진 시간이라면 일대다 관계가 되어야할 것 같아요.

제 생각엔 이럴 때는 주최자가 00:00-23:30로 모든 시간에 대한 약속을 설정하고, 그 다음날까지 이용가능일로 특정한 뒤
주최자가 가능한 시간대를 표시하게끔 하는 방식도 고려할 수 있을 것 같아요.

> 연관관계에 대해서 약속 당 하나의 확정 일정이 필요하기 때문에 약속-확정일정 일대일 연관 관계 맵핑했어요.

현재 마크가 보여준 Entity 설계가 30분씩 시간이 줄어드는 오류에 관한 이슈만 해결된다면 MVP를 충분히 만족하고 있다고 생각합니다 👍

2024-08-05 08:15 UTC, seunghye218 commented on backend/src/test/java/kr/momo/controller/confirmschdule/ConfirmScheduleControllerTest.java
> +        meeting = meetingRepository.save(meeting);
기본적으로 잠긴 약속으로 초기화 하고 잠기지 않은 약속을 테스트할 때 unlock 후 테스트하도록 변경했어요. 확인 부탁드려요~

2024-08-05 13:49 UTC, ikjo39 reviewed
안녕하세요 마크!
복잡한 로직 구현하시느라 고생 많으셨어요..!
몇가지 리뷰 남겼으니 확인해주세요🙏

2024-08-05 13:49 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +    public boolean isContainedWithinDateRange(LocalDate startDate, LocalDate endDate) {
이런 메서드명 어떨까요?
```suggestion
    public boolean isConsecutiveDay(LocalDate startDate, LocalDate endDate) {
```

2024-08-05 13:49 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +                    || (date.isAfter(startDate) && date.isBefore(endDate))) {
1. if문 내에 2개 이상의 비교문이 있는 경우 메서드 분리하면 가독성이 오를 것 같아요!
2. 추가적으로 `(date.isEqual(startDate) || date.isEqual(endDate))`와 `(date.isAfter(startDate) && date.isBefore(endDate))` 모두 무엇을 의미하는지 와닿지 않아서요.
추가적인 설명이 궁금합니다!

2024-08-05 13:49 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return count != endDate.toEpochDay() - startDate.toEpochDay() + 1;
제가 이해한 연속된 날짜를 판단하는 로직이 맞을까요?
그렇다면 연속인지 숫자를 세기 보단, 
최초 날짜부터 하루씩 더한 날짜가 그 다음 인덱스의 날짜임을 판단하면 더 간단해질 수 있을 거 같아요!

```java
public boolean isConsecutiveDay(List<LocalDate> dates) {

    // Sorted 로직

    if (dates == null || dates.size() < 2) {
        return true;
    }

    for (int i = 1; i < dates.size(); i++) {
        LocalDate previousDate = dates.get(i - 1);
        LocalDate currentDate = dates.get(i);
            
        // 두 날짜가 연속되지 않으면 false를 반환
        if (!previousDate.plusDays(1).equals(currentDate)) {
            return false;
        }
    }

    return true;
}
```

2024-08-05 13:49 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
> +        }
시작일이 동일한 경우와 동일하지 않은 경우로 나눠서 로직을 구현하고 싶으셨던 것 같아요!
Early Return 으로 depth를 늘리기 보단 풀어서 설명해주시는게 가독성이 좋을 것 같아요!
```suggestion
        if (startDate.equals(endDate) && availableDates.notExistsByDate(startDate)) {
            throw new MomoException(ConfirmedScheduleErrorCode.INVALID_DATETIME_RANGE);
        }

        if (!startDate.equals(endDate) && meeting.isNotFullTime()) {
            throw new MomoException(ConfirmedScheduleErrorCode.INVALID_DATETIME_RANGE);
        }

        if (availableDates.isContainedWithinDateRange(startDate, endDate)) {
            throw new MomoException(ConfirmedScheduleErrorCode.INVALID_DATETIME_RANGE);
        }
```

2024-08-05 17:23 UTC, hw0603 requested changes
고생하셨어요 마크!
꽤 예외사항이 많은 로직이였는데 꼼꼼하게 잘 작성해 주셨네요!

몇 가지 변경 요청과 함께 테스트 코드에 코멘트 남겨 두었습니다. 코드와 일치하지 않는 테스트가 있어서 CI가 통과하지 않더라구요.

> 최대 가능 시간(23:59)을 처리하는 로직이 없기에 연속된 날짜 테스트가 불가능 합니다.

말씀해 주신 것과 같이 현재 테스트가 되고 있지 않은데, 이 부분을 해결하고 머지를 진행할지, #88 번 이슈에서 같이 해결할지는 논의가 필요해 보여요

2024-08-05 17:23 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return count != endDate.toEpochDay() - startDate.toEpochDay() + 1;
연속될 뿐만 아니라, `AvailableDates` 내의 날짜 범위의 부분집합이여야 합니다.
따라서 제시해 주신 로직만으로는 모든 검증을 다 할 수 없어요.

흐름을 따라가 보면, 1 3 5 7 10 일이 가능 날짜일 때, 닫힌구간 `[d, d+3]`일이 구간 내의 부분집합이라면 `d`, `d+1`, `d+2`, `d+3` 이렇게 총 `4`개의 날짜가 모두 `AvailableDates` 내에 존재해야 합니다.

따라서 `AvailableDates`를 오름차순 정렬한 후, 가장 빠른 일자부터 `d+3`일 까지 순회하며,
현재 탐색중인 `availableDate`가
- `d`일 혹은 `d+3`일 이거나
- `d`일 초과 `d+3`일 미만인
날짜들의 개수를 카운트하여  카운트 값이`((d+3) - d) + 1 [==4]` 와 일치하는지 확인하는 로직입니다.

가장 빠른 일자부터 탐색하지 않고 이분탐색을 활용하여 `d`일을 탐색 시작점으로 잡고 카운트하는 로직을 그대로 수행하면 조금 더 최적화할 수 있습니다.

---

기가 막힌 로직이긴 한데요, `public` 메서드임에도 해당 로직을 따라가기가 쉽지 않았습니다.
이러한 로직들은 이후 유지보수에 걸림돌이 될 수 있고, 작성자 본인만 수정할 수 있는 로직이 될 가능성이 커요.

특히, `public` 메서드의 흐름은 도메인 로직을 잘 모르는 개발자가 읽더라도 그 흐름이 명확해야 한다고 생각합니다.

위와 같은 복잡한 로직은 `private`메서드로 분리하거나 (물론 변수명/메서드명을 잘 지어서 흐름을 따라가는데 무리가 없어야겠죠), 메서드에 주석을 추가하는 한이 있더라도 의도를 설명해야 합니다.

2024-08-06 04:53 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +    public boolean isContainedWithinDateRange(LocalDate startDate, LocalDate endDate) {
기존에 존재하던 네이밍을 따라지었는데 이 쪽이 더 간결해보이네요. 적용하겠습니다~

2024-08-06 05:11 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return count != endDate.toEpochDay() - startDate.toEpochDay() + 1;
피드백이 필요했었는데 좋은 리뷰들 감사합니다. 가독성 좋게 메서드를 분리해볼게요!

2024-08-06 05:22 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +                    || (date.isAfter(startDate) && date.isBefore(endDate))) {
1. 아래 리뷰와 함께 리팩터링해볼게요!
2. 정렬된 약속의 날짜들 중 확정 일정에 해당하는 경우를 카운트하기 위한 조건문입니다. `isAfter` 와 `isBefore`는 비교 대상의 날짜를 포함하지 않기 때문에 `isEqual` 까지 추가한 모습이에요. 
-> 요약: 날짜 초과, 미만이 아니라 이상, 이하를 검증.

2024-08-06 05:25 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +    public boolean isContainedWithinDateRange(LocalDate startDate, LocalDate endDate) {
꿀팁이네요👍 리팩터링하며 위와 같은 형용사를 잘 사용해볼게요.

2024-08-06 05:28 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +                .toList();
저도 도입해도 좋다고 생각했는데 그런 문제가 발생하는군요... 필요성이 더 커질 때 확실히 알아보고 적용해보죠.

2024-08-06 05:29 UTC, seunghye218 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +                .header("Location", "/api/v1/meetings/" + meeting.getUuid() + "/confirmed-schedule");
수정했습니다!

2024-08-06 05:36 UTC, seunghye218 commented on backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
> +                || !meeting.isContainedWithinTimeRange(startDateTime.toLocalTime(), endDateTime.toLocalTime())) {
기다란 메서드를 변수로 빼보도록 할게요!

2024-08-06 05:39 UTC, seunghye218 commented on backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
> +        }
좋네욥👍 동의합니다.

2024-08-06 06:22 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return count != endDate.toEpochDay() - startDate.toEpochDay() + 1;
스트림으로 로직을 선언형으로 간결하겨 리팩터링했습니다~
```
long availableDateRangeCount = availableDates.stream()
                .sorted(comparing(AvailableDate::getDate))
                .dropWhile(date -> date.isBefore(startDateInclusive))
                .takeWhile(date -> !date.isAfter(endDateInclusive))
                .count();
```

2024-08-06 06:36 UTC, seunghye218 commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +    public ResponseEntity<Void> confirm(
당장은 안쓰더라도 추후에 프론트에서 가져다 쓰기 편하고, 응답을 테스트하기에 직관적이겠네요! 적용하겠습니다~

2024-08-06 07:57 UTC, hw0603 reviewed
```java
    @DisplayName("start일자부터 end일 사이의 모든 날짜가 가능한 날짜인지 확인한다.")
    @Test
    void testMethod() {
        // given
        AvailableDates availableDates = new AvailableDates(
                List.of(
                        LocalDate.of(2024, 8, 1),
                        LocalDate.of(2024, 8, 2),
                        LocalDate.of(2024, 8, 3),
                        LocalDate.of(2024, 8, 4),
                        LocalDate.of(2024, 8, 5),
                        LocalDate.of(2024, 8, 6),
                        LocalDate.of(2024, 8, 7),
                        LocalDate.of(2024, 8, 8),
                        LocalDate.of(2024, 8, 9),
                        LocalDate.of(2024, 8, 10)
                ), null
        );

        // when
        boolean actual = availableDates.isNotConsecutiveDay(
                LocalDate.of(2024, 8, 2),
                LocalDate.of(2024, 8, 10)
        );

        // then
        boolean expected = false;
        assertThat(actual).isEqualTo(expected);
    }
```

이런 느낌으로 `AvailableDates.isNotConsecutiveDay()` 에 대한 테스트도 가능할 것 같아요!

`@DisplayName`은 임시로 적어둔 거니 참고만 하시구요ㅎㅎ
`@MethodSource` 를 활용해서 `true` 일 때와  `false`일 때 모두 테스트하면 좋겠네요🙂

2024-08-06 08:51 UTC, seokmyungham approved these changes
마크 고생 많으셨어요. 🔥🎉🔥🎉🔥🎉🔥🎉

2024-08-06 10:27 UTC, ikjo39 approved these changes
고생했어요 마크~

2024-08-06 14:37 UTC, ehBeak approved these changes
마크 고생 많으셨습니다~!!💯💯

2024-08-06 14:45 UTC, hw0603 approved these changes
고생 많으셨습니다🚀
댓글 76개를 끝으로 이만 이 PR은 닫도록 하죠ㅎㅎ Approve 합니다!

2024-08-06 14:53 UTC, merged