[FE] colors, typography 디자인 토큰 생성
woowacourse-teams/2024-momo pull request #129
Opened 2024-07-31 13:28 UTC by hwinkr

## 관련 이슈

- resolves: #124 

## 작업 내용

### 디자인 토큰 적용

- colors
- typography
  - 피그마에 있는 값들은 모바일 규격과 맞지 않다고 판단했어요.
  - 그래서 `title`의 `font-size`를 `2.4rem`으로 잡고, title -> subtitle -> body -> caption 순으로 `0.4rem` 씩 내리면서 스타일을 설정했습니다.
  - font-size, font-weight, line-height를 함께 설정했어요
- timetable
  - 선택된 색상과, 선택되지 않은 색상을 구분하기 위해서 `selected`, `unselected` 프로퍼티를 추가하여 구분했어요.
  - `unselected` 같은 경우 피그마 디자인과 약간 색이 달라요. 
    - `dark` 색상은 사용자가 시간을 수정할 때, 선택한 시간과 더 대비되도록 하기 위해서 어둡게 할 때 사용하면 될 것 같아요

## 특이 사항

- 변경된 `grey` 팔레트 색상 피그마에 적용 예정
- 변경된 `typography` 피그마에 적용 예정
- red 색상에 관해서 추가 논의 필요

## 리뷰 요구사항 (선택)

2024-08-01 02:35 UTC, Yoonkyoungme approved these changes
해리 🍀 고생하셨습니다!
궁금한 점에 대해 코멘트 남겼는데, 편하게 답변 주세요 :)

2024-08-01 02:35 UTC, Yoonkyoungme commented on frontend/src/styles/tokens/colors.ts
> +  // 현재 달력에서 공휴일 색을 표시하기 위해서 빨간색을 사용하고 있는데, 빨간색도 palette를 사용해야 할지는 미정(@해리)
**[P3]** 
>   현재 달력에서 공휴일 색을 표시하기 위해서 빨간색을 사용하고 있는데, 빨간색도 palette를 사용해야 할지는 미정(@해리)

시간 도메인 내에서는 빨간색을 공휴일 표시할 때만 사용할 것 같아요.
지금은 `red: '#ff0000'`으로 해두고, 추후 빨간색 계열의 색상을 사용하게 될 때 palette로 만드는건 어떨까요?

2024-08-01 02:35 UTC, Yoonkyoungme commented on frontend/src/styles/tokens/colors.ts
> +  white: PRIMITIVE_COLORS.white,
**[Q]**

디자인 토큰에 대해 잘 몰라서 물어보는 질문입니다 :)
`PRIMITIVE_COLORS[white]`를 쓰는 것과 `SEMANTIC_COLORS[white]`를 사용할 때 차이가 있나요? 사용하는 상황이 구분되어 있나요?

2024-08-01 02:35 UTC, Yoonkyoungme commented on frontend/src/styles/tokens/colors.ts
> +export const SEMANTIC_COLORS = {
**[P3]**

`SEMANTIC_COLORS`도 `as const` 처리해주면 어떨까요?

2024-08-01 06:36 UTC, Largopie requested changes
고생하셨습니다 해리 :) 🐫
토큰 반영해주셔서 감사합니다!!!
사소한 리뷰 몇 가지 남겼으니 확인 부탁드려요!

2024-08-01 06:36 UTC, Largopie commented on frontend/src/components/_common/TimeSlot/TimeSlot.styles.ts
> +  background: ${isSelected ? theme.colors.primary : '#ececec'};
[P2]

여기 회색에 대해서도 토큰을 적용하면 좋을 것 같네요 :)

2024-08-01 06:36 UTC, Largopie commented on frontend/src/components/_common/Button/Button.styles.ts
>    background: #fff;
[P3]

흰색도 토큰 값에 반영된 만큼 해당 토큰을 이용하는 것이 좋을 것 같습니다!

2024-08-01 06:42 UTC, hwinkr reviewed
디스코드 리뷰 알림 테스트

2024-08-01 15:47 UTC, hwinkr reviewed
comment 알림 테스트

2024-08-01 15:59 UTC, hwinkr commented on frontend/src/styles/tokens/typography.ts
> +  },
타이틀은 기본적으로 `bold`로 폰트 설정이 될 것 같은데유
혹시 뭔가뭔가 한 상황에서~ `medium`까지는 필요하지 않을까~ 했고 `Light` 까지는 설마설마~ 해서 없어용

2024-08-01 16:02 UTC, hwinkr commented on frontend/src/styles/tokens/colors.ts
> +  // 현재 달력에서 공휴일 색을 표시하기 위해서 빨간색을 사용하고 있는데, 빨간색도 palette를 사용해야 할지는 미정(@해리)
넵.

2024-08-01 16:03 UTC, hwinkr commented on frontend/src/styles/tokens/colors.ts
> +export const SEMANTIC_COLORS = {
꼼꼼하시네요 빙봉뱅봉...날카로워서 베일 뻔 했습니다.

2024-08-01 16:13 UTC, hwinkr commented on frontend/src/styles/tokens/colors.ts
> +  white: PRIMITIVE_COLORS.white,
저도 잘 몰라서 디자인 토큰과 관련된 여러 레퍼런스를 보고 맞춰서 설정해본 것인데, white도 palette와 같이 여러개의 색을 사용하고, primary, secondary...를 사용한다면 PRIMITIVE_COLORS와 매핑시키는 것이 의미있다고 보지만, 현재 저희 서비스에서 흰 색은 `#ffffff` 하나이기 때문에 차이가 없어보일 것 같기도 하네요.

한 번 더 추상화하는 것과 같은 의미가 있을 것 같아요!

2024-08-01 16:18 UTC, hwinkr reviewed
리뷰 반영 했습니다!

2024-08-02 00:57 UTC, Largopie approved these changes
반영 감사합니다 :) 🐫🐫🐫🐫

2024-08-02 01:33 UTC, Yoonkyoungme approved these changes
해리 리뷰 반영 감사합니다 ~

2024-08-02 04:39 UTC, merged