[BE] 기존 jwt 토큰 응답 방식을 쿠키로 변경하고 path 및 보안 설정
woowacourse-teams/2024-momo pull request #131
Opened 2024-07-31 14:57 UTC by seokmyungham

## 관련 이슈

- resolves: #117 

## 작업 내용

- 응답 시 ResponseBody, 요청 시 Authorization 헤더에 jwt 토큰을 저장하던 방식을 쿠키로 변경하였습니다.
- 쿠키의 `HttpOnly`, `Secure` 옵션을 활성화 하였습니다.
- 요청시 현재 사용자가 접속한 UUID와 일치하는 인증 쿠키만 전송하도록 인증 쿠키 path에 약속 UUID를 포함하였습니다.

## 특이 사항

## 리뷰 요구사항 (선택)

2024-07-31 17:02 UTC, ikjo39 submitted a review, later dismissed
고생했어요 재즈 😄

2024-08-01 06:32 UTC, seunghye218 submitted a review, later dismissed
HttpOnly, Secure 옵션으로 더 안전하게 인증할 수 있겠네요. path 옵션을 통해 다른 약속의 토큰이 전달되지 않도록 설정하여 그로인해 발생할 수 있는 문제도 해결되겠어요. 👍

2024-08-01 07:08 UTC, hw0603 requested changes
고생하셨습니다 재즈!

코멘트 몇 가지 남겨 드렸습니다^^

2024-08-01 07:08 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
>      }
명시적으로 `null`을 다루기보다는 `Optional`  API를 활용해 보면 어떨까요?

```suggestion
        String token = getCookieValue(cookies).orElse("");

        return jwtManager.extract(token);
    }

    private Optional<String> getCookieValue(Cookie[] cookies) {
        if (cookies == null) {
            return Optional.empty();
        }

        return Arrays.stream(cookies)
                .filter(cookie -> ACCESS_TOKEN.equals(cookie.getName()))
                .map(Cookie::getValue)
                .findFirst();
    }
```

2024-08-01 07:08 UTC, hw0603 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +                .cookie("ACCESS_TOKEN", token)
Fixture 에 상수로 추가해줘도 될 것 같아요!

2024-08-01 07:17 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
> +        String path = String.format("/api/v1/meetings/%s/", uuid);
이 부분은 오타가 맞을까요?
```suggestion
        String path = String.format("/api/v1/meetings/%s", uuid);
```

2024-08-01 08:02 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
>      }
현재 로직에 따르면 cookies가 null일 때 예외가 발생해야합니다. 
그런데 제안하신 로직에서는 cookies가 null일 때 예외가 발생하지 않고 ""이 반환되는 것 같아요..!

아니면 아래처럼 resolveArgument() 함수 내에서 token의 null 체크 부분을 삭제하고 getCookieValue()함수에서 optional을 사용해서 cookie가 null 값일 때 예외를 발생시키는 방법도 있을 것 같습니다.
```java
    @Override
    public Long resolveArgument(
            @NonNull MethodParameter parameter,
            ModelAndViewContainer mavContainer,
            @NonNull NativeWebRequest webRequest,
            WebDataBinderFactory binderFactory
    ) {
        HttpServletRequest request = (HttpServletRequest) webRequest.getNativeRequest();
        Cookie[] cookies = request.getCookies();
        String token = getCookieValue(cookies);

        return jwtManager.extract(token);
    }

    private String getCookieValue(Cookie[] cookies) {
        cookies = Optional.ofNullable(cookies)
                         .orElseThrow(() -> new MomoException(AuthErrorCode.NOT_FOUND_TOKEN));

        return Arrays.stream(cookies)
                .filter(cookie -> ACCESS_TOKEN.equals(cookie.getName()))
                .map(Cookie::getValue)
                .findFirst()
                .orElseThrow(() -> new MomoException(AuthErrorCode.NOT_FOUND_TOKEN));
    }
```

2024-08-01 08:05 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
> +        response.addCookie(cookie);
`Set-Cookie` 가 설정된 경우 브라우저는 기존 쿠키들을 전부 지우고 해당 헤더에 명시된 쿠키만을 설정하는게 아니라, 헤더에 명시되어 있는 쿠키만 업데이트/추가 하는것으로 알고 있어요.

동일한 도메인과 경로에 동일한 이름을 가진 쿠키가 설정될 때만 기존 쿠키가 새로운 값으로 업데이트됩니다.
`ResponseEntity`를 사용한 방법으로는 힘들 것 같다는게 어떤 말씀이신지 좀 더 자세히 설명해 주실 수 있으신가요?

2024-08-01 08:25 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
>      }
반영하겠습니다 😄

2024-08-01 08:45 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
>      }
@ehBeak 
페드로의 제안은 쿠키의 토큰이 JwtManger의 verifyToken 메서드 한 곳에서 검증 관리되는 게 응집도 측면에서 자연스럽다는 것을 의미하는 것 같습니다.

2024-08-01 08:46 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
>      }
@ehBeak 
페드로의 제안한 의견 맥락은 쿠키의 토큰이 JwtManger의 verifyToken 메서드 한 곳에서 검증 관리되는 게 응집도 측면에서 자연스럽다는 것을 말하고자 하는 것 같습니다.

2024-08-01 08:46 UTC, seokmyungham commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +                .cookie("ACCESS_TOKEN", token)
좋네요 반영하겠습니다.

2024-08-01 08:55 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
>      }
@ehBeak 
페드로 제안의 의미는 쿠키의 토큰이 JwtManger의 verifyToken 메서드 한 곳에서 검증 관리되는 게 응집도 측면에서 자연스럽다는 것을 말하는 것 같습니다.

2024-08-01 08:55 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
> +            @PathVariable String uuid, @RequestBody @Valid AttendeeLoginRequest request, HttpServletResponse response
오 좋은데요? 👍

2024-08-01 08:57 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
> +        response.addCookie(cookie);
배키가 제안해주신 방법 괜찮아보이는데 지금 하시는 말이 무슨 의미인지 이해가 안됩니다. 😅

2024-08-01 09:11 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
>      }
해당 맥락에서 쿠키는 결국 토큰이므로 `null`일 때의 예외 처리 역시 `JwtManager`의 책임이라고 생각했어요🙂

2024-08-01 11:49 UTC, hw0603 approved these changes

2024-08-01 11:51 UTC, ikjo39 approved these changes

2024-08-01 11:53 UTC, merged