[BE] 약속 추천 기능 구현
woowacourse-teams/2024-momo pull request #139
Opened 2024-08-01 06:11 UTC by ehBeak

## 관련 이슈

- resolves: #122 

## 작업 내용

약속 시간을 추천하는 기능을 구현했습니다. 
약속 시간을 추천하는 기준은 아래와 같습니다.
* **가장 빨리 만날 수 있는 시간 순** : 참여자가 가장 많은 약속으로 정렬한 뒤, 참여자가 동일한 경우 가장 빨리 만날 수 있는 시간으로 정렬
* **가장 오래 만날 수 있는 시간 순** : 참여자가 가장 많은 약속으로 정렬한 뒤, 참여자가 동일한 경우 가장 오래 만날 수 있는 시간으로 정렬

### 예시
아래와 같이 시간 정보가 있다고 하면,
| 날짜 | 시간 | 참여자|
|-----|-----|-------|
| 2024-08-01 | 1:00-2:00 | attendee1 |
| 2024-08-01 | 3:30-4:30 | attendee1, attendee2 |
| 2024-08-01 | 4:30-5:00 | attendee1 |
| 2024-08-01 | 5:00-7:00 | attendee1, attendee2 |
| 2024-08-02 | 1:30-3:00 | attendee1, attendee2 |
| 2024-08-02 | 5:00-5:30 | attendee1 |

가장 빨리 만날 수 있는 시간 순으로 정렬 시 응답입니다.
| 날짜 | 시간 | 참여자|
|-----|-----|-------|
| 2024-08-01 | 3:30-4:30 | attendee1, attendee2 |
| 2024-08-01 | 5:00-7:00 | attendee1, attendee2 |
| 2024-08-02 | 1:30-3:00 | attendee1, attendee2 |
| 2024-08-01 | 1:00-2:00 | attendee1 |
| 2024-08-01 | 4:30-5:00 | attendee1 |
| 2024-08-02 | 5:00-5:30 | attendee1 |

가장 오래 만날 수 있는 시간 순으로 정렬 시 응답입니다.
| 날짜 | 시간 | 참여자|
|-----|-----|-------|
| 2024-08-01 | 5:00-7:00 | attendee1, attendee2 |
| 2024-08-02 | 1:30-3:00 | attendee1, attendee2 |
| 2024-08-01 | 3:30-4:30 | attendee1, attendee2 |
| 2024-08-01 | 1:00-2:00 | attendee1 |
| 2024-08-01 | 4:30-5:00 | attendee1 |
| 2024-08-02 | 5:00-5:30 | attendee1 |

### API 형식
요청
```http
GET /api/v1/meetings/{uuid}/recommend-schedules/{recommendType}?attendeeNames=name1,name2,name3..
```

응답
```http
{
    "data": {
        "attendeeNames": [
            "daon",
            "mark"
        ],
        "recommendSchedules": [
            {
                "date": "2024-07-15",
                "dayOfWeek": "월",
                "startTime": "20:00",
                "endTime": "21:00",
                "attendeeNames": [
                    "daon",
                    "mark"
                ]
            },
            {
                "date": "2024-07-15",
                "dayOfWeek": "월",
                "startTime": "21:00",
                "endTime": "21:30",
                "attendeeNames": [
                    "mark"
                ]
            }
        ]
    }
}
```

## 특이 사항

endTime은 마감시간입니다. 1:00-2:00라면, 1시부터 2시까지 말합니다. (1:00-2:30 까지가 아님)
추후 논의 뒤에 수정 예정입니다.

## 리뷰 요구사항 (선택)

`ScheduleRecommender` 클래스의 역할
`ScheduleRecommender` 클래스는 정렬 방법을 추천 유형에 따라 Comparator를 다르게 정의합니다.
* `ScheduleService`의 `recommendSchedules()`에서 추천 유형에 따라 정렬할 때 사용합니다. service 로직이 너무 길어져서 정렬 로직을 `ServiceRecommender`로 분리했는데, 괜찮은 건지 모르겠습니다. 
* 추가로, service에 해당되는 로직이라 service 패키지에 두었습니다. enum 클래스라도 service로 두는 것이 괜찮은지 궁금합니다.
* 네이밍도 괜찮은지 모르겠네요! 

`groupingScheduleByAttendees(List<Schedule> schedules) `함수 리팩토링
이 함수는 참가자가 선택한 모든 스케줄을 매개변수로 받아와서 (1) 다음 시간이 30분 뒤 시간이고 (연속된 시간이고) (2) 해당 참여자들이 이전과 동일한 참여자들이라면 `ScheduleRecommendResponse`로 묶어주는 역할을 합니다. 이 로직을 구현했지만 많이 복잡해 보여서 도움이 필요합니다 😢

# 리팩토링이 많이 필요한 코드입니다. 코드리뷰 매운맛으로 부탁드려요🔥

2024-08-01 08:21 UTC, ikjo39 reviewed
배키 고생하셨어요!
몇가지 컨벤션 관련 리뷰 남겼으니 확인부탁드려요!

2024-08-01 08:21 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleRecommender.java
> +
불필요한 공백 제거 부탁드려요 🙏

2024-08-01 08:21 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
`ScheduleService` 관련 로직은 어떻게 리팩토링 해야할지는 당장은 떠오르지 않네요...🥲
다만 private 메서드보단 객체로 분리하여 테스트가 가능하도록 두는 게 어떨까요?

2024-08-01 08:21 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +    private boolean isContinuousDateTime(
```suggestion
    private boolean isDiscontinuousDateTime(
```

2024-08-01 12:16 UTC, hw0603 requested changes
고생하셨습니다!

몇 가지 수정사항들 리뷰 남겨 두었어요.
`ScheduleService`가 너무 비대해져서, 몇 기능들을 도메인 서비스로 위임하고 쿼리로 처리할 수 있는 부분들을 쿼리로 처리하는 것도 고려해 봐야 할 것 같아요.

경우에 따라서는 한 타임슬롯을 비트 하나에 대응시켜 `long long`을 활용한 비트마스킹 기법도 도입해 볼 수 있겠네요.

2024-08-01 12:16 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/schedule/dto/ScheduleRecommendResponse.java
> +    public static ScheduleRecommendResponse from(
```suggestion
    public static ScheduleRecommendResponse of(
        ...
) {
```

2024-08-02 01:17 UTC, Largopie commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
> +            @PathVariable String uuid, @PathVariable String recommendType, @RequestParam List<String> attendeeNames
저 또한 동의합니다.

2024-08-02 01:18 UTC, Yoonkyoungme commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
> +            @PathVariable String uuid, @PathVariable String recommendType, @RequestParam List<String> attendeeNames
코멘트가 늦었네요😅 저도 동의합니다.

2024-08-02 01:54 UTC, seunghye218 commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
> +            @PathVariable String uuid, @PathVariable String recommendType, @RequestParam List<String> attendeeNames
저도 동의합니다!

2024-08-02 01:59 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
> +            @PathVariable String uuid, @PathVariable String recommendType, @RequestParam List<String> attendeeNames
`@PathValiable`과 `@RequestParam`의 차이를 깊게 고민하지 않고 사용했네요 😅
첨부하신 링크와 [자료](https://stackoverflow.com/questions/30967822/when-do-i-use-path-parameters-vs-query-parameters-in-a-restful-api)를 읽어보니 path parameter와 query parameter의 근본적인 차이는 아래 같네요!

> The best practice for RESTful API design is that path parameters are used to identify a specific resource or resources, while query parameters are used to sort/filter those resources.

파라미터를 사용하는 것이 올바른 방향인 것 같아요. 수정하겠습니다~

2024-08-02 02:14 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/Attendees.java
> +    public void validateDuplicatedDates(List<Attendee> attendees) {
> 접근제어자를 public으로 열어두신 이유가 궁금합니다!

실수입니다.. 하하

> 안전한 상황을 검증한다는 의미로 메서드명을 정의하자는 팀 컨벤션을 적용한다면 메서드명이 변경될 수 있을 것 같아요.

앗 그렇네요. 반영해서 validateUniqueNames로 수정했습니다 :)

2024-08-03 10:56 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/Attendees.java
> +        }
>처음으로 중복된 요소를 만났을 때 연산을 중단할 수 있으면 더 좋지 않을까요?

이런 방법이 있었군요! 효율적인 방법이네요. 반영하겠습니다~

2024-08-03 11:15 UTC, ehBeak commented on backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
앗 그렇네요! 안 그래도 테스트 코드가 너무 길어져서 어떻게 해야 할지 고민했는데, 이 방법을 쓰면 확실히 줄일 수 있을 것 같아요 😊

2024-08-03 12:24 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/Attendees.java
> +    private final List<Attendee> attendees;
> 하지만 Attendees 라는 클래스명은 단일 참가자를 나타내는 도메인인 Attendee와 이름이 비슷하여 헷갈릴 우려가 있을 것 같아요.

사실 제가 작성한 클래스명인데도 헷갈렸어요..😅  (지금까지 일급 컬렉션의 클래스는 도메인명에 s를 붙이는 것이 컨벤션인 줄 알았네요.)
페드로가 추천한 네이밍으로 수정하겠습니다~

2024-08-03 13:42 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/ScheduleRecommender.java
> +                .orElseThrow(IllegalArgumentException::new);
앗. ErrorCode를 어느 클래스에 두어야 할지 고민하다가 일단은 IllegalArgumentException로 두었는데, 수정을 안했네요. 
MomoException을 던지도록 수정했습니다!

2024-08-03 15:09 UTC, hwinkr commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
> +            @PathVariable String uuid, @PathVariable String recommendType, @RequestParam List<String> attendeeNames
저도 그게 올바른 방향인 것 같아요!

2024-08-04 12:42 UTC, ehBeak commented
리뷰 반영하고 로직 또한 수정해서 다시 리뷰 요청 드립니다.

현재 추천 로직은 아래와 같습니다.

참여자 A, B, C가 있을 때 가장 빨리 만날 수 있는 시간과 오래 만날 수 있는 시간순으로 정렬하는 법은 아래와 같습니다.
1. A, B, C의 조합을 구합니다 : `findAttendeeGroupCombination()`
2. 전체 조합을 돌면서 연속된 시간이면 시간을 합칩니다 : `groupingScheduleByAttendees(List<Schedule> schedules)`
3. 빠른 시작 시간으로 정렬합니다. : `sortedAndFilterByRecommendType(...)`

2024-08-05 12:40 UTC, hw0603 requested changes
리뷰 반영하느라 고생하셨어요 배키!

다만 몇 가지 더 수정해야 할 부분들이 보여서 다시 변경 요청 드립니다!

2024-08-05 12:40 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +                .filter(response -> response.attendeeNames().size() == groupSize)
모든 조합에 대해 연산을 하고 있는데 이곳에서 필터링을 해야 한다는 것은 각 조합 연산 끼리 중복되는 연산이 있다는 의미입니다.
162행에 남겨드렸던 리뷰와 동일한 리뷰가 될 것 같은데, 미리 관심 있는 것들만 계산하도록 개선할 수 있을 것 같아요.

2024-08-05 12:40 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleRecommender.java
> +package kr.momo.service.schedule;
응용 서비스 로직보다는 도메인 로직을 수행하는 도메인 서비스로 사용되는 것 같아요.
service 패키지보다는 domain 패키지가 어울릴 것 같은데 어떻게 생각하시나요?

2024-08-05 12:40 UTC, hw0603 commented on backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
> +        AvailableDate date1 = availableDateRepository.save(new AvailableDate(LocalDate.now(), movieMeeting));
테스트코드 공통적으로 사용되는 `LocalDate.now()` 나 `LocalDate.now().plutDays(1) ` 같은 값들은 별도의 픽스쳐를 두는 게 깔끔할 것 같아요

2024-08-05 12:40 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +            addCombinationAttendeeGroup(isVisit, groupCombination, index + 1);
도메인 내에서의 재귀호출은 디버깅이 까다로워질수도 있고 무엇보다 코드를 한번에 이해하기 어렵게 만들 것 같아요.
유틸성 클래스 하나가 늘더라도 `List<T>` 를 받아서 모든 조합을 `List<List<T>>` 혹은 `Stream<List<T>>` 형태로 반환해 주는 조합 클래스를 만드는 건 어떨까요?

자바에 조합 내장함수가 없어서 여러 사람이 고생이네요😅

2024-08-05 13:08 UTC, hw0603 commented on backend/src/test/java/kr/momo/domain/attendee/AttendeeGroupTest.java
> +                .containsExactlyInAnyOrder(
이곳도 로직을 수정해서 항상 참여자가 많은 순으로 조합이 계산되도록 하고, `.containsExactly`로 검증하면 좋을 것 같아요!

2024-08-05 13:22 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +            addCombinationAttendeeGroup(isVisit, groupCombination, index + 1);
\+) 현재 참여자가 `N` 명이면 `2^N` 개의 조합쌍이 나오는 구조입니다.
이렇게 되면 15명만 참여해도 3만개 이상의 조합이 생겨서..나중에는 이것을 적당히 끊을 기준이 필요해 보여요!

예를 들어 15명이 필터링 조건으로 들어왔을 때, 참여자가 `(15-3)`개 이상의 조합쌍에 대해서만 계산을 해 준다던지 하는 방법으로요.

2024-08-06 10:53 UTC, ikjo39 reviewed
배키에게 기분 좋아지는 RC를 남겨드립니다~ 😄

2024-08-06 10:53 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +    private void addCombinationAttendeeGroup(Map<Attendee, Boolean> isVisit, List<AttendeeGroup> groupCombination, int index) {
동의 합니다!
```suggestion
    private void addCombinationAttendeeGroup(
            Map<Attendee, Boolean> isVisit, List<AttendeeGroup> groupCombination, int index
    ) {
```

2024-08-06 10:53 UTC, ikjo39 commented on backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
> +import kr.momo.domain.attendee.AttendeeGroup;
Conflict 해결과정에서 패키지 정리가 안된 것 같아요!
`optimize import` 한번 부탁드릴게요!

2024-08-06 10:53 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/schedule/dto/SchedulesRecommendResponse.java
> +        return new SchedulesRecommendResponse(attendeeNames , recommendSchedules);
```suggestion
        return new SchedulesRecommendResponse(attendeeNames, recommendSchedules);
```

2024-08-06 10:53 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +                .allMatch(new HashSet<>()::add);
1개의 요소 매칭시 빠르게 결과를 반환하려면 다음과 같이 변경해주어야 할 것 같아 보이네요!
```suggestion
        return attendees.stream()
                .map(Attendee::name)
                .noneMatch(new HashSet<>()::add);
```

2024-08-06 10:53 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +        HashSet<String> attendeeNames = new HashSet<>(names);
추후에 요구사항이 변경될 때 수정에 닫히고 확장에 용이하도록 구현체가 아닌 인터페이스에 의존하는게 좋을 거 같아요!

```suggestion
        Set<String> attendeeNames = new HashSet<>(names);
```

2024-08-06 11:58 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
> +    @GetMapping("/api/v1/meetings/{uuid}/recommend-schedules")
그렇네요! 동사형보다는 명사형이 올바른데, 동사형을 쓰고 있었네요..😅

2024-08-06 12:53 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +@EqualsAndHashCode
네 맞습니다. 그런데 사실 순서가 어긋나면 다른 그룹으로 처리하는 건 @EqualsAndHashCode의 역할을 잘하는 것 같다는 생각이 들어요. 필드가 List 타입이니까요.
그래서 equals를 오버라이딩하는 것 보다 attendee 타입을 Set<Attendee>로 바꾸고 @EqualsAndHashCode는 유지하는 것이 어떨까요?🤔

2024-08-06 13:25 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +    private List<ScheduleRecommendResponse> groupingScheduleByAttendees(List<Schedule> schedules) {
앗 그렇네요.. 해당 메서드의 역할은 Schedule의 연속된 시간을 묶은 뒤에 바로 ScheduleRecommendResponse에 맞춰서 값을넣어주는 역할인데, 뭔가.. 응답으로 변환하는 로직과 그룹핑하는 로직이 뒤섞인 것 같아요. 그러니까 네이밍도 좀 애매하고요🥲
TimeInterval 같이 시간과 날짜가 같이 있는 객체를 만들어서(DateTimeInterval) Map<TimeInterval, AttendeeGroup> 으로 반환한 뒤, ScheduleRecommendResponse로 변환하면 더 읽기 쉬운 코드가 될 것 같습니다~

2024-08-06 13:38 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +        responses.add(ScheduleRecommendResponse.of(startTime, now, startNames));
> 제일 마지막에 남는 타임슬롯 그룹을 추가하기 위한 행인가요? 원 로직이랑 합쳐볼 수는 없을까요?🤔

네 맞습니다. do while문을 쓰면 합칠 수도 있지만, 마지막에 남는 타임슬롯인지 아닌지 확인하는 과정 때문에 오히려 반복문 안의 로직이 복잡해 지더라고요. 다른 방안이 생각나지 않네요😢

> + 확실히 이 부분까지 오니 startNames 라는 네이밍이 확실히 어색한 것 같아요.

계속 수정한다는 걸 깜박했네요..핳 이번에는 진짜 수정했습니다~!

2024-08-06 13:50 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/dto/SchedulesRecommendResponse.java
> +public record SchedulesRecommendResponse(
오늘 같이 이야기한 것처럼,
추천 페이지에 참여자의 이름이 필요한 상황이라 API 호출 한번으로 추천 페이지를 그리기 위해서 위와 같이 API 응답을 구현했습니다. 
페드로 말을 듣고 공감했고 @hwinkr 해리한테도 전달하고 상의했습니다. 추후 수정될 예정입니다~

2024-08-07 01:57 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +                .allMatch(new HashSet<>()::add);
isUnique() 함수는 각 Attendee의 이름이 서로 중복되지 않는지 확인하는 로직입니다.
그래서 전체 값이 true인 경우, true를 반환하는 allMatch를 사용하고 부정연산자(!)를 통해 반환시켰습니다.
noneMatch의 경우 전체 값이 false인 경우 true를 반환합니다. 때문에 List.of("1", "2", "2")인 경우 true를 반환할 것 같지만 false를 반환합니다. allMatch와 완전히 반대되는 개념이 아니라서, 그대로 두어야 할 것 같습니다.

---
혹시나 몰라서 이해를 위해 설명 올립니다.
```java
List<Integer> list = List.of(1, 2, 4, 4, 5);

list.stream().allMatch(HashSet<>()::add); // (1)

list.stream().noneMatch(HashSet<>()::add); // (2)
```
*먼저, allMatch와 noneMatch 내부의 HashSet<>()::add  함수는 주어진 HashSet에 add()를 통해 값을 넣은 뒤, 해당 값이 set 내부에 존재하면 false를 반환하고 해당 값이 내부에 존재하지 않으면 true를 반환합니다.

(1) AllMatch(HashSet<>()::add)
원소 1을 넣습니다 -> add의 값은 true이기 때문에 넘어갑니다.
원소 2를 넣습니다 -> add의 값은 true이기 때문에 넘어갑니다.
원소 4를 넣습니다 -> add의 값은 true이기 때문에 넘어갑니다.
원소 4를 넣습니다 -> add의 값은 false이기 멈춥니다. 
=> allMatch의 경우 하나라도 false이면 결과 값이 flase가 되기 때문에 그 뒤의 값을 볼 필요가 없습니다. 


(2) noneMatch(HashSet<>()::add)
원소 1을 넣습니다 -> add의 값은 true이기 때문에 멈춥니다.
=> noneMatch의 경우 하나라도 true면 결과 값이 false가 되기 때문에 그 뒤의 값을 볼 필요가 없습니다.

2024-08-07 02:05 UTC, seunghye218 reviewed
어려운 파트를 맡아 고생이에요 배키.. 참여자 그룹에서 조합을 구하는 코드의 리팩터링을 제안해봤어요. 확인 부탁드리고 궁금한것 있으면 언제든 물어봐주세요~

2024-08-07 02:05 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +}
페드로가 말한 최소인원을 파라미터로 받아 조합을 수행하는 로직으로 리팩터링을 해봤어요. ScheduleServiceTest에서 테스트 3개가 실패하지만 같은 인원수 사이의 순서 차이라 도메인 로직에 문제 없다고 생각합니다.

1. 재귀
```suggestion
public List<AttendeeGroup> findAttendeeGroupCombination() {
        List<AttendeeGroup> groupCombination = new ArrayList<>();
        addCombinationAttendeeGroup(new ArrayList<>(), groupCombination, 0, 2);
        return groupCombination;
    }

    private void addCombinationAttendeeGroup(
            List<Attendee> currentCombination,
            List<AttendeeGroup> groupCombination,
            int start,
            int combinationSize
    ) {
        if (currentCombination.size() >= combinationSize) {
            groupCombination.add(new AttendeeGroup(new ArrayList<>(currentCombination)));
        }

        if (currentCombination.size() == attendees.size()) {
            return;
        }

        for (int i = start; i < attendees.size(); i++) {
            currentCombination.add(attendees.get(i));
            addCombinationAttendeeGroup(currentCombination, groupCombination, i + 1, combinationSize);
            currentCombination.remove(currentCombination.size() - 1);
        }
    }
```
2. 스택(덱으로 대체)
```java
public List<AttendeeGroup> findAttendeeGroupCombination(int combinationSize) {
        List<AttendeeGroup> groupCombination = new ArrayList<>();
        Deque<List<Attendee>> stack = new ArrayDeque<>();
        stack.push(new ArrayList<>());

        while (!stack.isEmpty()) {
            List<Attendee> currentCombination = stack.pop();

            if (currentCombination.size() >= combinationSize) {
                groupCombination.add(new AttendeeGroup(new ArrayList<>(currentCombination)));
            }

            if (currentCombination.size() == attendees.size()) {
                continue;
            }

            for (int i = getLastAttendeeIndex(currentCombination); i < attendees.size(); i++) {
                List<Attendee> newCombination = new ArrayList<>(currentCombination);
                newCombination.add(attendees.get(i));
                stack.push(newCombination);
            }
        }
        return groupCombination;
    }

    private int getLastAttendeeIndex(List<Attendee> currentCombination) {
        return currentCombination.isEmpty() ? 0
                : attendees.indexOf(currentCombination.get(currentCombination.size() - 1)) + 1;
    }
```

2024-08-07 02:15 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +                .allMatch(new HashSet<>()::add);
저도 순간 헷갈렸네요ㅋㅋㅋ 배키의 설명이 정확합니다👍

2024-08-07 11:45 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +@EqualsAndHashCode
순서와 관련 없이 `서로 같은 attendee`만 들어있는 경우 `true`를 반환하도록 `equals()`를 오버라이딩 할 수 있지만, 이렇게 해도 될까 싶네요🥲
`AttendeeGroup`의 `attendees`의 타입이 `List`이기 때문에 의도하지는 않았지만 암묵적으로 순서를 보장한다는 의미가 담겨있다고 생각합니다. `@EqualsAndHashCode`는 이를 반영하여 올바르게 오버라이딩 했다고 생각해요! 
그래서 `@EqualsAndHashCode`는 그대로 두고 `AttendeeGroup`의 `attendees`의 타입을 `Set`으로 두는 방향이 더 좋을 것 같아요. 지금 로직으로는 `index`를 사용하여 조합의 경우의 수를 구하기 때문에 `attendees`의 타입을 `Set`으로 바꾸기가 어렵습니다. 그래서 뒤에 말해준 로직을 사용하면 `Set`으로 바꾸는 것도 쉬워질 것 같아서 로직을 수정한 뒤에 한번 바꿔보겠습니다.

2024-08-07 11:53 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +        Map<LocalDateTime, AttendeeGroup> attendeeByDateTime = groupAttendeeByDateTime(schedules);
> 현재는 메서드 분리의 위계가 맞지 않는 것 같아요.

코드 컨벤션이 맞지 않다는 것을 말씀하시는 걸까요?

2024-08-07 11:58 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +        addCombinationAttendeeGroup(visited, groupCombination, 0);
> 지금 잘 생각은 안 나는데 재귀함수를 안 쓰고 조합을 구현할 수 있다면 나중에 그렇게 리팩토링하는게 제3자가 이해하기 편할 수도 있을 것 같아요.
(아래에 비트마스킹을 통한 해법 남겨 두었습니다)

비트마스킹이 훨씬 성능적으로 좋을 것 같다는 생각에 동의합니다! 다만, 비트마스킹이 다른 사람이 이해하기 쉬운 로직일까.. 싶습니다.(저도 지금 당장 어려워요😢) 물론 재귀 또한 직관적으로 알아보기 힘듭니다.. 두개 다 알아보기 어려운 상황에서 둘 중 하나를 선택하라면 성능이 더 좋은 것을 선택해야 하는 것이 아닐까 싶네요. 한번 적용해 보도록 하겠습니다~

2024-08-07 12:03 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +        addCombinationAttendeeGroup(visited, groupCombination, 0);
> 저희는 '가장 많이 겹치는 시간'에 관심이 있는 것이기 때문에, 조합 리스트를 '각 원소의 길이가 긴 순'으로 정렬하여 전달하는 게 최적화 면에서 유리할 것 같네요!


어제 전달한 것처럼, '가장 많이 겹치는 시간대로 정렬'이라는 로직은 '시간 추천 기능' 로직 중 하나 입니다. `AttendeeGroup`의 `findAttendeeGroupCombination()`함수는 단순히 `AttendeeGroup`의 조합만을 반환하는 기능을 담당하고 있습니다. 이와 같은 조합을 정렬하는 역할은 `ScheduleRecommender`가 맡아야 한다고 생각합니다. 즉, `AttendeeGroup`은 시간 추천 기능의 특정 로직인 '가장 많이 겹치는 시간대로 정렬'을 알 필요 없이, 오직 조합만을 반환하면 된다고 생각합니다..!

2024-08-07 12:10 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/ScheduleRecommender.java
> +package kr.momo.service.schedule;
`ScheduleRecommender`은 '추천 기능'에 사용될 가장 시간이 빠른 순으로 정렬, 가장 오래 만날 수 있는 시간 순으로 정렬에 필요한 `comparator`를 반환하는 것이 주된 로직입니다. `ScheduleService`는 반환받은 `comparator`로 `response`를 정렬하고요. 

`ScheduleRecommender`가 도메인 로직에 있으려면, 추천 로직 외에도 다른 곳에서 쓰여야 한다고 생각합니다. 그러나 현재 `ScheduleRecommender`는 다른 서비스 로직에 사용되지 않습니다. ScheduleService의 recommendSchedules()함수에서만 쓰입니다. 함수가 너무 길어져서 서비스의 로직을 뺀 느낌으로 `ScheduleRecommender`를 구현했습니다. 그래서 사실 service에 더 가깝다고 생각했는데, 도메인 쪽에 더 가깝다고 생각한 페드로의 구체적인 의견이 궁금합니다~

(사실, 응용 서비스 로직과 도메인 로직의 차이를 구분하기 어렵네요 🥲 조금 더 설명이 가능할까요?)

2024-08-07 12:12 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/ScheduleRecommender.java
> +    private static Comparator<ScheduleRecommendResponse> descendingByAttendees() {
앞의 리뷰에 대한 답글 확인 부탁드립니다~

> 어제 전달한 것처럼, '가장 많이 겹치는 시간대로 정렬'이라는 로직은 '시간 추천 기능' 로직 중 하나 입니다. AttendeeGroup의 findAttendeeGroupCombination()함수는 단순히 AttendeeGroup의 조합만을 반환하는 기능을 담당하고 있습니다. 이와 같은 조합을 정렬하는 역할은 ScheduleRecommender가 맡아야 한다고 생각합니다. 즉, AttendeeGroup은 시간 추천 기능의 특정 로직인 '가장 많이 겹치는 시간대로 정렬'을 알 필요 없이, 오직 조합만을 반환하면 된다고 생각합니다..!

2024-08-07 13:43 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +        List<LocalDateTime> sortedDateTimes = attendeeByDateTime.keySet().stream()
로직에 오류가 있었네요😅 
참여자의 수만 확인하니 확실히 로직이 전보다 간단해졌습니다👍👍

2024-08-07 13:46 UTC, ehBeak commented on backend/src/test/java/kr/momo/domain/attendee/AttendeeGroupTest.java
> +                .containsExactlyInAnyOrder(
앞에서 언급했던 이유로 일단은 그냥 뒀는데요..! 이 부분에 대해서 다시 이야기 나누면 좋을 것 같네요 :)

2024-08-07 14:46 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +}
두가지 경우를 다 제시해 주시다니..🥹 구체적인 예시 감사합니다!

2024-08-07 14:48 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +            addCombinationAttendeeGroup(isVisit, groupCombination, index + 1);
> 유틸성 클래스 하나가 늘더라도 List<T> 를 받아서 모든 조합을 List<List<T>> 혹은 Stream<List<T>> 형태로 반환해 주는 조합 클래스를 만드는 건 어떨까요?

해당 클래스를 만들게 되면 클래스의 함수가 AttendeeGroup을 매개변수로 받는 걸까요? 만약 그렇다면 AttendeeGroup에만 종속된 느낌일 것 같아요🙃 구체적으로 어떤 느낌인지 궁금합니다..!

2024-08-07 14:52 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +            addCombinationAttendeeGroup(isVisit, groupCombination, index + 1);
>+) 현재 참여자가 N 명이면 2^N 개의 조합쌍이 나오는 구조입니다.
이렇게 되면 15명만 참여해도 3만개 이상의 조합이 생겨서..나중에는 이것을 적당히 끊을 기준이 필요해 보여요!

예를 들어 15명이 필터링 조건으로 들어왔을 때, 참여자가 (15-3)개 이상의 조합쌍에 대해서만 계산을 해 준다던지 하는 방법으로요.

> 지금처럼 nC1 ~ nCn의 모든 조합쌍을 구하는 로직은 비트마스킹으로 쉽게 구할 수 있습니다.
모든 조합쌍이 2^N개라는 것을 잘 생각해 보면,
각 참여자를 하나의 비트에 할당하고 00..000 ~ 11..111 만큼의 쌍을 구하는 것이니,
단순히 for (int i = 0; i < N ; i++) {} 형태의 for문 하나로도 해결이 가능해요.

비트마스킹 방식을 잘 모르지만, 확실히 지금 로직 보다는 덜 복잡해 보일 것 같네요!
비트마스킹 방식을 사용하여 `nCr`을 구할 수 있도록 구현하고 반복문을 돌아, `nCn~nCr`의 모든 경우의 조합을 구하도록 구현했습니다.
단, `ScheduleService`에서 `findAttendeeGroupCombinationsOverSize(int size)` 를 호출할 때 상수 1 값을 넣어줘서 `nCn~nC1`까지 모든 경우의 수를 구하도록 설정해 뒀습니다. 매개변수를 어떻게 넣을지 이야기 해보는 것이 좋을 것 같아요!

2024-08-07 15:02 UTC, ehBeak commented
리뷰 감사합니다.. 제 코드가 점점 인간다움을 찾아가고 있어요🥹🥹

리뷰에서 가장 큰 변경 사항은 `AttendeeGroup`의 모든 조합을 구하는 방식입니다.
이전에는 백트래킹 방식으로 `nCn~nC0`까지 `AttendeeGroup`의 모든 조합을 구했습니다. 
그러나 이번에는 리뷰를 반영하여 비트마스킹을 사용했습니다. 로직은 아래와 같습니다.
`AttendGroup` 내부에서,
1. `findAttendeeGroupCombinations(int r)`을 사용하여 nCr의 경우의 수를 구할 수 있도록 구현합니다.
2. `findAttendeeGroupCombinationsOverSize(int minSize)` 내부의 반복문을 통해서 `findAttendeeGroupCombinations(i)`를 호출하여 `nCn~nCr` 까지 경우의 수를 구합니다.

테스트 코드는 다 돌아가지만, 혹시 로직에 문제가 있으면 리뷰 부탁드립니다.

+) 현재 `ScheduleService`에서 `findAttendeeGroupCombinations(1)`을 호출하여 `nCn~nC1`까지 전체 조합을 가져오고 있습니다. `r`을 어떤 방식으로 지정할지 이야기 나누면 좋을 것 같아요. 이후에 반영하겠습니다.

또한 리뷰에 대해서 의문점이나 상의할 내용은 코멘트 달았습니다. 확인 부탁드립니다~

2024-08-07 18:41 UTC, seokmyungham requested changes
배키!! 고생많으셨어요 🔥
전체적으로 이해하는데 시간이 많이 걸릴 것 같아, 우선적으로 궁금한 사항과 개선 방안을 남깁니다!

2024-08-07 18:41 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +    private List<LocalDateTime> filterCommonScheduleDateTimes(List<Schedule> schedules, AttendeeGroup targetGroup) {
`filterCommonScheduleDateTimes()`, `groupingAttendeesByDateTime()`, `filterAndSortCommonDateTimes()`

세 메서드가 하는 전체적인 역할이
그룹에 속한 참가자들의 공통 시간을 찾아내서 정렬하는 것이라고 이해했어요. 맞을까요?

맞다면 복잡한 집계 연산 로직을 모두 어플리케이션에서 처리하는 것 보다는
데이터베이스에 적절히 책임을 분산해서 도움을 받아서 효율적으로 처리할 수 있을 것 같아요.

```sql
SELECT ad.date, s.timeslot
FROM schedule s
JOIN available_date ad ON s.available_date_id = ad.id
WHERE s.attendee_id IN (1, 2) 
GROUP BY ad.date, s.timeslot
HAVING COUNT(s.attendee_id) = 2
ORDER BY ad.date ASC, s.timeslot ASC;
```
```java
@Query("""
    SELECT ad.date AS date, s.timeslot AS timeslot 
    FROM Schedule s 
    JOIN s.availableDate ad 
    WHERE s.attendee.id IN :attendeeIds 
    GROUP BY ad.date, s.timeslot 
    HAVING COUNT(s.attendee.id) = :groupSize 
    ORDER BY ad.date ASC, s.timeslot ASC
    """
)
```

위는 native sql이고, 아래는 jpql 이에요. 
필요에 따라 ORDER BY는 없어도 될 것 같습니다.

2024-08-08 02:25 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +@EqualsAndHashCode
순서 보장 부분은 차치하고서라도, `@EqualsAndHashCode`를 사용하면 내부적으로 `Attendee`의 `equals()` 를 사용하게 됩니다.

현재 `Attendee`의 `equals()` 가 별도로 정의되어 있지 않으므로, `System.identityHashCode()`를 기준으로 비교를 하게 되는데 이렇게 되면 동일한 내용의 `Attendee`객체라도 메모리 주소값이 달라지면 다른 객체로 판단합니다.

그렇다면 `AttendeeGroup`의 경우 `['페드로@0x0c', ''배키@0x0a']`와 `['페드로@0x0c', ''배키@0x0f']` 는 동일한 그룹으로 평가받지 못하겠네요.

따라서 `Attendee`의 `equals()` 를 명시적으로 재정의해야 해요.
`Attendee`가 엔티티임을 감안했을 때, 기본적인 비교는 `id` 필드를 기준으로 하되, `id`가 `null`일 경우에 한해(영속화되지 않은 attendee의 group을 만들 수도 있을 것 같아서 이 경우에 대한 처리가 필요합니다.) 필드 조합을 기준으로 비교해야 할 것 같은데 어떻게 생각하시나요?

2024-08-08 02:28 UTC, seokmyungham requested changes

2024-08-08 02:28 UTC, seokmyungham commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +@EqualsAndHashCode
아 무슨 의도인지 이해했습니다.
그런데 `@EqualsAndHashCode` 하나로 의도하신 목적이 잘 수행될지 의문이 듭니다.

그리고 Service에서 `findAttendeeGroupCombination` 메서드를 호출하는 부분이 있던데 반환 값이 `List<AttendeeGroup>`이 아니라 `Set<AttendeeGroup>`이 되어야 하는게 아닐까요?

2024-08-08 06:53 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +@EqualsAndHashCode
> 그리고 Service에서 findAttendeeGroupCombination 메서드를 호출하는 부분이 있던데 반환 값이 List<AttendeeGroup>이 아니라 Set<AttendeeGroup>이 되어야 하는게 아닐까요?

네 이걸 말씀드린 겁니다. `equals()`를 명시적으로 재정의 하는 것보다 `Set`으로 바꾸는 것이 올바른 방향인 것 같습니다. 
당연히 `equals()`를 명시적으로 오버라이딩 하지 않는 이상 순서를 고려하기 때문에 `['페드로@0x0c', ''배키@0x0a']`와 `['페드로@0x0c', ''배키@0x0f']`는 동일한 객체가 아닙니다. 이를 해결하기 위해서는 2가지 선택지가 있습니다.
1. 명시적으로 순서를 고려하지 않도록 `equals`를 오버라이딩
2. `attendees`의 필드 타입을 List가 아닌 `Set`으로 수정

그 중에서 2번을 선택하는 것이 더 올바른 방향인 것 같다는 말이었습니다. `attendees`의 타입을 List로 설정하고 equals를 명시적으로 오버라이딩하면, `euqals()`에서 본래 의도했던 역할과 달라지니까요..!

2024-08-08 07:05 UTC, Largopie commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +        LocalDateTime now = startTime;
동의합니다.

2024-08-08 08:20 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +        }
앗 findAttendeeGroupCombinationsOverSize()를 내부에 넣어줘서 검증하려 했는데, 제가 잘못 두었네요! 리뷰 감사합니다~

2024-08-08 08:27 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +    public List<AttendeeGroup> findAttendeeGroupCombinationsOverSize(int minSize) {
>  현재는 결국 1로 전달되어 nCn ~ nC1 을 모두 구하고 있지만, 실행구조가 k 값을 유동적으로 변화시킬 수 있게 작성된 것으로도 의미를 가진다고 생각합니다.

네 맞습니다. 이 값은 팀끼리 이야기 해서 정하거나 받아야 하기 때문에 그대로 두겠습니다.

2024-08-08 08:40 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +        if (r < 1 || r > attendees.size()) {
검증 로직의 위치를 제가 잘못 두었네요. 수정했습니다~

2024-08-08 08:41 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
> +    private List<AttendeeGroup> generateCombinations(int groupSize) {
네 이후에 해보면 좋을 것 같네요! 테스트 코드도 확인했습니다. 고민해 보겠습니다~

2024-08-08 08:58 UTC, ehBeak commented
### 변경사항
(1) AttendGroup은 Set으로 변경하는 과정 중에 테스트 코드를 수정하는데 어려움이 있어서 equals를 명시적으로 오버라이딩 했습니다. 그러나 이후에 리팩토링해야 할 필요가 있습니다.

(2) 응답 형식을 수정했습니다. 전체 참가자 이름을 반환하는 부분은 분리하고 data를 통해서 추천 목록을 반환하도록 수정했습니다.

2024-08-08 09:05 UTC, seunghye218 approved these changes
서비스 로직의 복잡도가 높아 N이 커진다면 응답 까지 오랜 시간이 걸리겠네요. 일단 구현이 되었으니 approve 하고 나중에 리팩터링 해야할듯합니다!

2024-08-08 09:06 UTC, hw0603 approved these changes
진짜 고생 많았습니다ㅋㅋㅋㅋ🚀 이만 Approve 할게요!

2024-08-08 09:07 UTC, ikjo39 approved these changes

2024-08-08 09:12 UTC, seokmyungham approved these changes
고생하셨습니다 ㅋㅋ 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
기능이 구현된 것 같긴한데 리팩토링도 열심히 같이 해보면 좋을 것 같아요
배키 화이팅 🎉🎉🎉

2024-08-08 09:14 UTC, merged