[FE] API 명세 수정에 따른 변경사항 반영
woowacourse-teams/2024-momo pull request #140
Opened 2024-08-01 06:26 UTC by Largopie

## 관련 이슈

- resolves: #이슈 번호

## 작업 내용

https://paper-mass-5ff.notion.site/API-0c2e6beb3c4c44f2984872320d2a53d0?pvs=4

수정 사항은 노션 링크에 자세하게 남겨두었습니다.

- API 명세 변경으로 인한 수정 사항 반영
- `fetchClient`함수의 try, catch 제거
- `BASE_URL` 수정
- `Schedules`, `SingleAttendeeTimeSlot` 두 타입의 중복 해소
- `meetingFrame` -> `meetingBase`로 용어 전제 통일

## 특이 사항

하나는 type폴더 하위, 몇개는 파일 상위에 정의되어있는 것이 통일성이 어긋나보여서 현재 파일의 가장 최상단에 interface를 선언해두었습니다. 이 타입 파일을 어떻게 관리할 지에 대해서도 얘기를 나누어보면 좋을 것 같아요!

## 리뷰 요구사항 (선택)

API 관련되어서 피드백 얼마든지 환영입니다!

2024-08-01 06:46 UTC, hwinkr requested changes
디스코드 알림 테스트

2024-08-01 06:49 UTC, Yoonkyoungme requested changes
고래밥 감사합니다 :) 디스코드 알림 테스트

2024-08-01 07:26 UTC, hwinkr reviewed
코멘트 디스코드 알림 테스트

2024-08-01 07:44 UTC, Yoonkyoungme submitted a review, later dismissed
작업 단위를 잘 쪼개서 커밋 하셨군요! 덕분에 수정 사항을 파악하기 편했습니다 👍

2024-08-01 15:46 UTC, hwinkr requested changes
고생하셨습니다 낙타~🐪

사소하다면 사소하다고 할 수 있는 인터페이스명에 대한 고민도 공유해줘서 좋았고, 제가 추상화 한 `fetchClient` 함수 구현에 대해서도 그냥 넘어가지 않고 더 좋은 방법을 모색하기 위한 의문을 던져준 것도 좋았습니다~
사용자에게 예외 피드백을 전달할 때 컴포넌트 측에서 `isPaused` 를 적극적으로 활용하면 네트워크 off 상태에 대한 처리도 해줄 수 있을 것 같네요!

간단한 요청 사항 몇개 남겼습니다~ 반영해주시면 감사하겠습니다~ㅎㅎ

2024-08-01 15:46 UTC, hwinkr commented on frontend/src/apis/_common/getHeaders.ts
> +export default function getHeaders(): HeadersInit {
엥 이거 그냥 제공해주는 유틸리티 타입이였나요...🥺

2024-08-01 15:46 UTC, hwinkr commented on frontend/src/apis/attendee.ts
> +  const url = `${BASE_URL}/${uuid}/login`;
공통되는 api 주소를 묶으니까 더 보기 좋네요 👍

2024-08-01 15:46 UTC, hwinkr commented on frontend/src/apis/attendee.ts
> +const postAttendeeLogin = async (props: PostAttendeeLoginRequest): Promise<AttendeeLogin> => {
[P3]
함수형 컴포넌트 props를 받는 컨벤션에서 미리 구조분해를 한 후 받기로 했었는데요.
해당 함수도 그 컨벤션을 맞춰서 구현 내부에서 구조분해 하기 보다 인자를 선언하는 쪽에서 미리 하는 건 어떨까요? ☺️

2024-08-01 15:46 UTC, hwinkr commented on frontend/src/apis/meetings.ts
> +interface GetMeetingResponse {
[P3]
해당 인터페이스 네이밍도 `GetMeetingBaseResponse`로 통일해보는 것은 어떨까요? ☺️

2024-08-02 01:30 UTC, hwinkr approved these changes
리뷰 반영 감사합니다~

2024-08-02 01:32 UTC, Yoonkyoungme approved these changes
오!!!!! 드디어👍👍👍👍👍👍👍

2024-08-02 01:34 UTC, merged