[BE] 로그아웃 기능 추가
woowacourse-teams/2024-momo pull request #151
Opened 2024-08-02 13:18 UTC by seokmyungham

## 관련 이슈

- resolves: #132 

## 작업 내용

- 로그아웃 기능을 추가하였습니다.
    - API 요청 시 저장되어있는 쿠키 만료 시간을 0으로 설정합니다.
- AccessToken의 만료 시간을 새롭게 설정하였습니다.
- 로그인 시 로그인한 참가자의 이름(닉네임)을 ResponseBody에 저장하여 반환하도록 변경하였습니다.

## 특이 사항

- 현재는 AccessToken만 다루고 있으나, 추후 기능이 모두 완성되어 안정화 되었을 때 RefreshToken을 도입할 수 있을 것 같습니다.

## 리뷰 요구사항 (선택)

2024-08-02 19:51 UTC, hw0603 requested changes
늦은 시간에 고생하셨습니다~

몇 가지 코멘트 남겨 두었어요.

2024-08-02 19:51 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +    private static final String SAME_SITE_SETTING = "None";
`SAME_SITE_OPTION`이 좀 더 자연스럽지 않을까요?
사소한 건데, 다른 분들의 option, setting, config을 사용하시는 맥락이 궁금하네요ㅎㅎ

2024-08-02 19:51 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
> +    private final JwtCookieManager jwtCookieManager;
질문) 꼭 필요한 인스턴스화인가요? `JwtCookieManager.createCookie` 처럼 사용하는 것과 차이는 무엇인가요?

2024-08-02 19:51 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +        String cookie = jwtCookieManager.createNewCookie(response.token(), response.uuid(), -1);
코드를 처음 본다면 `-1` 이 어떤 의미인지 궁금할 것 같아요

2024-08-02 19:51 UTC, hw0603 commented on backend/src/main/java/kr/momo/exception/code/AuthErrorCode.java
> +    UNAUTHORIZED_TOKEN(HttpStatus.UNAUTHORIZED, "유효하지 않은 토큰입니다.");
중복된 문맥을 하나로 합쳐 주셨네요👍

2024-08-02 19:51 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/attendee/dto/AttendeeLoginResponse.java
> +public record AttendeeLoginResponse(String token, String name) {
현재는 이름만 내려주고 있기는 한데, 사용자의 `HOST` 여부도 필요할지 프론트 측과 이야기 해 봐야 할 것 같아요

(명시적인 사용자 권한을 응답으로 내려도 되는 건지는 잘 모르겠네요🥲 어떻게 생각하시나요?)

2024-08-02 19:51 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                      @Value("${security.jwt.expiration_period}") long expirationPeriod) {
메서드/생성자 파라미터 개행 컨벤션 적용 필요해 보입니다!

2024-08-02 19:51 UTC, hw0603 commented on backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
> +        String token = response.cookie("ACCESS_TOKEN");
👍

2024-08-03 05:02 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +    private static final String SAME_SITE_SETTING = "None";
개인적인 생각으로는
`SETTING`을 사용하면 해당 상수는 SameSite를 구성하는 목적을 갖는 값이라는 의미가 잘 드러나는 것 같고
`OPRION`을 사용하면 해당 상수는 SameSite의 여러 옵션 중 하나라는 맥락이 더 잘 담기겠네요.. ㅋㅋㅋ

개발자간에는 서로 동의어처럼 사용되는 것 같고, UX와 관련된 것이 아니라면 일관성이 제일 중요할 것 같아요
Option, Setting, Config.. 정답이 없는 문제라 너무 어려운데요 😂

2024-08-03 06:18 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
> +    private final JwtCookieManager jwtCookieManager;
스프링 빈으로 관리하느냐와 정적 클래스로 사용하느냐의 생각은 사람마다 조금씩 다를 것 같은데 몇 가지 기준이 있을 것 같아요.

- 정적 클래스로 사용할만큼 클래스의 목적이 명확하고 항상 일관된 입출력을 가지는지
- 유틸 성격을 띌 경우 공통적인 메서드로만 구성되어 프로젝트 전역에 광범위하게 영향을 미치는지
- 추후 해당 클래스가 상태나 의존성을 가질 가능성이 존재하는지
- 스프링 컨테이너에 관리하는 이점이 존재하는지 (Test, LifeCycle, DI, IOC)

더 자세하게 들어가보면 제가 생각하는 장단점은 다음과 같습니다.
- 정적 클래스로 사용
    - 간단하게 사용할 수 있다.
    - 의존성에 관한 코드를 작성하지 않아도 된다.
    - 유연하지 못하고 강결합이 발생한다.
    - Mock이 불가능하기 때문에 의존하는 클래스를 테스트하기 어렵다.
- 스프링 빈으로 관리하여 사용
    - DI의 장점을 가질 수 있다. (유연한 설계, 확장 및 테스트)
    - 스프링이 지원하는 환경 설정과 연동할 수 있다 (yml)
    - 컨테이너에 빈이 하나 추가 됨으로 관리 포인트가 늘어난다.

스프링의 DI 탄생 배경을 생각해봤을 때, 저는 스프링을 사용한다면 거의 웬만한 상황에서 스프링의 도움을 받는 것이 좋다는 생각입니다. 미래 확장 가능성을 배제하고 현재 상황에만 집중하여 하나 둘 씩 정적 클래스가 늘어나면, 나중에는 감당 못할만큼 유연하지 못한 설계가 되어있을 가능성이 크다 생각합니다. (그치만 이 의견은 사람마다 많이 갈리는 것 같습니다)

제 생각들을 배제하고, 이 클래스를 빈으로 만든 이유는 제가 추후 확장 가능성을 정확히 예측할 수 없었기 때문인데요. 추후 환경 변수에 의존할 가능성이 없을지? 로그나 모니터링 툴을 도입했을 때 체크 포인트로 사용될 시점으로 사용될 가능성이 없을지 잘 모르겠습니다. (현재 학습하지 않아 이 부분에 대한 제 지식이 부족합니다.)

현재 상황만 본다면 정적 클래스로 사용해도 무방한 기능들을 가지고 있는데요, 될 수 있으면 해당 기술에 지식이 있는 팀원들 모두의 동의를 거쳐 결정했으면 좋겠다는 생각입니다.

2024-08-03 06:19 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +        String cookie = jwtCookieManager.createNewCookie(response.token(), response.uuid(), -1);
의견에 동의합니다. 변경할게요 👍

2024-08-03 06:36 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/attendee/dto/AttendeeLoginResponse.java
> +public record AttendeeLoginResponse(String token, String name) {
음.. 정말 `HOST`, `GUEST` 여부에 따라 사용자에게 화면을 다르게 보여줘야 한다면, 해당 값을 응답으로 내려주어야 할 것 같네요.

그런데 사용자 권한이기는 하지만 현재 약속 만들고 확정하는 일이 
게시글을 작성하고 삭제하거나 투표를 만들고 종료하는 상황과 비슷한 느낌이 들기는 해요. 🤔 
엄밀하게 검토해보고 비슷한 상황에 대한 레퍼런스를 찾는 건 어렵지 않으니 한 번 적용해볼 수 있을 것 같아요 😀

2024-08-03 06:38 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                      @Value("${security.jwt.expiration_period}") long expirationPeriod) {
엇... 새벽에 하다보면 역시 이런 실수가 나오는군요..

2024-08-03 08:24 UTC, ikjo39 reviewed
재즈 고생하셨어요 😄 
몇가지 리뷰 남겼으니 확인 부탁드립니다!

2024-08-03 08:24 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                .withExpiresAt(expirationDate)
만료기한을 claim으로 추가해주셨는데 `IssedAt()`설정을 추가로 claim으로 넣어주신 이유가 궁금합니다!

2024-08-03 08:24 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +            @Value("${security.jwt.expiration_period}") long expirationPeriod
[Spring 공식 문서](https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.vs-value-annotation)에선 직접 만든 컴포넌트에 한해선 `@Value`보다  `@ConfigurationProperties`를 권장한다는 말이 있네요. 😵‍💫

첨부한 링크부터 아래 읽어보시면 좋을 것 같습니다!

2024-08-03 08:53 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
> +    private final JwtCookieManager jwtCookieManager;
> 스프링의 DI 탄생 배경을 생각해봤을 때, 저는 스프링을 사용한다면 거의 웬만한 상황에서 스프링의 도움을 받는 것이 좋다는 생각입니다.

좋은 접근법인것 같네요🙂

2024-08-03 09:03 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                .withExpiresAt(expirationDate)
만료기한을 추가하면서 발행시각도 필요하지 않은지 생각했었는데 필수적인 내용은 아니군요. 제 착각이었습니다 😅

현재 토큰을 재사용한다거나 추적이 필요하지는 않으니 삭제해도 될 것 같네요. 그런데 보안에 활용할 수 있는 메타데이터를 포기하는 만큼, 만료 기한을 조금 더 짧게 가져가야 할 필요가 있을 것 같긴합니다.

2024-08-03 09:24 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +            @Value("${security.jwt.expiration_period}") long expirationPeriod
오 😮 좋은 내용 감사합니다 👍
읽어보니 단순한 개별 속성인 경우 `@Value`가 간단하고 직관적으로 좋은 선택이지만, 위 처럼 관련 설정 속성이 여러 개인 경우 POJO로 묶어 관리하는 것을 권장하네요. 

`@Value`가 지원하는 SpEL 표현식이 필요하지 않으니, 객체로 구조화하여 타입 안정성 확보하는 것이 좋은 선택일 것 같아요. 확장 가능성도 염두할 수 있겠군요 👍

2024-08-03 09:45 UTC, hw0603 requested changes
JWT 만료 시간 관련 리뷰 하나 더 드렸습니다. 확인 부탁드려요!

2024-08-03 09:45 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                .withIssuedAt(new Date())
`Date` 객체는 생성자에서 밀리초 단위의 값을 받지만, JWT 헤더에 기록될 때는 밀리초 단위가 절사되어 기록됩니다. (초단위로 기록)


<img width="250" alt="image" src="https://github.com/user-attachments/assets/ee85e9a5-380a-414e-bfb8-85be692e51e2">

`expirationPeriod`의 로컬 기본값이 `3600`으로 설정되어 있는 것으로 확인했는데요, 이는 3.6초에 해당하여 현재 설정에서 JWT 디코드 시 발행일자와 만료일자가 4초(3.6초에서 반올림) 차이가 납니다.
의도하신 사항이 맞으실까요? 아니라면 단위 수정이 필요할 것 같아요.

이런 혼선을 방지하기 위해 프로퍼티 이름을 `expiration-period-in-hour` 과 같이 단위를 명시해 주는 방법도 있겠네요. 그 단위에 맞춰서 `JWTManager`에서는 밀리초 단위로 변환하여 `Date`객체를 만들어야 할 것 같습니다.

(yml 프로퍼티명은 외부 파일에서 주입받는 값이기 때문에 이름만 보고도 값을 "오해 없이" 정확하게 알 수 있어야 한다고 생각해요.)

이때 `ms` 단위로 변환하기 위해서는 값이 매우 커질 텐데요, `long`에서는 오버플로우 문제가 발생할 수 있습니다.

참고하실 만한 링크 하나 공유해 드릴게요.

- https://sundries-in-myidea.tistory.com/150

2024-08-03 09:45 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                .withIssuedAt(new Date())
+ 생성하신 JWT 토큰을 꼭 Decode 해 보시고, 원하는 값이 잘 들어갔는지 눈으로 확인해 보시는 걸 추천드려요!

2024-08-03 09:59 UTC, ehBeak reviewed
재즈 고생하셨어요! 
팀원들이 좋은 리뷰 남겨주셔서 저는 간단하게 코멘트 남깁니다~👍

2024-08-03 09:59 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +    private static final String SAME_SITE_SETTING = "None";
> OPITON을 사용하면 해당 상수는 SameSite의 여러 옵션 중 하나라는 맥락이 더 잘 담기겠네요.. ㅋㅋㅋ

위에 써주신 이유로, None은 옵션 중 하나이기 때문에 `SAME_SITE_OPTION`이 더 적절해 보입니다~
CookieResponse.sameSite(SAME_SITE_OPTION) 함수를 통해서 그 옵션을 설정(setting)해 주는 것이라고 직관적으로 이해할 수 있을 것 같아요!

2024-08-03 09:59 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +public class JwtCookieManager {
현재 `JwtManager`가 따로 있기도 하고  이 클래스 에서 하는 일은 `만료 쿠키 생성`, `새로운 쿠키 생성`, `쿠키 생성`이니, `CookieManager`로 바꿔도 좋을 것 같아요.
쿠키 값을 jwt 토큰을 사용하긴 하지만, 현재 이 클래스는 String으로 받는 값이 jwt 토큰인지 알지 못하니까요..!

2024-08-03 09:59 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +    private String createCookie(String value, String path, long maxAge) {
정~~~~~말 사소한 것인데, 매개변수 명을 `value` 보다는 `token`을 쓰면 좋을 것 같아요..ㅎ

2024-08-03 10:04 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                .withIssuedAt(new Date())
ms 단위인 걸 알면서도 미처 확인하지 않았네요. 좋은 지적 감사합니다 👍

2024-08-03 10:07 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +    private String createCookie(String value, String path, long maxAge) {
클래스 이름에서 Jwt를 제거하면 모든 매개변수에 value를 사용하는게 더 자연스러울 것 같은데 어떤가요?? 😀

2024-08-03 10:07 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +public class JwtCookieManager {
좋네요 👍

2024-08-03 10:24 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/auth/JwtManager.java
> +                .withIssuedAt(new Date())
![image](https://github.com/user-attachments/assets/a1e221d1-01a3-44b1-b3d7-335bd0f5f2f8)

`System.currentTimeMillis()` 메서드로 현재 기준 약 1.7조ms 를 확인했고 long타입의 정수 범위를 생각했을 때 오버플로우 문제는 발생하지 않을 것 같습니다. int 타입이 문제가 될 것 같아요.

현재 타입을 유지하고 코드를 개선해보겠습니다 🚀

2024-08-03 10:35 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +    private String createCookie(String value, String path, long maxAge) {
넵 value가 더 좋을 것 같네요! ` ResponseCookie.from(ACCESS_TOKEN, value)` 내부에서도 value라는 이름을 쓰고 있고요 👍

2024-08-03 11:34 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/JwtCookieManager.java
> +    private static final String SAME_SITE_SETTING = "None";
팀원들의 소중한 의견 반영했습니다 😁

2024-08-03 12:07 UTC, ehBeak submitted a review, later dismissed
🎉🎉🎉

2024-08-03 12:19 UTC, ikjo39 approved these changes

2024-08-03 13:42 UTC, seokmyungham commented
### 변경 사항

JWT와 관련된 환경 변수들을 POJO로 관리할 수 있도록 `JwtProperties`를 추가하였습니다.
- Spriting docs에 따르면 관련된 설정 속성이 여러개인 경우 `@Value` 보다는 `@ConfigurationProperties`로 관리하기를 권장합니다.
- `Properties Conversion` 기능을 활용하여 `Duration` 단위를 환경 변수에 명시할 수 있습니다. 기존 millis 단위를 계산해야 했던 개발자의 실수를 줄이도록 개선하였습니다.
- 더 나아가 발생할 수 있는 실수를 줄일 수 있도록 `Duration`의 기본 단위를 `@DurationUnit` 으로 명시하여 문서화 하였습니다.
- 더불어 `@Validated` `@NotNull`을 사용하여 환경 변수가 존재하지 않는 상황에 컨텍스트가 로드되는 상황을 방지하였습니다.

2024-08-03 16:19 UTC, hw0603 requested changes

2024-08-03 16:19 UTC, hw0603 commented on backend/src/main/java/kr/momo/MomoApplication.java
> +@ConfigurationPropertiesScan
단순히 ConfigruationProperty를 활성화하기 위한 빈 클래스였던 `JwtConfig`을 제거하고 스캔 방식으로 변경해 주셨네요👍

2024-08-03 16:19 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +        String cookie = cookieManager.createNewCookie(response.token(), response.uuid(), -1);
`-1` 값 상수화 필요해 보여요! 위에서는 컨트롤러의 상수로 관리하고 계시던데, 여러 컨트롤러에서 필요하니 차라리 `CookieManager`의 상수로 관리하면 어떨까 합니다. 오버로딩을 통해 max-age 값이 전달되지 않으면 `-1`로 설정하는 방식도 고려해 볼 수 있겠네요

2024-08-03 17:08 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/CookieManager.java
> +        return String.format("/meeting/%s", uuid);
상수인지 아닌지 조금 애매한 것 같은데, 애초에 `CookieManager`의 책임이 아니라는 생각이 드네요.
책임에 맞도록 컨트롤러로 이동시켰습니다. 🚀

2024-08-03 17:08 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +        String cookie = cookieManager.createNewCookie(response.token(), response.uuid(), -1);
동의합니다. 👍

2024-08-04 05:30 UTC, hw0603 approved these changes

2024-08-04 10:49 UTC, ikjo39 approved these changes

2024-08-04 10:53 UTC, seunghye218 approved these changes
CookieManager를 분리하여 다양한 컨트롤러에서 사용해야할 로직을 잘 재사용하네요. JWT 가 들어있는 쿠키에 httpOnly, secure 옵션을 통해 보안이 잘 되어있는 것 같아요 👍

2024-08-04 11:50 UTC, merged