[FE] 버튼 컴포넌트 재구성
woowacourse-teams/2024-momo pull request #154
Opened 2024-08-03 16:39 UTC by Largopie

## 관련 이슈

- resolves: #144 

## 작업 내용

> [작업 내용 정리]
> https://paper-mass-5ff.notion.site/Button-036a7d6f927d48408e89455c23866de9?pvs=4

- 현재 구현 가능한 가장 최소한의 버전(v0.1)을 만들었습니다. 추후에 이를 지속적으로 발전시키면 좋을 것 같습니다.
- 아이콘의 위치를 좌, 우 조정할 수 있도록 children으로 구현했습니다.
- `BaseButton`을 구현하고, 해당 컴포넌트를 기반으로 `PrimaryButton`, `SecondaryButton`을 구현했습니다.
- `size prop`에서 기존에는 `l` 사이즈도 있었지만, 지금 바로 사용하지 않을 뿐더러 정해놓은 디자인이 없어 제외시켰습니다.
    - xs : 네이밍 태그 적용 시 사용
    - s : 로그인, 로그아웃
    - m : 수정하기
    - full : 최하단 버튼 및 공유 하기 버튼

## 특이 사항

- 추후 확장하고 싶은 버튼이 있다면 BaseButton을 기반으로 구현하면 좋을 것 같습니다.

## 리뷰 요구사항 (선택)

만든 컴포넌트는 **"공통"** 컴포넌트이기 때문에 어떻게 사용하는지 궁금하거나 prop네이밍 부분에서도 궁금한점이 있다면 자유롭게 말해주세요!

2024-08-05 16:12 UTC, Yoonkyoungme reviewed
🐪낙타🐪 유연한 버튼 공통 컴포넌트 만드느라 고생 많았어요!!
가벼운 코멘트 달아두었으니 천천히 확인해보세요 :)

2024-08-05 16:12 UTC, Yoonkyoungme commented on frontend/src/styles/tokens/typography.ts
> -    lineHeight: '1.5',
뭔가 typography에서 lineHeight를 제거하는게 옳은 방향은 아닌 것 같은데,
버튼 안 텍스트가 미세하게 가운데 정렬이 안 되는 문제를 해결할 수 있는 방법을 모르겠네요😭😭

2024-08-06 00:15 UTC, hwinkr requested changes
낙타 버튼 공통 컴포넌트 만드신다고 고생하셨습니다~

간단한 수정 사항 요청과 함께, 궁금한 사항들을 코멘트로 남겨두었습니다!!  
더 빠르게 리뷰를 드렸어야 했는데...🥺  

제 리뷰를 받았으니, 오늘 하루 행복할 것입니다!! 🍀🍀🍀

2024-08-06 00:15 UTC, hwinkr commented on frontend/src/components/_common/Button/Button.styles.ts
>  `;
[P2]

현재, 이 방식으로 버튼의 스타일을을 만들어가면 새로운 버튼 variant 스타일이 나올 때마다 새로운 스타일 객체를 정의해야할 것 같아보입니다...! 그래서, s_buttonVariants 라는 하나의 공통 스타일 객체를 만들고 이 객체에 primary, seconday 스타일을 정의해보는 것은 어떨까요??

```js
const s_buttonVariants = {
  primary : 
  secondary :
}
```

이런식으로요!!! :)

2024-08-06 00:15 UTC, hwinkr commented on frontend/src/components/_common/Button/index.tsx
> +  }
@Yoonkyoungme 

해당 추천 코드에서 filter(Boolean)을 한 번더 하는 이유가 있을까요~?

2024-08-06 00:15 UTC, hwinkr commented on frontend/src/components/_common/Button/index.tsx
> +}
[P2]

PrimayButton, SecondaryButton 컴포넌트도 새로운 버튼 컴포넌트들이 필요할 때마다 새롭게 컴포넌트를 정의해야할 것 같은데 `variant = 'primary' | 'seconday'`를 props로 받아서 css 함수와 엮어서 사용해보는 것은 어떨까요~!?

2024-08-06 00:15 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.stories.tsx
> +} satisfies Meta<typeof Calendar>;
엥 이거 왜 `typeof Button`으로 되어있었던거죠...실수했나보네요 제가...ㅋㅋ

2024-08-06 00:15 UTC, hwinkr commented on frontend/src/components/_common/Button/Button.styles.ts
> +  gap: 0.4rem;
[Comment]

낙타가 말하는 두 개의 요소가 혹시 아이콘, 텍스트를 함께 사용하는 경우를 말하는 것일까요??

2024-08-06 00:49 UTC, hwinkr commented on frontend/src/styles/tokens/typography.ts
> -    lineHeight: '1.5',
**[COMMENT]**

낙타가 타이포그래피 관련해서 발견한 문제에 대해서, 현재 제가 생각했을 때 가장 괜찮은 방법은 타이포그래피를 구성하는 스타일 속성들을 하나 씩 구분하는 것 같아요.  

- `font-size`
- `font-weight`
- `line-height`
- `letter-spacing`(현재 사용하는 속성은 아니지만)

해당 속성들을 따로 구분한 후, TYPOGRAPHAY를 만들 때는, 분리된 스타일 속성들을 다시 조합하는 방향으로 수정하고, 버튼 컴포넌트를 만들 때는 line-height를 1로 고정한 후, font-size와 font-weight를 가져와서 사용하면 될 것 같아요.  

다들 제가 제시하는 방법에 동의하신다면 낙타 버튼 작업이 머지 된 후, 따로 이슈를 파서 개선해보도록 하겠습니다!!!  

낙타가 말해줬던 문제를 한 줄로 정의해보면 "'TYPOGRAPHY' 스타일 객체에 모든 스타일이 미리 정의되어 있어 다른 상황에서 유연하게 재사용하기 힘들다" 인 것 같아요. 그래서 가장 쉽게 미리 정의된 스타일 객체들의 프로퍼티들을 다시 하나 씩 분리하는 방법을 생각해 봤어요 :)

2024-08-06 06:26 UTC, Largopie reviewed
반영 사항 반영해두었습니다 :) 확인 후 다시 검토 부탁드립니다! 🙇‍♂️

2024-08-06 06:26 UTC, Largopie commented on frontend/src/components/_common/Button/index.tsx
> +  }
해리가 제안한 방식대로 수정한다면 코드의 depth가 깊어질 문제도 함께 해결되겠네요!

2024-08-06 06:26 UTC, Largopie commented on frontend/src/styles/tokens/typography.ts
> -    lineHeight: '1.5',
요상한 현상인데, 저도 그걸 해결하기 위해서 다시 한 번 line-height 속성을 적용했는데 이상하게 잘 되네요...?
그래서 일단 원래대로 복구는 시켜뒀습니다.

예상컨데, 높이를 강제해줘서 해당 높이에 맞게 typography 속성이 눌려버린듯한(?) 느낌도 있어요...
궁금하시다면 스토리북에 구현해두었으니 확인 부탁드리겠습니다 :)

2024-08-06 08:38 UTC, hwinkr commented on frontend/src/components/_common/Button/index.tsx
> +  onClick,
> 1. 사용자는 각 prop의 역할을 파악하기 어렵습니다. 내가 사용하는 prop이 오버라이딩된 prop인지 파악이 어렵기 때문에 예상하지 않은 형태로 동작할 가능성이 있습니다. 또한 IDE에 의해 불필요한 prop들이 같이 나열되기 때문에 공통 컴포넌트 개발자가 의도하지 않은 prop을 사용할 수 있습니다.
> 
> 2. 유지보수 관점에서 어려움이 있습니다. 리팩토링을 진행하면 겉보기 동작(observable behavior)은 변하지 않아야 하는데 리팩토링 후 모든 prop이 같은 기능을 수행할 것이라 장담하기 어렵기 때문입니다. 만일 공통 컴포넌트를 사용하는 곳들에서 잘 쓰이지 않는 prop들을 사용하고 있다면 모든 케이스에 대응하고 검증하는 과정이 어려울 것입니다.

낙타가 제공해 준 링크에서 내용들을 읽었는데, 솔직히 1번 관점은 휴먼 에러랑 관련이 많이 되어 있는 것 같아서 실수만 하지 않는다면 큰 문제는 발생하지 않는 것 같아 공감이 되지 않았습니다. 하지만 2번 관점에서는 공통 컴포넌트가 모든 HTML Attribure들을 사용할 수 있도록 인터페이스를 확장해서 열어두고 있고, 잘 쓰이지 않는 속성들을 사용했을 때 예상하지 못한 문제가 발생한다면 2번에서 말하는 문제처럼 모든 케이스에 대응하기는 힘들 것 같다는 생각이 드네요.   

무조건 모든 HTML Attribute를 열어두는 것이 좋다고 생각했었는데, 낙타의 의견과 글을 읽으니 생각이 약간 바뀌게 된 것 같아요. 관성적으로 인터페이스를 확장해서 컴포넌트를 정의했던 제 습관을 고칠 수 있겠군요...! 굿입니다 낙타.

2024-08-06 08:40 UTC, hwinkr commented on frontend/src/components/_common/Button/index.tsx
> +export type ButtonSize = 'xs' | 's' | 'm' | 'full';
저도 낙타의 의견에 동의하기는 합니다만 `Button.styles.ts` 파일에서 컴포넌트 파일에서 정의한 타입을 가져와서 사용하는 것이 약간 어색하게 느껴져서 했던 제안이었습니다...!  

데모데이 끝나고 타입 설정의 방향성에 대해서 더 이야기를 나눠봐야 겠군요...:)

2024-08-06 08:47 UTC, hwinkr approved these changes
리뷰 반영 고생하셨습니다~  
리뷰어들이 남긴 의견을 그냥 수용하는 것이 아니라 항상 한 번더 생각하고 본인만의 의견을 굳세게 유지하는 점이 보기 좋은 것 같아요~  
낙타의 의견에는 다 근거가 있네요...(너는 근거가 다 있구나....)
<img width="345" alt="image" src="https://github.com/user-attachments/assets/f938c97e-0fed-4f76-8d5c-247c18b1cfd9">

2024-08-06 13:58 UTC, Yoonkyoungme approved these changes
오👍🏻👍🏻 원래도 좋았지만, 훨씬 코드가 깔끔해졌네요
고생하셨습니다 낙타🐪
내일도 화이팅🍀

2024-08-07 00:52 UTC, merged