Feat/130 tooltip
woowacourse-teams/2024-momo pull request #156
Opened 2024-08-04 12:40 UTC by hwinkr

## 관련 이슈

- resolves: #130

## 작업 내용

(우선 디버깅을 하느라, 예상보다 작업이 훨씬 많이 소요되어 PR 제출이 늦어진 점 죄송합니다...🥺  
디버깅했던 컴포넌트들은 현재 버리기는 아까워 `legacy` 폴더에 있습니다!)

### 툴팁 컴포넌트 구현

재사용 가능한 툴팁 컴포넌트를 구현했습니다.

### 1) 사용법

```tsx
export const Playground: Story = {
  args: {
    content: <div>안녕하세요 툴팁입니다</div>,
    children: <button>마우스를 올려보세요</button>,
    position: 'top',
  },
  render: (args) => {
    return (
      <Tooltip content={args.content} position={args.position}>
        {args.children}
      </Tooltip>
    );
  },
};
```
- content : 툴팁을 사용해서 보여줄 컴포넌트
- children : 툴팁 렌더링을 트리거하는 컴포넌트, 위 스토리북 예시에서는 버튼이 됩니다.
- position : **children을 기준으로** 툴팁을 보여줄 위치, 동서남북 + 4가지 대각선 방향 총 8가지 방향이 있습니다.

### 2) 구현 과정

툴팁 구현할 때, 최대한 관심사를 분리하고자 했습니다.

- 툴팁을 어느 방향에서 보여줄지를 결정하는 책임
- 결정된 위치에 따라서 툴팁의 세부 위치를 결정하는 책임 (top, left)

따라서 `<Tooltip />` 컴포넌트가 툴팁 렌더링을 트리거하는 컴포넌트를 `children`으로 가지고 있고, 해당 props의 위치에 따라서 `content`가 렌더링 될 위치를 결정하도록 했습니다.  
`position : absolute` 속성을 사용했고 부모 요소(relative)기준으로 상대적인 위치를 구할지, React.createPortal을 사용하여 document.body 기준 절대적인 위치를 구할지 고민했었습니다. 현재는 부모 요소 기준 상대적인 위치를 구하는 것이 8가지 방향에 대해 공수가 너무 많이 드는 작업이라고 생각해 createPortal을 사용해서 절대적인 위치를 사용해서 구현했습니다. 평소에 상대, 절대 위치 중 어느 것을 선호하시는지 리뷰를 할 때 함께 달아주시면 감사하겠습니다!! :) 

### 3) 2차원 테이블 셀 내부 툴팁의 위치 
<img width="514" alt="image" src="https://github.com/user-attachments/assets/c9b5c768-d49f-46af-81d5-0ac921ebf6ae">  
2차원 테이블 셀 내부에서 툴팁을 어느곳에 렌더링해야할 지 고민을 한 결과, 일단은 2차원 셀을 **최대한 벗어나지 않는 곳**으로 툴팁을 렌더링하고자 했고, 꼭짓점이나 양 끝의 경우 최대한 안쪽으로 툴팁이 렌더링될 수 있도록 했습니다.

## 특이 사항

### Header 스타일 변경

현재 헤더 컴포넌트의 스타일이 고정되어 있지 않은데, `sticky` 속성을 사용하는 것으로 고정했습니다.

### 글로벌 레이아웃 스타일 변경

기존에는 height가 고정되어 있고, overflow-y 속성이 있었는데 툴팁이 렌더링 된 상태에서 스크롤을 하게 되면 툴팁의 위치는 고정되어 있고 툴팁 뒤 영역만 렌더링되는 문제가 있었습니다. 알고보니, 고정된 height와 관련된 문제였고 따라서 이 속성을 제거하게 되었습니다. 

## 리뷰 요구사항 (선택)

### 툴팁 위치 결정 상대 vs 절대

부모 요소의 위치를 활용한 상대적인 위치를 사용하는 편인지, createPortal을 사용한 절대적인 위치를 사용하는 편인지 알려주세요 ㅎㅎ

아래는 이번 툴팁 기능을 구현하면서 두 방식을 비교한 내용입니다.

---

createPortal을 사용하면, body 기준으로 렌더링 요소의 위치를 결정하기 때문에, 절대값 기준으로 위치를 설정하면 된다. 예를 들어, 툴팁을 렌더링 할 때 툴팁 트리거 컴포넌트의 오른쪽에 띄워야 한다면

```tsx
right: css`
top: ${targetRect.top + targetRect.height / 2 + window.scrollY}px;
left: ${targetRect.right + window.scrollX}px;
transform: translate(0, -50%);
`,
```

이렇게 위치를 결정할 수 있을 것이다.

만약, createPortal을 사용하지 않는다면 부모 요소 기준으로 상대적인 위치를 결정해야 한다. 따라서,

```tsx
right: css`
top: 50%;
left: 100%;
transform: translateY(-50%);
`,
```

이렇게 위치를 결정해야 한다.

만약, 부모 요소에 종속되지 않고 위치를 독립적으로 결정하고 싶다면 createPortal을 사용할 수 있을 것이다.

2024-08-05 12:49 UTC, Largopie requested changes
안녕하세요 해리~! 구현하신 부분 너무 잘 봤습니다 :) 주말에 해주신 컨텍스트 공유도 너무 좋았어요! 덕분에 코드를 읽는데 더 수월했던 것 같습니다!

많은 고민하고 구현해주신게 느껴졌습니다 :)
현재 아까 오후에 공유한 css 위치 선정되는 부분에 대한 문제 함께 해결해주시면 감사드리겠습니다!

추가적으로 질문에 대한 답변입니다!
> 부모 요소의 위치를 활용한 상대적인 위치를 사용하는 편인지, createPortal을 사용한 절대적인 위치를 사용하는 편인지 알려주세요 ㅎㅎ

경우에 따라 많이 달라지는 내용이 될 것 같다는 생각이 먼저 들었어요!
현재 경우로 보았을 때, 저 같은 경우 툴팁은 어떻게 보면 table 기준에서만 작동이 이루어지는 컴포넌트이다보니 테이블 측에서 상대경로로 구현했을 것 같네요!

기능 구현하느라 너무 고생했습니다 :) 반영사항 반영 부탁드리며, 남은 데모데이도 화이팅~! 🐫

2024-08-05 12:49 UTC, Largopie commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +    <>
[P3]
저도 알아봐야 하는 사항이지만, 이 Fragment를 사용할 때만 import React from 'react'를 해야하는 부분이 조금 불편하게 느껴지더라구요..! 제가 나중에 해결방법을 찾아오겠습니다.

2024-08-05 12:49 UTC, Largopie commented on frontend/src/components/Schedules/Schedules.util.ts
> +  return 'top';
[P3]
지금 현재 상태로 보면 가장 바깥 상태에 위치해있는 표에 대해서만 로직 처리가 되어있고 그 외 내부 컴포넌트는 모두 'top'속성을 갖는 것으로 이해했습니다. 그렇게 되면 `rowIndex = 1`을 갖는 로직도 'top'으로 처리가 되어 어느정도 넘는 부분이 생길 것 같아요!

현재로서 구현할 수 있는 최선으로 구현해주신 것으로 생각하는데, 추후에 이를 더 잘 이용할 수 있도록 함께 고민해봐야할 것 같아요!

2024-08-06 08:00 UTC, Yoonkyoungme requested changes
해리 툴팁 만드느라 정말 고생 많았습니다!!!!!!! 대단하네요👏👏👏👏
백로그에 작성해주신 부분도 잘 읽었습니다 :) 덕분에 코드 리뷰할 때 해리가 어떤 고민을 가지고 문제를 해결하였는지 알 수 있었어요
legacy 코드들 넘 아쉽네요ㅜㅡㅜ (깔끔해서 더 아쉬워요) 스프린트 끝나고 스크롤 문제 같이 해결해봐요

2024-08-08 06:12 UTC, Largopie approved these changes
해리 복잡한 기능 구현하느라 고생했습니다 :)
시간 관계상 더 깊게 모든 코드를 파악하기는 어려웠지만, 여러 주석 덕분에 이해하는데 많은 도움이 되었어요!

리뷰 남긴 부분 확인 부탁드립니다!

2024-08-08 06:15 UTC, Largopie requested changes
실수로 어프루브를 눌러서 다시 RC 요청합니다 😭

2024-08-08 06:55 UTC, Yoonkyoungme requested changes
해리꺼 로직이 너무 어려워요😭 고생하셨습니다 👏👏👏
이전 리뷰와 현재 리뷰 확인해주세요 :)

2024-08-08 06:55 UTC, Yoonkyoungme commented on frontend/src/hooks/useDatePage/useDatePage.ts
> +  );
**[P3]**
`slice(currentDatePage * DATES_PER_PAGE, (currentDatePage + 1) * DATES_PER_PAGE)` 가
`usePagedTimePick` hook에서도 사용되네요. 이 부분을 함수로 빼서 재사용 하는건 어떤가요?

2024-08-08 06:55 UTC, Yoonkyoungme commented on frontend/src/hooks/useDatePage/useDatePage.ts
> +  };
**[P3]**
함수 선언 사이에 개행해주실 수 있나요?

2024-08-08 06:55 UTC, Yoonkyoungme commented on frontend/src/mocks/meeting/data/meetingAllSchedules.json
> +        "attendeeNames": ["해리", "낙타", "빙봉"]
아싸 내 이름도 있다 🔮🔮🚀🤸‍♀️😆

2024-08-08 10:25 UTC, hwinkr commented on frontend/src/components/_common/Tooltip/index.tsx
> +  }, [visible]);
동의합니다..! 툴팁을 트리거하는 컴포넌트의 rect 정보를 얻은 후, 디버깅에 활용하기 위해서 useEffect 훅을 사용했던 것인데, 기능 구현이 완료되었으니 지우도록 하겠습니다~

2024-08-08 10:26 UTC, hwinkr commented on frontend/src/components/AttendeeTooltip/AttendeeTooltip.styles.ts
> +`;
툴팁 컴포넌트를 구현할 당시에는, 디자인 토큰 pr이 머지가 되지 않은 상태라 사용하지 못했었는데 활용해보도록 할게요~

2024-08-08 10:35 UTC, hwinkr commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +  };
변수끼리는 개행을 하지 않고, 붙어서 선언을 하고 함수끼리는 개행을 하는 편이라는 말씀이신가요??? 좋네요!!

낙타의 의견에 더해 변수끼리도 관심사 분리를 해서, 관심사가 일치하는 변수끼리는 개행을 하지 않고 다른 변수들끼리는 개행을 해도 좋을 것 같아요!

2024-08-08 10:36 UTC, hwinkr commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +    <>
Fragment를 사용할 때마다, 런타임 에러가 발생해서 너무 당황스럽더라구요...! 이번 데모데이 끝나면 함께 알아보시죠!

2024-08-08 10:43 UTC, hwinkr commented on frontend/src/types/tooltip.ts
> +  | 'rightBottom';
`BasePosition`, `CombinedPosotion`를 구분하는 것을 통해 타입에서도 관심사를 분리하면 좋겠다는 의견이신가요?? `top` `left` `right` `bottom`은 다른 타입들과도 엮어서 확장성 장점을 챙길 수 있을 것 같아서 좋네요! 타입 분리 해보겠씁니다 ㅎㅎ

2024-08-08 10:51 UTC, hwinkr commented on frontend/src/components/AttendeeTooltip/AttendeeTooltip.utils.ts
> +      s.time === `${rowIndex + parseInt(firstTime.slice(0, 2))}:00`,
헉 지금 코드는 find메서드로 반복문을 돌 때마다 계속해서 동일한 값을 담는 변수를 계속해서 선언하고 있네요, 가독성도 좋지 않고 메모라 효율 관점에서도 좋지 못한 코드를 작성한 것 같습니다~ 좋은 피드백 고마워유

2024-08-08 10:53 UTC, hwinkr commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +    if (selectedAttendee === attendee) return;
해당 조건문이 필요하다고 생각했던 이유는, 사용자가 현재 보고 있는 사용자와 클릭한 사용자가 같은 경우 setState 호출로 인한 리렌더링이 필요하지 않다고 생각했기 때문입니다! 그래서 현재 `selectedAttendee` 상태와 클릭한 `attendee`의 값이 같으면 early return 하도록 했어요!

2024-08-08 10:54 UTC, hwinkr commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +        `}
급하게 구현하느라 디테일적인 부분을 놓친 것 같아요! 빠르게 수정하겠습니다 ㅎㅎ

2024-08-08 10:55 UTC, hwinkr commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +      </div>
`git pull --rebase origin develop`을 하면 충돌을 위한 공수가 너무 많이 들 것 같아 일단 기본 버튼으로 수정해 둘게요 :)

2024-08-08 10:56 UTC, hwinkr commented on frontend/src/hooks/useDatePage/useDatePage.ts
> +interface UserDatePageReturn {
사실 이 오타는 제가 여러분들이 코드 리뷰를 꼼꼼하게 하는지 확인하기 위한 이스터에그였습니다. 하하... 장난이고 예리하네요 낙타. 역시...사막에서 살아남으려면 강해져야하나 봐요

2024-08-08 10:57 UTC, hwinkr commented on frontend/src/components/Schedules/AllSchedule.tsx
> +                  `}
하하..꼼꼼한 낙타

2024-08-08 10:58 UTC, hwinkr commented on frontend/src/components/Schedules/Schedules.styles.ts
> +  -webkit-box-pack: justify;
필요없는 속성인 것을 알게되어 수정하도록 할게요...!

2024-08-08 10:59 UTC, hwinkr commented on frontend/src/components/Schedules/Schedules.styles.ts
> +    margin-left: calc(5rem); /* Adjust according to your needs */
정말 아무일도 일어나지 않네요...ㅋㅋ ~~(정신이 없었나 봅니다.)~~

2024-08-08 11:31 UTC, hwinkr commented on frontend/src/hooks/usePagedTimePick/usePagedTimePick.ts
> +    currentValue,
의미있는 변수명을 잘 사용해보도록 하겠습니다! ㅎㅎ

2024-08-08 11:34 UTC, hwinkr commented on frontend/src/hooks/useDatePage/useDatePage.ts
> +  };
낙타, 빙봉 모두 함수 선언 사이에는 개행을 원하는 것 같군요~ 저는 관심사가 비슷한 즉, 위 코드 예시처럼 페이지 관리를 한다는 비슷한 역할을 하는 함수 사이에는 개행을 하지 않았는데 저는 이 부분이 취향 차이라고 생각해서 개행을 추가해 보도록 하겠습니다!

2024-08-08 11:40 UTC, hwinkr commented on frontend/src/hooks/useDatePage/useDatePage.ts
> +  );
# TODO 리뷰 반영하기

2024-08-08 12:02 UTC, Largopie approved these changes
반영하느라 수고하셨습니다 :) 사소한 리뷰사항 몇 가지 남겨드렸으니 확인 부탁드려요~! 🐫

2024-08-08 12:02 UTC, Largopie commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +        <button onClick={handleToggleIsTimePickerUpdate}>수정하기</button>
rebase 요구할려고 했는데 봐 드리겠습니다 ^&^🐫🎶룰루랄라

2024-08-08 14:34 UTC, Yoonkyoungme commented on frontend/src/components/Schedules/SchedulesViewer.tsx
> +    if (selectedAttendee === attendee) return;
react의 상태 업데이트는 상태 값이 변경되었을 때만 컴포넌트를 리렌더링하기 때문에 조건문이 따로 필요없다고 생각했어요 :)

이거에 대해서는 왜 생각대로 동작하지 않는지 같이 딥다이브 해보죠🍡

2024-08-08 14:35 UTC, Yoonkyoungme approved these changes
고생하셨습니다 해리🍀

2024-08-08 14:36 UTC, Yoonkyoungme commented on frontend/src/hooks/useDatePage/useDatePage.ts
> +  );
이번 스프린트 끝나고 꼭 반영해주세요 ^^

2024-08-08 15:38 UTC, merged