[FE] 공용 토글 버튼 컴포넌트 구현
woowacourse-teams/2024-momo pull request #158
Opened 2024-08-05 06:38 UTC by Largopie

## 관련 이슈

- resolves: #155  

## 작업 내용

https://paper-mass-5ff.notion.site/47545046f8414544aa193d164d9ed578?pvs=4

작업 내용 및 특이사항 노션에 기록해두었습니다 :)

## 특이 사항

- stylelint 관련 에러 발생(노션에 "구현 중 발견한 Stylelint 에러" 참고)

## 리뷰 요구사항 (선택)

`isClicked` 라는 네이밍이 살짝 어색하게 느껴지는데 다른 의견 있으면 자유롭게 부탁드립니다! 🙇‍♂️

2024-08-05 16:31 UTC, Yoonkyoungme requested changes
낙타~~ 빠르게 구현해 주셨군요!! 고생 많으셨습니다🤸‍♀️

2024-08-05 16:31 UTC, Yoonkyoungme commented on frontend/src/components/_common/ToggleButton/ToggleButton.styles.ts
> +  left: -1000%;
**[Q]**
`left: -1000%`는 무엇을 위한 설정인가요? 🫨 

아하 해당 스타일 속성을 업애면 아래처럼 보이는군요 ...! 
<img width="241" alt="image" src="https://github.com/user-attachments/assets/79bedca0-154f-4e53-a86e-b9e5ad60230b">

**[P3]**
주석으로 간략하게 설명을 남겨두면 좋을 것 같네요!

2024-08-05 16:31 UTC, Yoonkyoungme commented on frontend/src/components/_common/ToggleButton/index.tsx
> +  isClicked: boolean;
**[P3]**
`isClicked` 대신 `isToggled` 어떤가요?

2024-08-05 16:31 UTC, Yoonkyoungme commented on frontend/src/components/_common/ToggleButton/index.tsx
`Button` 관련된 컴포넌트들은 
`components/_comoon/Button` 디렉터리 하위에 위치시키는 것은 어떨까요?

ex)
components/_common
 ㄴ Button
     ㄴ BaseButton
     ㄴ ToogleButton
     ㄴ NavigateButton
     ㄴ AuthButton
     ㄴ HomeButton

2024-08-05 16:33 UTC, Yoonkyoungme commented
++ 사소하지만 `Button 스토리북`에서 `CustomText` 버튼의 텍스트가 길어서 버튼을 벗어나네요 😭 
<img width="827" alt="image" src="https://github.com/user-attachments/assets/ce654559-76fa-474a-9136-9be9d2f4bde7">

2024-08-06 00:33 UTC, hwinkr reviewed
토글 버튼 만든다고 고생했씁니다 낙타!!!

간단한 코멘트 달았는데, RC를 날릴까 하다가 사소한 것이라서 반영해도, 안해도 크게 문제가 되지 않을 것이라 판단해 코멘트로 요청합니다 ㅎㅎ

2024-08-06 00:33 UTC, hwinkr commented on frontend/src/components/_common/Header/Header.styles.ts
> +
[Comment]

린트가 적용이 안되다가, typography 관련 문제가 해결되어 다시 적용된 것일까요~?

2024-08-06 00:33 UTC, hwinkr commented on frontend/src/components/_common/ToggleButton/index.tsx
> +        <span css={s_switch}>선택</span>
**[Q]**

`선택`이라는 텍스트의 스타일이 `display : none`인데, 보이지 않게 하는 요소에 텍스트를 추가한 이유가 있을까요~? 웹 접근성을 위해서라면, `aria-label`등 html 어트리뷰트를 활용하면 좋을 것 같아요!

2024-08-06 00:33 UTC, hwinkr commented on frontend/src/components/_common/ToggleButton/index.tsx
> +      <input type="checkbox" id={id} checked={isClicked} css={s_input} />
**[Comment]**

토글 버튼은 input 태그를 활용해서 만들 수 있겠군요... 한 번도 만들어보지 않은 컴포넌트라서 인풋 태그를 사용해서 만든다는 것을 처음 알았네요...! 웹 접근성을 위해서 해당 태그를 활용한다고 보면 될까요?? (궁금궁금)

2024-08-06 00:33 UTC, hwinkr commented on frontend/src/components/_common/ToggleButton/ToggleButton.stories.tsx
> +};
[P3]

False, True로는 어떤 UI가 그려질지 예상하기 힘든 것 같습니다...!

그래서 스토리 이름을 Toggled, UnToggled로 변경해보는 것은 어떨까요~? :)

2024-08-06 00:33 UTC, hwinkr commented on frontend/src/components/_common/ToggleButton/ToggleButton.stories.tsx
> +  decorators: [
**[Comment]**

데코레이터 활용 좋습니다!!

2024-08-06 07:55 UTC, Largopie reviewed
수정사항 반영해서 답글 남겼습니다 :) 확인 후 재검토 부탁드려요~ 🐫

2024-08-06 07:55 UTC, Largopie commented on frontend/src/components/_common/ToggleButton/index.tsx
> +        <span css={s_switch}>선택</span>
먼저 좋은 질문 감사합니다 해리 👍

저번에 하루와 aria-label과 일반 label에 대해서 대화를 나눈 기억이 있었는데, aria-label은 일부 스크린 리더에는 지원이 안된다고 하셨던 기억이 나서 관성적으로 사용을 안했던 것 같네요 😅. 직접 확인해보고자 찾아봤는데 아직 관련 레퍼런스는 찾지 못했습니다.

그래서 구글 스크린리더 익스텐션을 설치해서 테스트해봤는데 정상적으로 잘 동작하네요! aria-label로 이용하면 좋을 것 같습니다!

깊게 연관된 것은 아니지만 관련 자료 함께 남겨드려요!
https://bootcamp.uxdesign.cc/when-to-use-aria-label-or-screen-reader-only-text-cd778627b43b

2024-08-06 07:55 UTC, Largopie commented on frontend/src/components/_common/ToggleButton/index.tsx
> +      <input type="checkbox" id={id} checked={isClicked} css={s_input} />
원래는 저도 button 태그로 이용해보려 생각을 했습니다!
그런데 `checkbox`로 이용하게 되면 어차피 `checked` 프로퍼티는 항상 `true`, `false`값을 가지기 때문에 해당 체크박스로 구현하는 것이 더욱 좋을거라고 판단했습니다 :)

특별하게 웹 접근성을 고려한 것은 아니고 취향차이인 것 같아요 :)

2024-08-06 07:55 UTC, Largopie commented on frontend/src/components/_common/ToggleButton/index.tsx
현재 공통 컴포넌트로 구현한 버튼이 수정사항이 생겨서 기존 Button의 이름을 그대로 사용하게 되었는데요..!
그래서 Button 하위에 두기엔 이미 존재하는 Button 컴포넌트가 있어서 애매한 느낌이 있는 것 같습니다.

이름 자체는 매우 비슷하지만, 내부 구현되어 있는 로직이 다르기도 해서 파생상태가 아니다 보니 폴더구조를 어떻게 잡아야할지 현재는 감이 오지 않네요!!

현재는 여러 버튼이 존재하기보다는 기존의 Button으로 디자인이 충분히 가능할 것이라는 생각도 들어서 더이상 Button 관련된 컴포넌트가 생길까 싶기도 한 생각이 듭니다!

기존의 Button 컴포넌트를 유지하면서 다른 좋은 의견이 혹시 있으실까요~? 😭

2024-08-06 08:48 UTC, hwinkr commented on frontend/src/components/_common/ToggleButton/index.tsx
> +        <span css={s_switch}>선택</span>
탐구 정신 미쳤다 송재석...

2024-08-06 09:22 UTC, hwinkr approved these changes
리뷰 반영 고생하셨습닏~~

2024-08-06 09:22 UTC, hwinkr commented on frontend/src/components/_common/ToggleButton/ToggleButton.stories.tsx
> +export const UnToggled: Story = {
👍👍👍

2024-08-06 13:48 UTC, Yoonkyoungme commented on frontend/src/components/_common/ToggleButton/index.tsx
현재 구현한 Button(=index.tsx)을 BaseButton으로 네이밍을 변경하고

ToggleButton을 Button 디렉터리 내로 이동시키는건 어떨까요?

지금 구조는 Button 속성을 띈 컴포넌트들이 흩어져있다는 느낌이 들어요🥲

2024-08-06 13:49 UTC, Yoonkyoungme approved these changes

2024-08-06 13:49 UTC, Yoonkyoungme commented on frontend/src/components/_common/ToggleButton/index.tsx
현재 구현한 Button(=index.tsx)을 BaseButton으로 네이밍을 변경하고

ToggleButton을 Button 디렉터리 내로 이동시키는건 어떨까요?

지금 구조는 Button 속성을 띈 컴포넌트들이 흩어져있다는 느낌이 들어요🥲

@Largopie

2024-08-07 04:03 UTC, merged