[FE] 비회원 로그인 로직을 백엔드의 쿠키 기반 인증 방식에 맞게 수정
woowacourse-teams/2024-momo pull request #159
Opened 2024-08-05 12:14 UTC by Yoonkyoungme

## 관련 이슈

- resolves: #126 

## 작업 내용

### apis/fetchClient
- 백엔드의 JWT 토큰을 쿠키 기반 인증 방식으로 변경에 맞춰 클라이언트의 로그인 상태 관리 방식을 수정했습니다.
- `credentials: 'include'` 옵션을 사용하여 쿠키를 자동으로 포함시키도록 설정하였습니다.

### contexts/AuthProvider
- 로그인 상태(`isLoggedIn`)와 사용자 이름(`userName`)을 `Context`로 관리하였고, `localStorage`를 사용하여 페이지 새로고침 시에도 상태가 유지되도록 하였습니다.

### components/Header
- `Header` 컴포넌트에서 `useParams`를 사용하여 UUID가 존재할 경우에만 로그인/로그아웃 버튼을 표시하도록 구현하였습니다.
- 약속 생성 페이지에서는 로그인/로그아웃 버튼을 숨기고, 약속 참여 페이지에서만 버튼이 보이도록 하였습니다.

## 특이 사항

- 낙타의 #154 PR이 아직 merge되지 않았기 때문에 로그인/로그아웃 버튼의 경우 기본 button 태그를 사용하였습니다. (스타일링 적용 X) -> 추후 BaseButton component를 상속 받아 구현할 예정입니다.

- 토큰 만료로 인한 401 에러 발생시 isLoggedIn, userName, 로그인페이지로 router처리 등은 아직 구현하지 않았습니다. (에러 발생시 처리할 로직을 담당하는 작업을 할 때 포함해야 할 것 같아요. 시간이 되면 이번 스프린트 때 해보고, 안 되면 다음 스프린트 때 본격적으로 해봅시다)

### 참고 자료
[작업 현황 정리 노션 링크](https://www.notion.so/b6afc846dec74efd9775952aa00be381?pvs=4)

## 리뷰 요구사항 (선택)

2024-08-05 14:50 UTC, Largopie requested changes
역시 빙봉 노션 정리 능력은 참 대단해요.. 항상 감탄하고 갑니다.
작업했던 내용이 이해가 쏙쏙 되는 것 같아요! 👍👍👍💯💯💯

리뷰 및 질문 남겼으니 답변 부탁드리겠습니다 :)

2024-08-05 14:50 UTC, Largopie commented on frontend/src/apis/attendee.ts
>  };
[Q]

fetchClient 함수에서 가져오는 값이 `data.data`로 이미 data로 감싸진 객체를 한 번 풀어서 내부 데이터만 가져오는 형식으로 갖추어져 있는 것으로 알고 있는데, 여기서는 data.data로 보내주는 것을 보니 JSON 데이터 형식이
```tsx
{
  data: {
    data: (유저이름)
  }
}
```

이와 같은 형식으로 되어있나요?

2024-08-05 14:50 UTC, Largopie commented on frontend/src/layouts/GlobalLayout.tsx
> +    </AuthProvider>
[Q]

다른 Provider는 index.tsx에 감싸져있는 것으로 알고 있는데 `AuthProvider`만 `GlobalLayout`에 감싸주신 이유가 있을까요? 🐫

2024-08-05 14:50 UTC, Largopie commented on frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
> +    navigate(-1);
[P3]
만약 바로 로그인 페이지로 직접적인 주소로 접속하게 된다면 -1 했을 때 로그인 페이지가 그대로 유지될 수도 있을 것 같습니다!
참고부탁드립니다!

2024-08-05 14:50 UTC, Largopie commented on frontend/package.json
꼼꼼함 굿! 👍👍👍👍

2024-08-05 14:50 UTC, Largopie commented on frontend/src/components/_common/Header/index.tsx
> +    navigate(`/meeting/${uuid}/login`);
[P3]

현재 로그인 된 상태에서 로그아웃을 누르면 현재 페이지가 그대로 유지되는 것을 기대할 것 같다고 생각합니다!
이 부분도 로그인, 로그아웃에 대해서 분기처리하면 어떨까요?

2024-08-05 14:50 UTC, Largopie commented on frontend/src/utils/auth.ts
> +  const userName = localStorage.getItem('userName');
[P3]
해당 key값도 상수로 분리되면 좋겠네요!

2024-08-05 15:05 UTC, hw0603 commented on frontend/src/utils/auth.ts
[P2] `localStorage`는 `Origin` 단위로 관리되기 때문에, 전역 `isLoggedIn`과 `userName`으로 관리하면 한 브라우저에서 여러 약속(다른 `uuid`)에 참여했을 때 문제가 생길 수 있을 것 같아요.

실제로 백엔드에서는 Cookie의 Path 값을 통해 약속 별 JWT를 별도로 관리하고 있습니다.

`localStorage`를 사용하실 예정이라면, `uuid`별로 사용자 로그인 여부와 이름을 관리할 수 있는 방법이 필요할 것 같아요🥲

2024-08-05 16:41 UTC, Yoonkyoungme commented on frontend/src/apis/schedules.ts
> +  const attendeeName = '빙봉'; // TODO: 임시 설정
헉쓰 이 부분 바꿔두는 것을 깜빡했네요😅 수정하겠습니다! 감안해서 리뷰 부탁드립니다

2024-08-06 03:18 UTC, Yoonkyoungme commented on frontend/src/utils/auth.ts
페드로의 요구 사항은 프론트 팀 모두가 이해를 했습니다...!  

궁금한 점이 몇가지 있어 추가 질문 드립니다! :)

1. Origin 단위로 관리된다는 것의 의미
- 해당 문장이 잘 이해되지 않습니다...!
- Origin = scheme + domain + port가 맞나요?
-> 한 Origin이 하나의 로컬 스토리지를 가질 수 있다는 의미인가요?

2. Path값의 의미
- Path가 어떤 값인가요?
  - uuid인가요?

2024-08-06 03:31 UTC, hw0603 commented on frontend/src/utils/auth.ts
1. 네 `localStorage`는 (스키마, 도메인, 포트) 당 하나로 관리되는 것으로 알고 있어요. 한 Origin은 하나의 로컬 스토리지만 가집니다.

2. URI 에서 `schem://domain:port/path#fragment` 에서 `path` 부분입니다. 브라우저에서 쿠키가 전송되려면 fetch의 요청 url이 쿠키의 path 속성을 prefix로 가져야 같이 전송됩니다.
예시를 들어 드리자면 쿠키의 Path 속성은 백에서는 `/api/v1/meetings/{uuid}/`로 설정해서 내려주고 있고, `/meeting/{uuid}` 에서 `POST /api/v1/meetings/{uuid}/schedule`을 요청했을 때, 자동으로 쿠키가 전송됩니다.

2024-08-06 07:57 UTC, hwinkr requested changes
빙봉뱅봉~  

로그인/로그아웃 기능 구현 고생하셨습니다...!

데모데이 당일 날 갑자기 로그인 기능이 추가되었고, 데모데이가 끝나자마자 request header에 JWT 토근을 담아서 보내는 방식에서 쿠키 자체를 서버에 보내는 방식으로 로그인 정책이 변경되어 정말 혼란스러운 상황 속에서 기능 구현을 했을 것 같아요...!  

이런 혼란스러움 속에서도 흔들리지 않고 기능 구현을 다 해주셔서 감사할따름입니다~~!!!  

파생 상태와 관련해서 코멘트를 남겼는데, 한 번 생각해보시고 답변 부탁드립니다.  

그리고 이번 데모데이 끝나면

- 로그인/로그아웃 텍스트가 적절한지
- 로그인 버튼의 위치가 헤더에 있는 것이 적절한지
  - 바텀 시트, 모달과 같은 다른 UI를 도입해보는 것은 어떤지

등등 UI와 관련된 결정 사항들이 아직 남아있다는 것을 인지해주시면 좋을 것 같아요!! 🔮🔮🔮

2024-08-06 07:57 UTC, hwinkr commented on frontend/src/apis/schedules.ts
> +  const attendeeName = '빙봉'; // TODO: 임시 설정
이런 사소한 실수는 오히려 수정 안하는 것이 인간답고 보기 좋네용~

2024-08-06 07:57 UTC, hwinkr commented on frontend/src/apis/_common/fetchClient.ts
> +const createFetchClient = (baseUrl: string) => {
`[Q]`

커링을 사용해서 `baseUrl`이 결정된 `fetchClient`를 만드는 것과, 클래스를 사용해서 `baseUrl`이 결정된 `fetchClient` 인스턴스를 만드는 것의 차이가 무엇이라고 생각하시나요?!!!

2024-08-06 07:57 UTC, hwinkr commented on frontend/src/contexts/AuthProvider.tsx
> +  const [userName, setUserName] = useState('');
**[COMMENT]**

isLoggedIn 상태는 useName 상태로 만들어지는 파생 상태로 관리할 수 있을 것 같은데 어떻게 생각하실까요??

```js
const isLoggedIn = userName === ''
```
위와 같이 **userName의 상태로 만들어지는 파생 상태로 관리할 수 있을 것 같아요..!**  이렇게 파생 상태로 관리하면 single source of truth 관점에서 장점도 챙길 수 있고, 개발자 도구를 열고 특정 사용자가 장난을 쳤을 때 예를 들어 `useName`이 있는 상태에서 `isLoggedIn` 상태를 `false`로 만들었을 때, 예외 상황이 발생할 것 같아서 파생 상태로 관리하는 것 어떻게 생각하시나요??

2024-08-06 07:57 UTC, hwinkr commented on frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
> +    navigate(-1);
**[COMMENT]**

사용자가 어떤 경로에서 로그인 페이지로 이동할지 알 수 없기 때문에, 로그인이 되어 있는 상태에서 로그인 페이지로 이동하면 navigate(-1)로 뒤로가기를 하기 보다는, MeetingTimePickPage로 이동시키면 좋을 것 같은데 이렇게 되면 어디선가 uuid값을 가지고 있어야 겠네요...흠  

로그인이 된 상태에서 로그인 페이지로 이동했을 때 예외 처리가 살짝 애매하긴 합니다.

2024-08-06 07:57 UTC, hwinkr commented on frontend/package.json
> -    "react-cookie": "^7.2.0",
**[Q]**

단순 궁금 사항인디, 저희 커밋 메시지 prefix에서 remove가 있었나요...?

2024-08-06 07:57 UTC, hwinkr commented on frontend/src/components/_common/Header/index.tsx
> +    navigate(`/meeting/${uuid}/login`);
**[COMMENT]**

저도 낙타의 의견에 동의합니다~ 로그아웃 버튼을 누르면 보통 현재 페이지에 그대로 머무르기 때문에 로그인 페이지로 강제로 이동시키는 것은 사용자 경험을 살짝 저하시킬 수 있는 요소라고도 생각합ㄴ디ㅏ..!

2024-08-07 11:07 UTC, Yoonkyoungme commented on frontend/src/apis/attendee.ts
>  };
### TODO
답글 달기

결론: 낙타 말 맞음 -> 어쩐지 localStorage에 제대로 값이 안 들어감 -> 그래서 수정함

2024-08-07 11:08 UTC, Yoonkyoungme commented on frontend/src/layouts/GlobalLayout.tsx
> +    </AuthProvider>
### TODO 답글달기

결론: AuthProvider가 router 경로에 접근 가능하게 하기 위해서

2024-08-07 11:20 UTC, Yoonkyoungme commented on frontend/src/apis/_common/fetchClient.ts
> +const createFetchClient = (baseUrl: string) => {
### TODO 답글달기

2024-08-07 11:47 UTC, Yoonkyoungme commented
@hwinkr @Largopie 

## 변경 사항
### 1. 비회원 로그인이 완료되면 로컬스토리지에 다음과 같은 형태로 저장됩니다.

```
uuid: {
  isLoggedIn: true,
  userName: "사용자이름"
}

```

> **[COMMENT]**
> 
> isLoggedIn 상태는 useName 상태로 만들어지는 파생 상태로 관리할 수 있을 것 같은데 어떻게 생각하실까요??
> 
> ```js
> const isLoggedIn = userName === ''
> ```
> 위와 같이 **userName의 상태로 만들어지는 파생 상태로 관리할 수 있을 것 같아요..!**  이렇게 파생 상태로 관리하면 single source of truth 관점에서 장점도 챙길 수 있고, 개발자 도구를 열고 특정 사용자가 장난을 쳤을 때 예를 들어 `useName`이 있는 상태에서 `isLoggedIn` 상태를 `false`로 만들었을 때, 예외 상황이 발생할 것 같아서 파생 상태로 관리하는 것 어떻게 생각하시나요??

해리의 파생 상태로 로그인 상태를 관리하자는 의견에 동의합니다! 이 부분은 향후 리팩터링에 적용하겠습니다 :)
(다만, 제 생각에는 개발자 도구를 통한 상태 변경 문제는 파생 상태로 관리해도 동일하게 발생될 것 같습니다. 추가적인 보안 조치가 필요할 수 있습니다!)

<br />

### 2. 약속 생성 시 자동 로그인
기존 PR에서는 주최자가 약속을 생성한 후에도 시간을 등록하려면 별도로 로그인을 해야 하는 문제가 있었습니다.
이를 해결하기 위해 약속 생성 시 자동으로 로그인되도록 수정하였습니다. 
관련 변경사항은 커밋 5279bef91790fe515e0aae0bed5119dcd76b539d에서 확인할 수 있습니다.

<br />

### 고민
로컬스토리지에 uuid별로 데이터가 계속 쌓이는 문제가 있습니다. 이에 대한 해결 방안을 고민 중입니다. 

- 일정 기간이 지난 데이터 자동 삭제
- 최대 저장 개수 제한 및 오래된 데이터부터 삭제
- 주기적으로 사용되지 않는 데이터 정리

이거에 대한 좋은 아이디어가 있을까요?🤔

2024-08-07 14:21 UTC, Largopie requested changes
고생하셨습니다 빙봉!
현재 공용 컴포넌트(`Button`)이 `develop` 브랜치에 머지된 상태라 바뀐 버튼으로 변경해도 좋을 것 같네요!

이외 드릴 피드백은 없는 것 같아요 :) 기나긴 로그인 로직 고민하느라 고생하셨습니다!

2024-08-07 14:21 UTC, Largopie commented on frontend/src/apis/_common/fetchClient.ts
👍👍👍

2024-08-07 14:21 UTC, Largopie commented on frontend/src/components/_common/Header/index.tsx
> +        </button>
[P2]
현재 로그인 공용 컴포넌트가 머지된 상태니 로그인 UI를 변경해도 괜찮을 것 같네요 :)

2024-08-07 14:53 UTC, hw0603 commented
>로컬스토리지에 uuid별로 데이터가 계속 쌓이는 문제가 있습니다. 이에 대한 해결 방안을 고민 중입니다.
이거에 대한 좋은 아이디어가 있을까요?🤔

주기적으로 사용되지 않는 데이터를 수동으로 정리해야 한다면, `localStorage` 말고 쿠키를 활용하는 것은 어떨까요?
쿠키의 `MaxAge` 나 `Expires` 값을 설정하여 자동 파기 효과를 누릴 수 있고, 미팅 url에 접속했을 때 사용자 정보를 유지하고 있는 쿠키의 유효기간을 `N`일 만큼 연장시켜 준다면 오래된 데이터를 삭제할 수 있는 로직도 자연스럽게 구현될 것 같아요.

`Path` 설정을 통해 미팅별 쿠키 격리 역시 실현 가능해 보이네요🙂

2024-08-08 01:29 UTC, Largopie approved these changes
👍👍👍💯💯💯

2024-08-08 01:57 UTC, hwinkr commented on frontend/package.json
> -    "react-cookie": "^7.2.0",
오...있는데 제가 안썼던것이었네용 ㅎ

2024-08-08 01:57 UTC, hwinkr commented on frontend/src/apis/_common/fetchClient.ts
> +const createFetchClient = (baseUrl: string) => {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-08-08 03:55 UTC, hwinkr reviewed
빙봉 리뷰 반영하신다고 고생하셨습니다!!  

navigate + state와 관련해서 추가 코멘트 남겼는데, 한 번 고민해 보시고 반영 부탁드릴게요!!

2024-08-08 03:55 UTC, hwinkr commented on frontend/src/pages/CreateMeetingPage/index.tsx
>  export default function CreateMeetingPage() {
현재 CreateMeetingPage에서  

```tsx
  useEffect(() => {
    if (uuid !== '') {
      navigate('/meeting/complete', {
        state: {
          uuid: uuid,
        },
      });
    }
  }, [uuid, navigate]);

```
useEffect 훅을 활용해서 uuid가 변할 때마다 navigate + state를 활용해서 약속 공유 페이지로 동시키고 있는데, 이 방법은 새로고침했을 때 uuid가 state에서 사라지는 문제가 발생할 수 있을 것 같습니다. 그래서, state로 넘기기 보다는 /meeting/:uuid/complete로 이동시킨 후 useParams 훅을 사용해서 새로고침해도 약속을 생성한 후 서버에서 받는 uuid를 유지할 수 있도록 하면 어떨까요?

2024-08-08 03:55 UTC, hwinkr commented on frontend/src/stores/servers/meeting/mutation.ts
>      },
onSuccess 콜백 함수에서, /meeting/:uuid/complete로 이동시킬 수 있을 것 같아요!!

2024-08-08 07:54 UTC, hwinkr approved these changes
바쁜 와중에도 리뷰 반영해주셔서 감사합니다~~

2024-08-08 07:55 UTC, merged