[BE] 약속 확정 조회 기능 구현
woowacourse-teams/2024-momo pull request #184
Opened 2024-08-08 04:56 UTC by seunghye218

## 관련 이슈

- resolves: #143 

## 작업 내용

확정된 약속을 조회하는 기능을 구현했습니다.

## 특이 사항

## 리뷰 요구사항 (선택)

2024-08-08 07:35 UTC, hw0603 requested changes
컨벤션 관련 리뷰 남겨 두었습니다! 확인해보시고 반영해주세요~

2024-08-08 07:35 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
> +@Table(name = "confirmed_meeting")
👍

2024-08-08 07:35 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
> +    private static final int SECOND_OF_HALF_HOUR = 1800;
사소하지만 `30 * 60` 으로 좀 더 명확하게 정의하는 것은 어떨까요?

2024-08-08 07:35 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmedResponse.java
> +public record MeetingConfirmedResponse(
```suggestion
public record ConfirmedMeetingResponse(
```

2024-08-08 07:35 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmedResponse.java
> +    public static MeetingConfirmedResponse from(Meeting meeting, List<Attendee> attendees,
개행 컨벤션 적용해주세요!

2024-08-08 11:34 UTC, ikjo39 reviewed
마크 고생 많으셨어요~
기분이 좋아지는 사소한 RC 남겨드립니다!

2024-08-08 11:34 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
> +                / SECOND_OF_HALF_HOUR;
`ZoneOffset.UTC`을 설정하신 특별한 이유가 있으신지 궁금합니다!

2024-08-08 11:34 UTC, ikjo39 commented on backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
> +    }
이전 PR에서 본 내용이 여기에도 있네요!?

2024-08-08 11:34 UTC, ikjo39 commented on backend/src/test/java/kr/momo/domain/meeting/ConfirmedMeetingTest.java
> +        assertThat(attendees).containsExactly(attendee1);
`assertAll()`로 묶을 수 있을 거 같아요!

2024-08-08 11:54 UTC, ehBeak requested changes
마크 고생 많으셨어요! 마지막까지 힘내봐요 👍

2024-08-08 11:54 UTC, ehBeak commented on backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
> +                / SECOND_OF_HALF_HOUR;
`(endDateTime.toEpochSecond(ZoneOffset.UTC) - startDateTime.toEpochSecond(ZoneOffset.UTC))`는 `startDateTime`과 `endDateTime`의 차이를 초로 계산한 것 같습니다. 각 시간을 초로 바꿔서 빼는 것 보다, `Duration.between() `함수를 사용하면 훨씬 더 직관적일 것 같아요~ (괜찮으시면 바꿔보시는 걸 추천드려요!)

```java
Duration duration = Duration.between(startDateTime, endDateTime);
// 또는, Duration.between(startDateTime.toInstant(ZoneOffset.UTC), endDateTime.toInstant(ZoneOffset.UTC));
return duration.toSeconds() / HALF_HOUR.getSeconds();
```

단순히 궁금한 점인데, 추가로 `ZoneOffset`을 `UTC`로 설정한 이유가 무엇인가요?

2024-08-08 11:54 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
> +    @Transactional
현재 해당 로직은 조회만 하는 로직인 것 같습니다. 옵션을 readOnly로 바꿔보는 것은 어떨까요?
```suggestion
    @Transactional(readOnly = true)
```

2024-08-08 11:54 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmResponse.java
> +        LocalDate startDate,
`LocalDate`의 기본 형식이 `yyyy-MM-dd` 인 것으로 알고있는데 `@JsonFormat`으로 형식을 적어준 것은 해당 형식을 명시하기 위함일까요?

2024-08-08 11:54 UTC, ehBeak commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +                .statusCode(HttpStatus.OK.value());
현재 이 테스트 코드에서 테스트하고 싶은 것은 `[DELETE] /api/v1/meetings/{uuid}/confirmed`가 잘 작동되는지 확인하고 싶은 것으로 이해했습니다. 
그런데, `[GET] /api/v1/meetings/{uuid}/confirmed` 요청과 `[GET] /api/v1/meetings/{uuid}` 요청을 모두 다 `RestAssured`로 요청하여 값을 가져와서 검증하고 있습니다. 직접 요청을 보내는 것보다 `respository`에서 값을 가져와서 확인하는 것은 어떤가요? 
추가로 `RestAssured`를 통해서 `api`를 호출한 다음 값을 검증한 이유가 궁금합니다!

2024-08-08 11:54 UTC, ehBeak commented on backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
> +        );
꼼꼼하네요.. 👍

2024-08-08 15:31 UTC, ehBeak approved these changes
마크 늦게까지 고생 많으셨어요~!! 🎉

2024-08-09 01:26 UTC, seokmyungham approved these changes
마크 고생하셨습니다 🎉🎉🎉

2024-08-09 01:40 UTC, ikjo39 approved these changes

2024-08-09 01:41 UTC, hw0603 approved these changes
고생했어요 마크!

2024-08-09 01:48 UTC, merged