[BE] 미팅 기본 정보 조회 API 구현
woowacourse-teams/2024-momo pull request #21
Opened 2024-07-16 05:59 UTC by hw0603

## 관련 이슈

- resolves: #16 

## 작업 내용
- 미팅의 후보 일자
- 미팅 이름
- 시작 시간과 끝 시간
- 현재 미팅에 등록된 시간들

을 조회할 수 있는 API를 작성했습니다.

## 특이 사항
이후 게스트 별 되는 시간을 조회해야 하는 기능이 추가될 것이므로  `schedules` 리스트의 구조는 변경될 여지가 있습니다.

검증과 예외처리를 추가해야 하고 테스트 코드 역시 추가가 필요해 보입니다 🥲

우선 오늘까지 해커톤으로 진행되니 현재 구현만큼만 머지하고 설계를 하나씩 수정해 봐요

## 리뷰 요구사항 (선택)

2024-07-16 06:08 UTC, ehBeak requested changes
고생 많으셨습니다 :)

2024-07-16 06:08 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/domain/schedule/dto/ScheduleTimeResponse.java
> +    // TODO: 디미터 법칙 지키기
`TODO` 지우면 좋을 것 같아요~

2024-07-16 06:08 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
> +    }
별 건 아니고 그냥 궁금증인데요..!  `@Getter`를 사용하면 안되나요?

2024-07-17 04:48 UTC, seokmyungham approved these changes

2024-07-17 04:48 UTC, ehBeak approved these changes

2024-07-17 04:48 UTC, seunghye218 approved these changes

2024-07-17 04:49 UTC, ikjo39 approved these changes

2024-07-17 04:49 UTC, merged