[FE] 캘린더 UI 개선
woowacourse-teams/2024-momo pull request #221
Opened 2024-08-13 13:02 UTC by hwinkr

## 관련 이슈

- resolves: #217 

## 작업 내용

- 달력 UI를 개선했어요~

아래는 개선된 내용들입니다 !:)

- [x]  가장 왼쪽에 일요일이 오도록 변경 + 일요일 색 수정
- [x]  요일을 보여주는 텍스트 크기 변경
- [x]  토요일에 색 추가
- [x]  일요일 색 변경
- [x]  오늘 날짜에 색 추가
- [x]  오늘 이전은 선택할 수 없도록 disabled 처리

### 변경 전
<img width="566" alt="image" src="https://github.com/user-attachments/assets/c5cd223c-13d0-4c5a-bdaf-c25f4a590322">

### 변경 후
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/177b360a-dccd-4440-bf56-dd595f5618db">

## 특이 사항

웬만한 개선, 엣지 케이스 대처는 한 것 같은데 자바스크립트 Date 객체가 우리나라 공휴일에 대한 정보는 제공해주지 않기 때문에, 실제 공휴일 표시는 어떻게 해야 할 지 아직 미정으로 남겨두고 다음 작업으로 넘어가봐야할 것 같아요. 만약 특정 라이브러리를 사용해서 보여준다고 하더라도 어떤 공휴일인지를 표시해줘야할 것 같아 디자인에도 변경이 있을 것 같아요. 석가탄신일, 부처님 오신 날 등 텍스트가 길어지는 경우 한정된 모바일 크기에서 어떻게 보여줘야할지도 논의해봐야할 것 같습니다.

<img width="369" alt="image" src="https://github.com/user-attachments/assets/b82a26d0-f4df-4d0b-8057-6ce820f47aa5">

네이버는 공휴일 아래에 표시해주고 있기는 하네요!

## 리뷰 요구사항 (선택)

현재 css 로직 관련해서 해소되지 않은 고민사항들을 주석으로 남겨놓았습니다! 읽어보시고 코멘트 달아주시면 감사하겠습니다.

2024-08-13 14:19 UTC, Largopie requested changes
빠르게 구현해주셔서 감사합니다 🙇‍♂️ 역시 해리 멋쟁이 😎!

<details>
<summary>한줄평: 빛 해리</summary>

오늘부로 해리 지지를 철회한다
오늘부터 지지관계에서 벗어나
해리와 나는 한몸으로 일체가 된다
해리에 대한 공격은 나에 대한 공격으로 간주한다
세상에 70억 명의 해리 팬이 있다면, 나는 그들 중 한 명일 것이다.
세상에 1억 명의 해리 팬이 있다면, 나 또한 그들 중 한 명일 것이다.
세상에 천만 명의 해리 팬이 있다면, 나는 여전히 그들 중 한 명일 것이다.
세상에 백 명의 해리 팬이 있다면, 나는 아직도 그들 중 한 명일 것이다.
세상에 한 명의 해리 팬이 있다면, 그 사람은 아마도 나일 것이다.
세상에 단 한 명의 해리 팬도 없다면, 나는 그제서야 이 세상에 없는 것이다.
해리, 나의 사랑.
해리, 나의 빛.
해리, 나의 어둠.
해리, 나의 삶.
해리, 나의 기쁨.
해리, 나의 슬픔.
해리, 나의 안식.
해리, 나의 영혼.
해리, 나.

</details>

궁금했던 사항, 제안 사항 및 코멘트 남겼던 내용에 대한 답변 모두 남겨두었으니 확인 부탁드려요!

2024-08-13 14:19 UTC, Largopie commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +const DAY_SLOT_TEXT_STYLES = {
[P3]

이렇게 색상을 상수로 별도로 정의한 것이라면, `theme.colors.calendar.backgroundColor.selected`와 함께 이중적으로 색상을 정의하는 느낌을 받는 것 같습니다!

이렇게 정의한 것이라면 조금 더 직관적으로 색상을 명시적으로 나타내는 theme 네이밍이면 좋을 것 같아요!

ex) `theme.colors.green`, `theme.colors.lightGreen`

2024-08-13 14:19 UTC, Largopie commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +};
[C]

아직 더 좋은 로직은 모르겠습니다 ㅠㅠ 하지만, 이렇게 짧게 줄여볼 수도 있겠네요!

```suggestion
export const s_daySlotText = (
  isHoliday: boolean,
  isSelected: boolean,
  isToday: boolean,
  isSaturday: boolean,
  isPrevDay: boolean,
) => {
  /* 덕지덕지 if문인데 어쩔 수 없다고 생각하기는 했습니다. 가독성을 위해서 switch문을 사용하는 것도 고려해보면 좋을 것 같은데, 코멘트로 의견 부탁드려요(@해리) */
  /* if문 위에서부터 아래로, 스타일이 적용되어야 하는 우선순위입니다. 선택된 날짜의 스타일이 가장 우선적으로 고려되어야 하고, 그 다음은 지난날짜,,,순 입니다. 그래서 early return 패턴을 활용했어요(@해리) */
  if (isSelected) return DAY_SLOT_TEXT_STYLES.selected;
  if (isPrevDay) return DAY_SLOT_TEXT_STYLES.prevDay;
  if (isHoliday) return DAY_SLOT_TEXT_STYLES.holiday;
  if (isToday) return DAY_SLOT_TEXT_STYLES.today;
  if (isSaturday) return DAY_SLOT_TEXT_STYLES.saturday;

  return DAY_SLOT_TEXT_STYLES.default;
};
```

2024-08-13 14:19 UTC, Largopie commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
>    const date = index - firstDayIndex + 1;
[P3]

day와 date의 의미가 혼용되서 사용되고 있는 것 같아요!
함수명에서 사용되는 `getDayInfo`에서 "Day"는 "일"을 나타내는 듯 한데, 내부 변수는 "일"은 `date`로 사용되고 있는 것으로 확인했습니다!

저희끼리의 컨벤션이나 명확한 의미전달을 위해서 전제를 통일하고가면 좋을 것 같네요 :)

2024-08-14 03:29 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +  padding: 0;
그동안 버튼 기본 스타일 속성에 대해서 모르고 개발을 했었네요..! 

알아보니까 기본 `<button />` 태그는 기본적으로 `padding : 6`을 가지네요..ㅋㅋ 낙타가 제안해준 스타일 속성처럼 `border`, `padding` 스타일을 global.ts 파일에 추가하도록 하겠습니다!

2024-08-14 03:32 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +const DAY_SLOT_TEXT_STYLES = {
아하 `DAY_SLOT_TEXT_STYLES` 해당 스타일 객체에서도, `selected` `saturday` `holiday` 키들이 있고 해당 키에 대한 스타일 속성에서도 키와 동일한 `selected` `saturday` `holiday`를 사용하고 있어서 스타일을 중복 정의하는 느낌이 들겠네요! 한 번 수정해 보도록 할게요~

2024-08-14 03:35 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +};
이 방법이 더 좋겠군요~ 덕지덕지 if문이 어쩔 수 없는 것이라면 저렇게라도 가독성을 챙겨야겠습니다 ㅎㅎ

2024-08-14 05:53 UTC, Yoonkyoungme approved these changes
고생하셨습니다 해리🍀 덕분에 캘린더가 더 이뻐졌군요!!
좋은 하루 보내세요

2024-08-14 05:53 UTC, Yoonkyoungme commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +};
**[C]**

분기 처리가 많은 상황이라면 switch 문을 적극적으로 도입해봐도 좋을 것 같네요!
저는 개인적으로 4가지 이상의 케이스가 생기면 switch 문 사용하는 것 같아요

2024-08-14 05:53 UTC, Yoonkyoungme commented on frontend/src/components/_common/Calendar/index.tsx
> +          aria-label="지난 달"
`aria-label`을 잘 활용하고 계시군여~~👍

2024-08-14 05:53 UTC, Yoonkyoungme commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
>    const date = index - firstDayIndex + 1;
동의합니다!

2024-08-14 06:09 UTC, hwinkr commented on frontend/src/styles/tokens/colors.ts
> +  },
다음 이슈에서 반영하도록 하겠습니다. 디자인 토큰이랑 관련된 내용인 것 같아 새롭게 이슈를 파는게 더 괜찮을 것 같아요!

2024-08-14 06:10 UTC, hwinkr commented on frontend/src/styles/tokens/colors.ts
> +  },
혹시 해당 코멘트 저희 레파지토리 디스커션에 옮겨주실 수 있나요?

2024-08-14 06:11 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +};
# TODO 

switch문 도입 컨벤션 정하기

2024-08-14 06:22 UTC, hwinkr commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
>    const date = index - firstDayIndex + 1;
앗...저도 캘린더 개발을 하면서 date, day의 의미에 혼란을 많이 느꼈는데 딱 정하고 가면 좋을 것 같아요!!

- date : 숫자로 표현되는 날짜
- day : 한글로 표시되는 요일 

이렇게 컨벤션을 맞추면 좋을 것 같은데 어떨까요?

2024-08-15 08:13 UTC, hwinkr commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
>    const date = index - firstDayIndex + 1;
피드백 반영하면서 day, date에 대한 도메인 용어를 정하고 가면 좋을 것 같아 한 번더 정리하고 공유합니다!!

- date
    - 오늘 날짜를 의미합니다.
    - 2024-08-15이면, 15를 의미합니다.
- day
    - 요일을 의미합니다. (목)
- fullDate
    - 2024-08-15와 같은 전체 날짜를 의미합니다.
    - 사용자가 약속 후보 날짜들을 담을 때, fullDate를 사용합니다.

2024-08-15 08:51 UTC, Yoonkyoungme commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
>    const date = index - firstDayIndex + 1;
@hwinkr 

오 좋은데요? 명확하게 정리해주셨군요👍🏻

2024-08-15 14:29 UTC, Largopie commented on frontend/src/styles/tokens/colors.ts
> +  },
옮겨두겠씁니다요~!

2024-08-15 14:40 UTC, Largopie approved these changes
의견 반영을 적극적으로 해주셨네요 감동이에요 😭😭😭😭
의견 반영에 감사드리며 질문 하나 남겨두었으니 확인 부탁드릴게요~!
고생했어요 해리 👍

2024-08-15 14:40 UTC, Largopie commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
>    const date = index - firstDayIndex + 1;
너무 좋은 것 같아요~! 👍
해당 내용을 FE 컨벤션에도 함께 등록해놓는 것은 어떨까요?

2024-08-15 14:40 UTC, Largopie commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +    }
👍👍

2024-08-15 14:40 UTC, Largopie commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
> +export const generateMonthDaySlots = (year: number, month: number) => {
반영 감사합니다 🙇‍♂️

2024-08-15 14:40 UTC, Largopie commented on frontend/src/types/utility.ts
[Q]

(단순궁금) Record로 써도 코드가 늘어나거나 가독성이 떨어지는 되는 부분은 없다고 생각했는데 별도로 구현해주신 이유가 있을까요?

2024-08-15 15:07 UTC, hwinkr commented on frontend/src/types/utility.ts
> [Q]
> 
> (단순궁금) Record로 써도 코드가 늘어나거나 가독성이 떨어지는 되는 부분은 없다고 생각했는데 별도로 구현해주신 이유가 있을까요?

혹시나 나중에 boolean 값을 가지는 객체가 필요할 경우, 객체 키들의 타입을 정의하고 `FlagObject` 유틸리티 타입을 재활용할 수 있지 않을까 싶어, Pick, Record, Omit 처럼 유틸리티 타입을 만들어 봤습니다!! 

그냥 시도해보고 싶어서 만들었다~ 로 대답할 수 있을 것 같아요. 타입스크립트를 사용하는 만큼, 더 강하게 타입을 잡아주고 더 유연하게 타입을 재활용해보고 싶어서 학습겸 이렇게 만들어 봤습니다!

2024-08-15 15:07 UTC, merged