[BE]
woowacourse-teams/2024-momo pull request #223
Opened 2024-08-13 13:30 UTC by ehBeak

## 관련 이슈

- resolves: #93 

## 작업 내용

요청 값의 형식이 잘못 들어오면 400 Bad Request를 반환하도록 수정했습니다.
* LocalDate 타입의 형식(`yyyy-MM-dd`) 검증
* LocalTime 타입의 형식(`HH:mm`) 검증
* LocalDateTime 타입의 형식(`yyyy-MM-dd HH:mm`) 검증
* 참가자의 닉네임(1자 이상 5자 이하), 비밀번호(1자이상 10자 이하, 알파벳대소문자 숫자,특수문자 포함)를 검증한다.

<br>

기존의 요청 객체는 `LocalDate`, `LocalTime`, `LocalDateTime`을 필드 타입으로 가지고 있었습니다.
문제를 해결하고자 각 타입을 `String`으로 변환하고 각 형식에 맞게 `ConstraintValidator`를 구현한 `커스텀 validator`를 사용했습니다.

`ConstraintValidator`를 구현한 클래스는 `isValid()`에서 검증을 진행하고 검증 과정에서 false를 반환하면 `MethodArgumentNotValidException`를 발생시킵니다. 이 예외는 `GlobalExceptionHandler`에서 잡아서 `400`을 반환하도록 처리했습니다.

## 특이 사항

* 참가자의 비밀번호를 알파벳대소문자와 숫자 뿐만 아니라 특수문자도 포함 시켰습니다. 
큰 이유는 없고, 테스트픽스처 비밀번호에 특수문자가 있길래 그렇게 했습니다.

## 리뷰 요구사항 (선택)

유효하지 않은 요청이 왔을 때, 응답 바디는 아래와 같이 반환됩니다.
```json
{
    "type": "about:blank",
    "title": "Bad Request",
    "status": 400,
    "detail": "유효하지 않은 요청입니다.",
    "instance": "/api/v1/meetings",
    "errorCode": "INVALID_FORMAT_REQUEST",
    "details": [
        "meetingEndTime:유효하지 않은 시간 형식입니다 ex)01:00",
        "availableMeetingDates[0]:유효하지 않은 날짜 형식입니다 ex)2024-03-01"
    ]
}
```
* ProblemDetails가 제공하는 필드에 의도한 대로 값을 넣었는지 검토 부탁드립니다.
* `details`는 요청으로 들어오는 값에서, 형식이 올바르지 않은 모든 필드에 대한 예외 메시지를 `[필드명1:메시지1, 필드명2:메시지2,..]` 형식으로 반환합니다. `details`라는 표현이 조금 어색한 것 같아서 이름이 고민됩니다.

그 외 피드백도 좋습니다.

2024-08-13 16:58 UTC, ikjo39 reviewed
안녕하세요 배키! 고생 많으셨습니다!!
몇 가지 코멘트 남겼으니 확인 부탁드려요 :)

2024-08-13 16:58 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/attendee/dto/AttendeeLoginRequest.java
> +        String password
세세하게 검증들을 추가하셨군요. 고생 많으셨습니다! 👏 

다만 개인적으로는 해당 검증 추가는 컨텍스트가 달라보여 새로 이슈를 팠으면 어땠을까 아쉬움이 남네요!

2024-08-13 16:58 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
> +    @DisplayName("닉네임이 5자 초과거나 비밀번호가 10자 초과하여 로그인 또는 회원가입을 하면 400 상태 코드를 응답한다.")
[`@ParameterizedTest`](https://www.baeldung.com/parameterized-tests-junit-5#:~:text=One%20such%20feature%20is%20parameterized%20tests.%20This%20feature%20enables%20us%20to%20execute%20a%20single%20test%20method%20multiple%20times%20with%20different%20parameters.)는 하나의 테스트 방법을 다른 매개 변수를 사용하여 여러 번 실행하는 방법입니다!

현재는 테스트 대상이 2개로 보이는데요.
1. 닉네임이 5자 초과인 경우
2. 비밀번호가 10자 초과하는 경우

문맥이 다른 두 테스트 대상을 분리하면 어떨까요?

2024-08-13 16:58 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +    @DisplayName("닉네임이 5자 초과거나 비밀번호가 10자 초과하면 400 상태 코드를 응답한다.")
> 문맥이 다른 두 테스트 대상을 분리하면 어떨까요?

여기도 해당해 보입니다!

2024-08-13 16:58 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
> +    private String getToken(Attendee attendee, Meeting meeting) {;
```suggestion
    private String getToken(Attendee attendee, Meeting meeting) {
```

2024-08-13 16:58 UTC, ikjo39 commented on backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
> +    GUEST_PEDRO("pedro", "pedroPw!12", Role.GUEST),
이 Fixture는 왜 변경 되었을까요? 🤔

2024-08-13 16:58 UTC, ikjo39 commented on backend/src/main/java/kr/momo/controller/validator/DateFormatConstraint.java
저는 처음 보는 어노테이션이어서 몇가지 여쭤보고 싶습니다!
1. 어떤 상황에 어떻게 써야하는지
2. `@Target`범위를 왜 이렇게 한정하셨는지
3. `groups`와 `payload` 필드는 무엇을 의미하는지
궁금합니다!

2024-08-13 16:58 UTC, ikjo39 commented on backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
> +
다음과 같이 에러들을 메세지로 변환하는 로직을 메서드 분리를 해보면 가독성이 조금 더 좋아질 것 같습니다!

```suggestion
    @ExceptionHandler
    public ProblemDetail handleMethodArgumentNotValidException(MethodArgumentNotValidException ex) {
        log.warn(ex.getMessage(), ex);

        List<String> errors = getErrorsToMessage(ex);
        ProblemDetail problemDetail = ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST, errors.toString());
        return new CustomProblemDetail(problemDetail, INVALID_REQUEST_FORMAT_MESSAGE);
    }

    private List<String> getErrorsToMessage(MethodArgumentNotValidException ex) {
        return ex.getBindingResult()
                .getFieldErrors()
                .stream()
                .map(error -> "%s:%s".formatted(error.getField(), error.getDefaultMessage()))
                .toList();
    }
```

2024-08-13 17:09 UTC, ikjo39 reviewed
추가로 찾은 리뷰 더 나갑니다 ㅎ

2024-08-13 17:09 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
> +                .then()
응답 쪽도 로그 부탁드립니다 😁
```suggestion
                .then().log().all()
```

2024-08-13 17:09 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
> +                .then()
```suggestion
                .then().log().all()
```

2024-08-14 01:30 UTC, ehBeak commented on backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
> +    GUEST_PEDRO("pedro", "pedroPw!12", Role.GUEST),
`pedroPw!123`가 11자로, 10자를 넘기 때문입니다. 비밀번호는 10자 이내가 되어야 합니다. 
GUEST_PEDRO가 request 객체를 생성할 때 사용되어서 request의 검증 오류가 발생합니다. 때문에 수정했습니다~

(추가로 아직 request 객체를 만드는데 사용하지 않지만 10자를 넘는 비밀번호도 수정하겠습니다~)

2024-08-14 01:45 UTC, ehBeak commented on backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
> +                .then()
앗.. 이걸 빼먹었네요! 반영하겠습니다~

2024-08-14 02:14 UTC, hw0603 approved these changes
고생하셨어요 배키! 다온의 리뷰 반영 후에는 크게 변경해야될 점들이 보이지 않아 Approve 드려요~

궁금한 점들 코멘트 남겨 두었으니 확인 부탁드려요!

2024-08-14 02:14 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +                LocalTime.parse(request.meetingEndTime()));
```suggestion
        Meeting meeting = saveMeeting(
                request.meetingName(),
                LocalTime.parse(request.meetingStartTime()),
                LocalTime.parse(request.meetingEndTime())
        );
```

2024-08-14 02:14 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/validator/DateFormatConstraint.java
> +    String message() default "유효하지 않은 날짜 형식입니다 ex)2024-03-01";
시간갑소가 달리 날짜는 계속 증가하기만 하므로, 특정 날짜를 명시하기보다는 그냥 `YYYY-MM-DD` 로 알려 주면 어떨까요?

2024-08-14 02:14 UTC, hw0603 commented on backend/src/main/java/kr/momo/controller/validator/DateTimeFormatConstraint.java
> +    String message() default "유효하지 않은 날짜시간 형식입니다 ex)2024-08-13 17:33";
여기도요!

2024-08-14 02:14 UTC, hw0603 commented on backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
> +    public ProblemDetail handleMethodArgumentNotValidException(MethodArgumentNotValidException ex) {
`ConstraintValidator`를 찾아 보니 크게 두 가지 예외를 던지더라구요

- `ConstraintViolationException`: 메서드 파라미터, 메서드 반환값에 문제가 있을 경우
- `MethodArgumentNotValidException`: `@RequestBody` 내부에서 검증에 실패한 경우, `@Validated` 나 `@Valid` 내부에서 처리되지 못한 경우

전자에 대한 핸들러는 추가하지 않아도 될까요?

2024-08-14 02:24 UTC, seokmyungham requested changes
배키 고생하셨습니다. 🔥🌞
피곤하지만 RC를 받았으니 기분이 좋아지셨을거에요!! 🎊🎊
화이팅해봐요!

2024-08-14 02:24 UTC, seokmyungham commented on backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
> +    }
예외 타입을 추상화해서 `CustomProblemDetail`의 책임으로 넘길 수 있으면 로직을 재사용할 수 있을 것 같아요.

2024-08-14 02:24 UTC, seokmyungham commented on backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
> +        return new CustomProblemDetail(problemDetail, INVALID_REQUEST_FORMAT_ERROR_CODE);
setter로 주입하는 것 보다 `CustomProblemDetail`에 생성자를 추가하거나 정적 팩토리 메서드를 만들어보는 건 어때요??

2024-08-14 02:32 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/validator/DateFormatConstraint.java
> 어떤 상황에 어떻게 써야하는지

요청 파라미터에서 날짜 형식을 검증하실 때 해당 어노테이션을 붙여 사용하시면 됩니다.(null인지 아닌지 검증하기 위해 @NotNull을 붙이는 것 처럼요.) 

<details>
  <summary>동작 방식에 대한 추가 설명이 필요하시면 확인해 주세요!</summary>

  현재 요청의 필드를 검증하는 과정에서  `Bean Validation (JSR 380)`을 사용하고 있습니다.    
`Bean Validation`은 `@NotNull`처럼 어노테이션을 이용해서 검증하도록 도와주는 프레임워크입니다. 
날짜 형식 또한 `Bean Validation`프레임워크를 사용해서 어노테이션으로 날짜 형식을 검증하고 싶었습니다. 그래서  `@DateFormatConstraint`를 만들었습니다.

`@DateFormatConstraint`의 정의를 보면, `@Constraint(validatedBy = DateFormatValidator.class)`라는 어노테이션이 있습니다. 
이는 `Bean Validation`을 사용할 것이고 `DateFormatValidator`클래스의 `isValid()`함수에 작성한 대로 값을 검증하겠다는 의미입니다. 

`DateFormatValidator`클래스를 들어가 보면, `isValid()`함수에서 검증 로직을 확인해 보실 수 있습니다.
`isValid`의 내용을 확인해 보시면 `isValid`의 파라미터로 들어온 `string` 값의 형식이 `DateTimeFormatter.ISO_LOCAL_DATE`가 아닐 때 false를 반환합니다. 이때 예외를 터뜨립니다.
</details>

---

> `@Target`범위를 왜 이렇게 한정하셨는지

현재 Target은 `필드`와 `타입`입니다. 

* `필드`는 예상하시는 대로 `request` 객체의 필드에 적용하기 위해 사용했습니다. `DateTimesCreateRequest`에서 `date` 필드에 해당 어노테이션을 붙여서 검증하는 것을 확인하실 수 있습니다.
* `타입`은 말 그대로 타입에 붙여서 검증하는 것입니다. 이것이 필요한 이유는 `request` 객체의 필드 타입이 `List<String>` 타입인 경우 `List<@TimeFormatConstraint String> times`처럼 `String`타입에 붙여서 리스트 요소 각각의 형식을 확인해야 하기 때문입니다. (`DateTimesCreateRequest` 클래스를 보시면 확인하실 수 있습니다.)

---

> groups와 payload 필드는 무엇을 의미하는지

groups와 payload 필드는 Spring 표준에 맞추기 위해 작성한 boilerplate 코드라고 보시면 될 것 같습니다.
[spring-mvc-custom-validator(baeldung)](https://www.baeldung.com/spring-mvc-custom-validator)를 보시면 아래와 같은 설명이 있습니다.

> With the `@Constraint` annotation, we defined the class that is going to validate our field. The message() is the error message that is showed in the user interface. Finally, the additional code is mostly boilerplate code to conform to the Spring standards.

<details>
  <summary>만약 쓴다면 어떻게 쓰일지 추가 설명</summary>

`group` :  아래와 같이, 서로 다른 검증 조건을 그룹별로 적용할 수 있습니다. 
```java
@DateFormatConstraint(groups = BasicChecks.class)
private String date;

@DateFormatConstraint(groups = AdvancedChecks.class)
private String date;
```

`payload`: 검증에 추가적인 메타데이터를 첨부할 때 사용됩니다. 

```java
@DateFormatConstraint(payload = CustomPayload.class) // CustomPayload : 메타정보를 담는 클래스
private String date;
```

</details>

2024-08-14 04:19 UTC, seunghye218 requested changes
검증 인터페이스를 구현하고 적용하느라 고생많으셨어요 배키~ 예상치 못한 DTO 스키마 수정이 있기에 행운이 깃드는 RC 드립니다😄 확인 부탁드려요!
+ 추가적으로 `AttendeePassword.validatePasswordLength` 메서드도 바뀐 정책을 적용해야합니다.

2024-08-14 04:19 UTC, seunghye218 commented on backend/src/main/java/kr/momo/exception/code/RequestFormatErrorCode.java
> +public enum RequestFormatErrorCode implements ErrorCodeType {
새로운 ErrorCode Enum을 만드셨는데 사용하는 곳이 없어보여요. 어떤 용도로 만든걸까요?

2024-08-14 04:19 UTC, seunghye218 commented on backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmRequest.java
> +        String endDateTime
확정 요청할 때 추천 일정 응답 DTO 스키마와 같게 가져가 일관되고 실수의 여지를 줄이려고 Date와 Time을 분리했었어요. 다시 이를 합치게되면 프론트엔드에서도 수정이 필요해보입니다. 
DateTime으로 합친 이유가 있을까요?

2024-08-15 23:20 UTC, ehBeak commented on backend/src/main/java/kr/momo/controller/validator/DateFormatConstraint.java
> +    String message() default "유효하지 않은 날짜 형식입니다 ex)2024-03-01";
아 그렇네요.. 나중에 시간이 지나면 좀 어색할 것 같아요! YYYY-MM-DD 이게 명시적이고 좋네요.
저도 좋다고 생각하는데, 프론트엔드 쪽에 보내는 메시지인 만큼, 프론트는 어떻게 생각할지 물어보겠습니다~

2024-08-15 23:30 UTC, ehBeak commented on backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
> +    public ProblemDetail handleMethodArgumentNotValidException(MethodArgumentNotValidException ex) {
현재 `bean validation`은 `@RequestBody` 내부에서만 사용하기 때문에 `ConstraintViolationException`이 발생할 일이 없다고 판단하여 따로 처리하지 않았습니다. 추후에 `@RequestBody`외에 어노테이션을 사용하여 검증할 일이 있을 때 핸들러를 추가하면 좋을 것 같네요👍

2024-08-15 23:47 UTC, ehBeak commented on backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
> +    }
`CustomProblemDetail`에 `details`필드를 따로 넣으면 MomoException 과 같이 다른 예외에서도 details 필드가 보일 줄 알았네요. 그러면 details에 null이 뜰거라 예상했습니다. 근데 직접 해보니까 아니네요😅

좋은 방법인 것 같습니다~

2024-08-15 23:59 UTC, ehBeak commented on backend/src/main/java/kr/momo/exception/code/RequestFormatErrorCode.java
> +public enum RequestFormatErrorCode implements ErrorCodeType {
어이쿠.. 제가 삭제를 안했네요. 감사합니다!

2024-08-16 00:03 UTC, ehBeak commented on backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmRequest.java
> +        String endDateTime
confilct를 해결하는 과정에서 제가 잘못 merge한 것 같아요😢 

> 추가적으로 AttendeePassword.validatePasswordLength, AttendeeName.validateNameLength메서드도 바뀐 정책을 적용해야합니다.

이 부분도 그런 것 같아요.. rebase하는 과정에서 수정되지 않을까 싶네요..! rebase해서 다시 올려보겠습니다~

2024-08-16 02:24 UTC, ehBeak commented
댓글 주신 내용 반영해서 다시 올립니다. 확인 부탁드려요!

2024-08-16 04:32 UTC, seokmyungham approved these changes
배키 고생하셨습니다 🎈

2024-08-16 05:13 UTC, hw0603 approved these changes
고생하셨습니다🙂

2024-08-16 05:55 UTC, ikjo39 approved these changes
리뷰 잘 반영해주셨네요!
간단한 코드 스타일 관련만 수정해주시면 좋을 것 같습니다~

2024-08-16 05:55 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/meeting/dto/MeetingCreateRequest.java
> +         return LocalTime.parse(meetingStartTime);
```suggestion
        return LocalTime.parse(meetingStartTime);
```

2024-08-16 05:55 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/schedule/dto/DateTimesCreateRequest.java
> +    }
```suggestion
        return times.stream()
                .map(LocalTime::parse)
                .toList();
    }
```

2024-08-16 09:40 UTC, seunghye218 approved these changes
리뷰 반영이 잘 이루어졌네요👍깃 문제가 해결되어 다행이에요. 고생하셨습니다~~

2024-08-16 09:40 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/attendee/AttendeeName.java
> +        if (name.length() > 5) {
👍

2024-08-16 09:46 UTC, merged