[BE] AvailableDates가 내부적으로 정렬된 상태를 유지하도록 개선
woowacourse-teams/2024-momo pull request #233
Opened 2024-08-14 13:53 UTC by hw0603

## 관련 이슈

- resolves: #230 

## 작업 내용

`AvailableDate` 의 일급 컬렉션인 `AvailableDates` 가 내부 필드로 `List` 가 아닌 `SortedSet`을 가지고 있도록 변경했습니다.

그에 따라 리스트에서 `O(N)` 으로 동작하던 몇 연산들을 `O(1)`로 수행할 수 있도록 최적화했습니다.

## 특이 사항

자료구조 특성상 더 이상 중복된 값이 존재할 수 없으므로 중복 검증 로직과 테스트를 삭제했습니다.

## 리뷰 요구사항 (선택)

`AvailableDates`는 도메인이죠. 현재 흐름대로 사용한다면 (테스트코드를 제외하고는) 모두 같은 `Meeting`에 대한 `AvailableDate`들을 래핑하고 있어요.

이때, 생성자로 전달되는 각 `AvailableDate` 들이 같은 `Meeting`을 가지는지를 검증해야 할까요?
로직상에서 강제로 `Meeting`이 다른 `AvailableDate`를 리스트에 담고, 그 리스트를 기반으로 `AvailableDates`를 생성하지 않는 이상 서로 다른 Meeting을 가질 일이 전혀 없긴 해요.

개인적으로는 같은 `AvailableDates`라는 객체를 `Meeting`에 대한 `AvailableDate`의 컬렉션으로 정의했기 때문에, 강제 생성 케이스를 제외하고는 만들어질 일이 없다고 하더라도 검증을 추가하는게 좀 더 견고한 도메인이 될 수 있는 방향이라고 생각합니다.

하지만 검증 로직을 작성 중, 다음과 같은 의문이 남아 우선 검증을 추가하지 않은 상태입니다.
1. 현재 `List.of(new AvailableDates(new Meeting(..)..))` 과 같이 임시로 객체를 생성하여 일급컬렉션을 만드는 테스트코드의 일괄 수정 필요
2. 거의 모든 경우에 실패할 일이 없음에도 검증을 해야 하므로, 그것에서 오는 연산 오버헤드
3. 검증을 위해 `Meeting`의 비교가 필요한데, 엔티티 동등성 비교 기준의 모호함
    - PK를 기준으로? / PK가 null일 때는?
    - PK를 제외한 필드값들을 기준으로? / 동등성 비교만을 위해 필드를 다 꺼내 와야 하나?
    - 비즈니스 키를 정의하여 해당하는 필드 쌍을 기준으로?
        - 특정 문맥에서만 사용되는 동등성 비교 메서드 정의 (ex, `hasSameId()`)

검증은 다음과 같은 방식을 생각하고 있어요.
만약 검증을 한다고 하면, 이곳에서 검증에 실패한 경우 어떤 예외를 던져야 할까요?
이러한 유형의 검증은 사용자의 잘못된 입력을 검증하기보다는 도메인에서 개발자의 실수를 미연에 방지하기 위해 던지는 예외의 성격이 강한데요, 때문에 `MomoException`을 던지기에는 부적절하다고 생각했어요.
```java
    public AvailableDates(List<AvailableDate> availableDates) {
        Meeting allowedMeeting = availableDates.get(0).getMeeting();
        this.availableDates = availableDates.stream()
                .map(ad -> validateAllSameMeeting(ad, allowedMeeting))
                .collect(Collectors.toCollection(() -> new TreeSet<>(Comparator.comparing(AvailableDate::getDate))));
    }

    private AvailableDate validateAllSameMeeting(AvailableDate availableDate, Meeting allowedMeeting) {
        long allowedMeetingId = allowedMeeting.getId();
        long thisId = availableDate.getMeeting().getId();
        if (allowedMeetingId != thisId) {
            throw new MomoException(???);  //  어떤 예외를 던질 것인가?
        }
        return availableDate;
    }
```

2024-08-14 18:15 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
>                  .count();
```suggestion
        Meeting meeting = availableDates.first().getMeeting();
        AvailableDate from = new AvailableDate(startDateInclusive, meeting);
        AvailableDate to = new AvailableDate(endDateInclusive, meeting);
        long availableDateRangeCount = availableDates.subSet(from, to).size() + 1L;
```

`SortedSet`의 특성을 이용해서 이렇게 구현할 수도 있는데, 변경하지 않는 것이 더 깔끔한 것 같아서 수정하지 않았습니다. 🥲

2024-08-15 17:11 UTC, seunghye218 reviewed
정렬을 수행하는 부분에 개선이 필요하다고 생각했었는데 수정되어 좋네요👍
검증에 대해서 2번과 같은 생각이에요. 고생하셨고 몇 개의 가벼운 코멘트 확인 부탁드려요~~

2024-08-15 17:18 UTC, seokmyungham requested changes
페드로 고생하셨습니다 🔥

리뷰 요구사항에 관해서 제 생각에는 불필요한 검증 같습니다.
페드로가 의문을 제기해주신 이유에도 일부분 동의하고

AvailableDates가 존재하지 않았을 때 List<AvailableDate>가 같은 Meeting에 속하는지 검증하지 않았듯이, 다른 개발자가 실수할 1% 예외 상황까지 방어하기 위해서 이러한 검증 로직을 추가하기엔 너무 큰 오버헤드 같다는 생각입니다.

현재 `AvailableDates(List<LocalDate> dates, Meeting meeting)`을 통해서만 직접적으로 AvailableDate를 생성하고 있고
`AvailableDates(List<AvailableDate> availableDates)`은 거의 데이터베이스 조회 시 사용되고 있기 때문에 코드를 봤을 때 헷갈릴 여지가 없을 것 같습니다.

2024-08-16 03:38 UTC, ikjo39 requested changes
고생 많으셨어요 페드로~
다른 분들의 리뷰들이 잘 담겨있어 간단한 부분만 RC 남겨드려요~

2024-08-16 04:14 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/timeslot/Timeslot.java
> +        Duration duration = ChronoUnit.DAYS.getDuration().dividedBy(slotLength);
`static block`에서 계산하도록 변경하였습니다!

2024-08-16 04:23 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +                availableDateRepository.findAllByMeeting(meeting)
좋은데요~~

2024-08-16 04:32 UTC, ehBeak approved these changes
리뷰를 다들 잘 달아주셔서 검증 방식에 대한 제 생각만 코멘트드립니다! 고생하셨어요 페드로👍

> 개인적으로는 같은 AvailableDates라는 객체를 Meeting에 대한 AvailableDate의 컬렉션으로 정의했기 때문에, 강제 생성 케이스를 제외하고는 만들어질 일이 없다고 하더라도 검증을 추가하는게 좀 더 견고한 도메인이 될 수 있는 방향이라고 생각합니다.

이 부분에 대해서 동의합니다. 만약, 테스트 코드를 작성할 때 코드를 작성하는 과정에서 `meeting`이 다른 `availableDate`가 만들어질 수도 있을 것 같아요.
하지만 그것까지 고려해서 검증로직을 작성하기에는 오버헤드가 크다고 생각합니다.


> 만약 검증을 한다고 하면, 이곳에서 검증에 실패한 경우 어떤 예외를 던져야 할까요?
이러한 유형의 검증은 사용자의 잘못된 입력을 검증하기보다는 도메인에서 개발자의 실수를 미연에 방지하기 위해 던지는 예외의 성격이 강한데요, 때문에 MomoException을 던지기에는 부적절하다고 생각했어요.


만약 해당 검증을 도입한다면, `IllegalStateException`을 던져야할 것 같아요. 
`IllegalStateException` 설명을 보면 메서드가 부적절한 시점에 호출되었음을 나타낼 때 사용됩니다. (무엇이 잘못 되었는지 메시지 정도 적어주면 더 좋겠네요..!)
그래서 `MomoException`보다는 자바에서 제공하는 `IllegalStateException`이 좋을 것 같습니다.

2024-08-16 04:46 UTC, hw0603 commented on backend/src/main/java/kr/momo/service/meeting/MeetingService.java
> +        return availableDateRepository.saveAll(availableDates.getAvailableDates());
과거 검증은 영속화 과정과 컨텍스트가 다른 것 같아서 다른 메서드로 분리했습니다.
해당 메서드에서 `LocalDate.now()`를 호출하도록 변경했구요, 중복 호출 문제는 불필요한 메서드 분리가 원인이였다고 생각하여 해당 메서드를 제거하고 `create()` 안에서 `.saveAll()`을 수행하도록 변경했어요!

2024-08-16 04:54 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return !availableDates.contains(new AvailableDate(other, meeting));
반영했습니다!

2024-08-16 05:09 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +                .collect(Collectors.toCollection(() -> new TreeSet<>(Comparator.comparing(AvailableDate::getDate))));
`static import` 는 컨벤션상 테스트 코드에서만 사용하도록 이야기했던 것 같아요!

2024-08-16 05:11 UTC, seokmyungham approved these changes

2024-08-16 05:27 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return !availableDates.contains(new AvailableDate(other, meeting));
<img width="665" alt="image" src="https://github.com/user-attachments/assets/db91b040-4bb7-4afc-83db-a863c710311e">

위와 같이 `TreeSet.contains()`의 javadoc 에는 단순히 `equals()`로 처리한다고만 되어 있어서 헷갈릴 수 있을 것 같아요.

위 구현에서 알 수 있듯, `TreeSet`은 내부적으로 `TreeMap`을 사용하는데, `contains()` 연산 시 `TreeMap.containsKey()`를 호출하게 됩니다.

`TreeMap.containsKey()`는 다시 `TreeMap.getEntry()`를 호출하구요, `getEntry()`를 보면 아래와 같습니다. (아래 생략)

2024-08-16 05:36 UTC, ikjo39 approved these changes
고생하셨어요~

2024-08-16 05:36 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return !availableDates.contains(new AvailableDate(other, meeting));
친절한 설명까지 감사합니다 👍

2024-08-16 05:45 UTC, seunghye218 approved these changes
이전에 남긴 리뷰에 대해 잘 이해되고 적용되었네요. 😄

2024-08-16 05:45 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
> +        return !availableDates.contains(new AvailableDate(other, meeting));
> 집합이 집합 인터페이스를 올바르게 구현하려면 집합이 유지하는 순서(명시적 비교자의 제공 여부와 관계없이)가 같음과 일치해야 한다는 점에 유의하세요. (See Comparable or Comparator for a precise definition of consistent with equals.) 이는 Set 인터페이스가 같음 연산으로 정의되어 있기 때문인데, TreeSet 인스턴스는 compareTo(또는 compare) 메서드를 사용해 모든 요소 비교를 수행하므로 이 메서드에 의해 같다고 간주되는 두 요소는 집합의 관점에서 볼 때 동일합니다. 집합의 순서가 같지 않더라도 집합의 동작은 잘 정의되어 있으며, 단지 집합 인터페이스의 일반적인 계약을 따르지 않을 뿐입니다.

https://docs.oracle.com/javase/8/docs/api/java/util/TreeSet.html

2024-08-16 05:45 UTC, seunghye218 commented on backend/src/main/java/kr/momo/domain/timeslot/Timeslot.java
> +    }
👍

2024-08-16 05:52 UTC, merged