[FE] 입력 필드 유효성 검사 및 비밀번호 보기/숨기기 기능을 추가
woowacourse-teams/2024-momo pull request #234
Opened 2024-08-14 16:17 UTC by Yoonkyoungme

## 관련 이슈
- resolves: #219 

## 작업 내용
### 1. 입력 필드 유효성 검사 추가 
약속명, 닉네임, 비밀번호 입력 필드에 대해 유효성 검사를 추가하였습니다. 

### 2. 유효성 검사 오류 메시지 표시
사용자가 비밀번호 입력 시 유효성 검사 오류가 발생하면 입력을 막고, 입력 필드 밑에 오류 메시지를 표시합니다.
<img width="523" alt="image" src="https://github.com/user-attachments/assets/c4ccfecc-731e-47a0-b294-d314c231931b">

### 3. 비밀번호 보기/숨기기 기능
비밀번호 입력 필드에 비밀번호 보기/숨기기 기능을 추가하였습니다. 사용자가 버튼을 클릭하면 비밀번호를 보이거나 숨길 수 있습니다.

## 특이 사항

## 참고 자료
[작업 현황 정리 노션 링크](https://paper-mass-5ff.notion.site/6c34d0a87bb24a45a872885fcca46ce7?pvs=4)

## 리뷰 요구사항 (선택)

2024-08-15 01:51 UTC, Yoonkyoungme commented
.

2024-08-15 14:28 UTC, Largopie requested changes
고생하셨습니다 빙봉 :) 꼼꼼하게 잘 만들어 주셨네요! 👏👏👏👏
몇 가지 제안 사항 리뷰로 남겨드렸으니 확인 부탁드립니다~~

ps. 입력 부분에 focus시 outline은 border-radius가 들어간 것 같은데 border에는 없는 것 같네요!
이 부분도 함께 radius를 주거나 없애도 좋을 것 같습니다!

개인적으로 저는 둥근게 이쁘네요~!

https://github.com/user-attachments/assets/a8b786b2-d82e-42ec-a94a-9a0870e2d765

2024-08-15 14:28 UTC, Largopie commented on frontend/src/hooks/useInput/useInput.ts
> +    if (!rules) return null;
[Q]

undefined가 아닌 null로 표기하신 이유가 있을까요?!

2024-08-15 14:28 UTC, Largopie commented on frontend/src/components/_common/Field/index.tsx
> +      {error && <div css={s_errorText}>{error}</div>}
[P2]

에러가 발생하면 요소가 밀리게 되는데요..! 사용자 경험을 위해서는 아래의 요소가 움직이지 않게 설정하면 좋을 것 같아요 :)

https://github.com/user-attachments/assets/cf4758ec-89ba-40bc-ab88-e5f85d797f1f

2024-08-15 14:28 UTC, Largopie commented on frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
> +    pattern: /^[a-zA-Z0-9!@#$%]+$/,
정규표현식 좋네요 😃

2024-08-15 14:28 UTC, Largopie commented on frontend/src/pages/CreateMeetingPage/index.tsx
> +    pattern: /^[a-zA-Z0-9!@#$%]+$/,
[P3]

해당 패턴이 중복적으로 사용된 것으로 보입니다 :) 해당 정규표현식을 명시적으로 상수로 분리해봐도 좋을 것 같아요!

예시) PASSWORD_PATTERN(뭔가 대소문자,특수문자가 직관적이지 않긴 함)

2024-08-15 14:28 UTC, Largopie commented on frontend/src/pages/CreateMeetingPage/index.tsx
> +          description="비밀번호를 1~10자 사이로 입력해 주세요. 사용 가능한 문자는 알파벳, 숫자, 특수문자(!@#$%)입니다."
[P3]

넘치면 두줄로... 만들어.... 주세요... 🫠

2024-08-15 14:59 UTC, hwinkr requested changes
빙봉뱅봉!! 🔮 유효성 검증을 맡아서 구현하시느라 고생하셨습니다!!  

간단한 코멘트 및 변경 사항 요청을 드렸습니다. (~~사실 간단하지 않을수도 있씁니다...~~)  
현재 placeholder가 사용되지 않고 있는 것 같은데 재치있는 빙봉의 멋진 placeholder를 기대해 봅니다! 아자아자 화이팅!!!

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/router.tsx
> +import CreateMeetingPage from '@pages/CreateMeetingPage/CreateMeetingPage';
[C]

저희 페이지 컴포넌트를 만드는 경우에도, 일반 컴포넌트를 만드는 것과 마찬가지로 `index.tsx`를 사용하기로 했던 것 같은데 이렇게 변경한 이유가 있을까요??

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/components/PasswordInput/PasswordInput.styles.ts
> +  background-color: ${theme.colors.white};
상수 사용 좋습니다!! 👍👍

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/components/PasswordInput/index.tsx
> +  const handleShowPasswordToggle = () => {
[P3] 

개인적으로 `handlePasswordToggle`만 되어도 충분하다고 생각합니다! 저희 핸들러 함수 네이밍 컨벤션인 handle + 명사 + 동사에도 적합해 보이구요 ㅎㅎ

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
> +          />
[P2] 

Field 컴포넌트를 호출할 때, 전달해주는 문자열 props에 대해서 상수화가 필요해 보이는 것 같아요~

```js
export const CREATE_MEETING_FORM_ATTRIBUTES: CardFormAttribute = {
  meetingName : {
    query : "",
    labelText : '',
    placeholder : '',
  }
```

제가 위에서 작성하 예시처럼, 특정 입력 필드에 대해 필요한 문자열들을 상수화를 하면 더 보기 편할 것 같아요!

그리고, 입력 규칙에 대해서도 상수화가 적용되면 좋을 것 같습니다!

```js
export const INPUT_RULES = {
  minMonth: 1,
  maxMonth: 12,
  maxCardNumberPartLength: 4,
  maxExpirationDateLength: 2,
  minCardOwnerNameLength: 1,
  maxCardOwnerNameLength: 15,
  validExpirationLength: 2,
  validCVCNumberLength: 3,
  validCardPasswordNumberLength: 2,
};
```

위 예시는 레벨 2 리액트-페이먼츠 미션에서 제가 사용한 입력 규칙에 대한 상수들인데, 상수화를 적용하고 나니 훨씬 보기 좋았던 것 같아요 ㅎㅎ

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/components/_common/Field/index.tsx
> +      {error && <div css={s_errorText}>{error}</div>}
[P2] 

Field 컴포넌트를 호출하고 있는 쪽에서 예외 메시지도 props으로 넘겨주고 있는 것으로 보입니다. Field 컴포넌트를 더 유연하게 활용하기 위해서 합성 컴포넌트 패턴을 적용해보는 것은 어떨까요? UI에 대한 책임이 많아질 때마다 Filed 컴포넌트로 전달해줘야 하는 props도 비례해서 많아질 것 같은데 합성 컴포넌트로 어떤 컴포넌트가 어떤 UI를 그릴지 더 빠르게 파악할 수 있도록 하면 어떨까요?

그리고, 낙타가 발견해 준 문제는 

```tsx
return (
    <FormField>
      <FormField.InputTitle text={query} />
      <FormField.InfoText textType="caption" text={caption} />
      <FormField.Label htmlFor="card-number" labelText={labelText} />
      <FormField.InputContent>
        <Input
          inputSize="large"
          isError={cardNumbers.length > 1 && !validationResult.isValid}
          value={cardNumbers.join("-")}
          onChange={(event) =>
            handleCardNumberChange(event.target.value.replaceAll("-", ""))
          }
        />
      </FormField.InputContent>
      <FormField.InfoText
        textType="error"
        text={validationResult.isValid ? "" : validationResult.errorText}
      />
    </FormField>
  );
```

위 코드 예시처럼, 공간은 차지하되 예외가 발생한 경우에만 텍스트를 그리도록 하면 해결될 것 같습니다!

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/hooks/useInput/useInput.ts
> +    if (!rules) return null;
[P2] 

현재 `validateInputValue` 함수의 책임을 봤을 때, 입력값에 예외가 있는 경우 상황에 따른 예외 메시지를 반환해주고 있는 것으로 보입니다. 입력값이 유효하다면 예외 메시지가 없을테니 null을 반환하기 보다는 빈 문자열을 반환해서 예외 메시지가 없다는 것을 상태로 표시하면 어떨까요? 아니면 저희 레벨 2 리액트-모듈 미션에서 경험한 것 처럼,

```ts
const useCardNumberValidation = () => {
  const [validationResult, setValidationResult] = useState<ValidResult>({
    isValid: false,
    errorText: "",
  });
```

유효성 검증에 대한 상태를 객체로 만들고, 유효한지 그렇지 않은지를 표현하는 `isValid`, 예외 메시지 상태를 관리하는 `errorText`를 활용해보는 것은 어떨까요?

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/components/PasswordInput/PasswordInput.styles.ts
> +  }
[Q]

오...이 스타일 속성은 처음 보는군요~ 그냥 focus와의 차이가 있을까요?

2024-08-15 14:59 UTC, hwinkr commented on frontend/src/components/_common/Input/index.tsx
>  }
좋은 제안인 것 같아요!

2024-08-15 15:04 UTC, hwinkr commented
[P1]

<img width="524" alt="image" src="https://github.com/user-attachments/assets/2d4c1a15-2027-43a5-b046-074fd99d4f7a">

그리고 현재 입력길이를 초과해서 입력한 경우에도 입력 길이를 초과했다는 예외 메시지를 보여주고 있는데요. 이 상황에서는 사용자에게 예외 메시지를 보여주는 것 보다 입력을 계속해서 막는 즉, setState를 호출하지 않는 쪽이 사용자 경험 측면에서 더 괜찮을 것 같다는 생각이 듭니다. 만약 입력 길이를 초과했다는 메시지를 전달해 주려면, setState를 계속해서 호출해서 업데이트 해줘야할 것 같아요. 

<img width="349" alt="image" src="https://github.com/user-attachments/assets/08501b1e-1b9a-437a-80f8-2cdda459decc">

저는 레벨 2 리액트-페이먼츠 미션에서 사용자 이름을 입력받을 때, 15글자를 입력 길이 제한으로 뒀고, 입력 길이를 초과할 경우 메시지를 전달해주기 위해서 setState를 계속해서 호출할 수 있도록 구현했었습니다.

제 코멘트를 요약하자면 
- 입력 길이를 초과한 경우 setState를 호출해서 입력값을 업데이트 하지 않으려면, 초과에 대한 예외 메시지는 전달하지 않는 것이 좋다.
- 만약, 초과에 대한 예외 메시지를 전달하고 싶다면 setState를 계속해서 호출하고 입력값을 업데이트해야 한다.

이렇게 두 가지 선택지 중 하나를 선택하면 될 것 같아요! 빙봉 화이팅!!

2024-08-15 15:10 UTC, Yoonkyoungme commented on frontend/src/router.tsx
> +import CreateMeetingPage from '@pages/CreateMeetingPage/CreateMeetingPage';
충격 ...
다른 페이지가 `pages/A페이지/A페이지` 형식으로 되어있길래 "와~~ 뭐야 AttendeeLoginPage만 index.tsx로 되어있네! 당장 바꿔야지"하면서 바꿨습니다....
근데, 다 제가 만든 페이지었군요😅
<img width="309" alt="image" src="https://github.com/user-attachments/assets/6f87fd69-9b65-44a0-b31e-ff6ae70715d4">


컨벤션 지키지 못했네요 ㅜㅜㅜㅜ 헷갈렸습니다🙏바꿔 둘게요!

2024-08-18 06:21 UTC, ehBeak approved these changes
확실히 화면이 더 깔끔해 보이네요~ 구현하시느라 고생 많으셨어요🥰

2024-08-18 08:55 UTC, Yoonkyoungme commented
안녕하세요 후론트 모모 @Largopie @hwinkr 

티켓 UI 작업을 먼저 하느라 리팩터링이 늦었습니다😅

오늘 저녁부터 리팩터링 시작할 예정입니다!
늦어도 내일 오후까지는 재PR 날리겠습니다!

2024-08-18 19:19 UTC, Yoonkyoungme reviewed
@Largopie @hwinkr 
낙타, 해리 좋은 코멘트 감사합니다!☺️
반영한 코멘트에는 🚀 이모지를 달아두었어요~

2024-08-19 01:36 UTC, Largopie approved these changes
빙봉 꼼꼼하게 구현해주느라 너무 고생 많았습니다 :) 👍
코드가 많이 깔끔해진 것 같네요!

사소한 의견 하나만 더하자면, 현재 입력이 완료된 상태가 아님에도 생성하기 버튼이 활성화 되어있는데 이 부분을 어떻게 핸들링해서 disable 시킬지 고민해봐도 좋을 것 같아요!

사용자 입장에서는 버튼이 비활성화 되면 아직 입력이 모두 된 것이 아닌 것으로 판단할 수 있으니 입력 부분에 대한 실수를 줄일 수 있지 않을까 싶습니다!

고생하셨습니다 :)
(근데 너무 늦은 시간까지 했어요 ㅠㅠ 컨디션 관리 잘 하시길 바랍니다... 🫠)

2024-08-19 13:58 UTC, hwinkr commented on frontend/src/hooks/useInput/useInput.ts
> +    if (!rules) return null;
> 해리가 예시로 든 코드에서 객체로 isValid와 errorText를 관리한 이유가 있을까요? (isValid와 errorText 중 한 가지만 관리해도 되지 않을까요?)

우선, 입력값에 대한 파생 상태를 두 가지로 구분해서 생각했던 것 같아요!
- 입력 값이 유효한지
- 예외 메시지
즉, 유효 & 예외 피드백 두 가지 컨텍스트를 구분하려고 했었습니다. 
`사용자의 입력값이 유요하지 않으면(isValid), 에러 메시지를 보여준다`의 흐름이 더 적절하다고 생각했던 것 같아요.

```tsx
<FormField.InfoText textType="error" text={validationResult.isValid ? "" : validationResult.errorText} />;
```
그래서 코드의 흐름도 프로퍼티 네이밍을 활용해서, 더 잘 파악할 수 있을 것이라 생각해 제안했던 의견이었습니다! 

그런데, 빙봉의 의견처럼 유효하지 않으면 예외 메시지가 있을 것이고, 사용자의 입력값이 유효하다면 예외 메시지가 있을 것이니 굳이 구분하지 않고 하나의 상태로 관리해도 될 것 같네요!! 

의견 정리해주셔서 감사합니다 ㅎㅎ

2024-08-19 14:00 UTC, hwinkr commented on frontend/src/hooks/useInput/useInput.ts
> +    if (!rules) return null;
> 이러한 점을 고려하여, 잘못된 값을 입력하더라도 입력 자체는 막지 않고, 오류에 대한 피드백을 즉각적으로 제공하기로 결정하였습니다.

오 빙봉만의 고민을 통해서, 결론을 도출해낸 것이 정말 보기 좋은 것 같아요! 제가 RC를 드렸을 때 줬던 선택지 중 하나를 선택하셨군요!! 입력값 자체는 막지 않으면서 유요하지 않은 입력을 했다는 것에 대해서 피드백을 전달해주면 사용자도 빠르게 입력값을 수정할 수 있을 것 같네요. 좋습니다!!

2024-08-19 14:02 UTC, hwinkr commented on frontend/src/components/PasswordInput/index.tsx
> +  const handleShowPasswordToggle = () => {
오오오~ 저희 핸들러 함수 컨벤션도 지키면서 가독성도 챙긴 정말 좋은 변경인 것 같아요!!

2024-08-19 14:03 UTC, hwinkr commented on frontend/src/components/PasswordInput/PasswordInput.styles.ts
> +  }
오...자식 태그가 부모 태그의 스타일도 변경할 수 있었군요~ 정리해 주셔서 감사합니다~ 덕분에 새로운 지식 얻었네요!!
럭키비키~ 🍀

2024-08-19 14:17 UTC, hwinkr approved these changes
빙비리리리빙봉뱅봉!!!

고봉밥 🍚🍚🍚🍚🍚 리뷰를 드렸는데도 굳세게 반영해 주셔서 감사합니다!!!

편하게 다음 작업하실 수 있도록 행운의 approve 드립니다!! 🍀🍀🍀

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/components/_common/Field/Field.styles.ts
> +`;
[C] 

(제가 까먹을까봐 남겨두는 코멘트)

현재는 PRIMITIVE_COLORS로 디자인 토큰의 색상을 활용하고 있는데, SEMENTIC_COLOR를 사용하는 것으로 수정해야겠네요!! 
light, dark와 같은 시멘틱 컬러 네이밍도 같이 정해보면 좋을 것 같아용

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/hooks/useInput/useInput.ts
> +    setErrorMessage(validationError);
빙봉의 고민 끝에 useInput 내부의 유효성 검증 로직이 결정되었군요~ 빙봉뱅봉 굿~

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/components/_common/Field/Field.styles.ts
> +  min-height: 2rem;
😊😊😊 굿굿굿

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/components/_common/Field/index.tsx
> +Field.ErrorMessage = FieldErrorMessage;
[C]

`Object.assign`을 사용해서 구현할 수도 있겠네요! (이건 취향차이인 것 같아요 :)

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/components/_common/Field/Field.styles.ts
> +  white-space: pre-line; /* 줄 바꿈을 인식 */
오~ 굿굿굿!!

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/components/_common/Input/index.tsx
> +export default function Input({ variant = 'default', type = 'text', ...props }: InputProps) {
> InputHTMLAttributes에 placeholder가 포함되어 있어 선택적으로 입력 가능하도록 수정

상속받은 타입을 잘 활용하고 있군요~ 덕분에 Input 컴포넌트가 받는 props가 줄어들어 깔끔해진 것 같아욤

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/components/PasswordInput/index.tsx
> +        aria-label={isPasswordShow ? '비밀번호 숨기기' : '비밀번호 보이기'}
오 ㅋㅋㅋㅋㅋㅋㅋㅋ 접근성 챙기는 빙봉~ 굿이당

2024-08-19 14:17 UTC, hwinkr commented on frontend/src/pages/CreateMeetingPage/CreateMeetingPage.tsx
> +  };
빙봉이 제시해준 의견이었던, `에러 메시지가 없으면(null 이면) 유효한 입력이라고 봐도 무방하다`를 코드로 확인할 수 있는 부분이네요. 해당 함수가 반환하는 불리언 값을 활용해서 버튼 disabled 속성에 활용해도 될 것 같아요~

2024-08-20 02:06 UTC, Yoonkyoungme commented
@hwinkr @Largopie 

버튼이 disabled 처리되는 조건을 다음과 같이 설정했습니다.

- 필수 입력 필드 중 하나라도 비어 있는 경우
- 입력 값이 필드 형식에 맞지 않는 경우

위 조건 중 하나라도 충족되면 버튼이 비활성화되게 하였습니다!


- 약속 생성

  https://github.com/user-attachments/assets/054b450b-7e3c-4b0f-af21-846ece8d0526

- 로그인

  https://github.com/user-attachments/assets/e19b7610-2799-4a7d-9b36-1055a7f73b71

2024-08-20 02:25 UTC, hw0603 requested changes
서브모듈이 포함되어서 백엔드 팀원들 모두 리뷰어로 지정됐네요ㅋㅋㅋㅋㅠ
확인 한 번 부탁드려요!

2024-08-20 02:25 UTC, hw0603 commented on backend/src/main/resources/security
커밋에서 서브모듈 제외해주세요!
이 상태로 머지되면 서브모듈이 과거 상태로 돌아갈 것 같아요🥲

2024-08-20 02:29 UTC, Yoonkyoungme commented on backend/src/main/resources/security
헉쓰

2024-08-20 02:41 UTC, hw0603 approved these changes

2024-08-20 02:42 UTC, merged