[FE] 재사용할 수 있는 Text 컴포넌트 구현
woowacourse-teams/2024-momo pull request #254
Opened 2024-08-18 06:51 UTC by hwinkr

## 관련 이슈

- resolves: #253 
- 재사용할 수 있는 Text 컴포넌트를 구현했습니다. 

## 작업 내용

<img width="226" alt="image" src="https://github.com/user-attachments/assets/9fb1bafb-5411-4964-b3e1-45d118c63a6e">
<img width="490" alt="image" src="https://github.com/user-attachments/assets/64089132-bdc4-4401-8b40-eb3462ca27c6">
<img width="464" alt="image" src="https://github.com/user-attachments/assets/5006d249-3587-445d-9830-02539c04c483">
<img width="498" alt="image" src="https://github.com/user-attachments/assets/add999a7-9506-4bf3-97b8-4b196aa018f3">

위 이미지에서 확인할 수 있듯, 4가지 상황에 대한 UI를 하나의 컴포넌트를 사용해서 그릴 수 있도록 재사용할 수 있는 Text 컴포넌트를 구현했습니다. 지난 스프린트에서 정의한 디자인 토큰의 TYPOGRAPHY를 활용해서 구현했어요.

## 구현 과정

아래는 Text 컴포넌트를 구현할 때, 정의했던 컴포넌트 인터페이스에 대한 설명입니다. 

### 1) input

- variant
    - default : 가장 기본이 되는 텍스트이며, 검은색을 사용한다.
    - caption :  사용자에게 추가적인 정보를 알려주기 위해 사용되는 텍스트이며, 회색을 사용한다. 약속을 생성하기 위해 정보를 입력할 때, 추가 정보를 주기 위해서 사용하거나 / 조회 페이지에서 추가 정보를 주기 위해서 사용할 수 있다.
    - warning : 사용자에게 예외 피드백, 경고를 주기 위해서 사용되는 텍스트이며, 빨간색을 사용한다. 약속을 생성하기 위해 정보를 입력할 때, 잘못된 입력을 할 경우 예외 피드백을 주기 위해서 사용할 수 있다.
    - accent : ‘**페드로**님 반가워요' 에서 ‘페드로’라는 단어를 강조할 때 사용되는 텍스트이며, 모모 서비스의 주 색상인 핑크색을 사용한다.
- typo
    - 디자인 토큰을 생성할 때, 만들었던 TYPOGRAPHY를 사용하며 titleBold, titileMedium,,,등 다양한 typo의 텍스트를 만들 수 있다.
- chidren(React.ReactNode)
    - 텍스트 컴포넌트를 사용해서, 사용자에게 전달할 메시지

### 2) output

Text 컴포넌트 인터페이스의 output은 여러 상황에서 유연하게 그려지는 텍스트 UI라고 할 수 있다!

## 특이 사항

**[🚨필독]** 현재 빙봉의 PR #234 에서 스토리북에서 svg를 사용하기 위한 설정이 추가되어 있는 것으로 알고 있는데, 저도 이번 작업에서 `information.svg`를 추가했습니다. 아직 빙봉의 PR이 머지되어 있지 않기 때문에 제 브랜치로 이동해서 스토리북을 실행하면 에러가 발생할 것입니다. 만약 로컬 스토리북에서 Text 컴포넌트에 대한 스토리를 확인하고 싶다면, [여기](https://github.com/woowacourse-teams/2024-momo/pull/234/files#diff-5256a4be7372c9e4864d843a69df5161a192a25bc7758c2578c5d7ca1e7aaed2) 를 참고해서 `main.ts`의 설정을 변경해 주세요. 

## 리뷰 요구사항 (선택)

2024-08-18 10:24 UTC, ehBeak commented
인터페이스에 대해서 자세하게 설명해 주셔서 어떤 내용을 말하는지 알 것 같기도 하네요ㅎㅎ
고생 많으셨어요 해리 💯💯

2024-08-19 11:38 UTC, Largopie requested changes
재사용 할 수 있는 Text 컴포넌트라니! 너무 멋진데요? 이제 이 Text 컴포넌트로 모든 텍스트를 대체하면 되는걸까요?!

하지만 저의 리뷰를 피해갈 순 없습니다. 리뷰 남겼으니 확인 부탁드려요~! 🍀

2024-08-19 11:38 UTC, Largopie commented on frontend/src/components/_common/Text/Text.styles.ts
[P2]

한 줄의 텍스트를 작성하기 위해서 두 번의 `<Text>` 컴포넌트를 호출해야하는 부분이 조금 어색하게 느껴지네요!
빙봉에게 제안했던 것처럼 합성 컴포넌트로 만들어보는 것은 어떨까요?

2024-08-19 12:35 UTC, Yoonkyoungme approved these changes
재사용 할 수 있는 Text 컴포넌트라니! 너무 멋진데요?!

2024-08-19 12:35 UTC, Yoonkyoungme commented on frontend/src/assets/images/information.svg
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
[P3]

svg width와 height 크기를 원하는 값으로 유연하게 조절할 수 있게 `width="current"` `heigth="current"` 설정을 하는건 어떨까요?

2024-08-19 14:25 UTC, hwinkr commented on frontend/src/components/_common/Text/Text.styles.ts
```tsx
export const TitleText: Story = {
  render: (args) => (
    <div style={{ display: 'flex', alignItems: 'center' }}>
      <Text {...args} variant="accent" typo="titleMedium">
        모모 런칭데이 회식
      </Text>
      <Text {...args} typo="titleMedium">
        약속 참여자들이 선택한 시간대를 알려드릴게요
      </Text>
    </div>
  ),
};
```
해당 스토리북의 코드를 보고 제시하는 의견일까요?? 저도 두 번 호출하는 것이 어색하다고 생각은 했었습니다!! 

다만, 노션 백로그에서 확인할 수 있는 것 처럼 Text 컴포넌트는 글자 렌더링과 관련된 책임만 가지고 있는 것이 좋을 것 같아 `<p />`태그 하나를 활용했었는데요. 해당 태그는 `<span />`과 다르게 블럭 요소라서 뷰포트의 한 줄을 다 차지하게 됩니다. 합성 컴포넌트 패턴을 Text 컴포넌트에 적용하려면 <p /> 태그들을 감싸는 부모 태그 예를들어, <div /> 태그가 있어야 할 것 같아보입니다. 혹시 여러개의 <p /> 태그를 감싸는 태그를 추가로 사용하는 방향으로 합성 컴포넌트 패턴을 사용해보자는 의견을 제안해주신게 맞을까요?? 그러면 컴포넌트 이름도 함께 변경해야할 것 같아요. 합성 컴포넌트 패턴을 사용하면 사실 상, Text 보다는 TextWrapper 성격이 강한 컴포넌트가 아닌가 하는 생각이 듭니다!!

2024-08-19 14:26 UTC, hwinkr commented on frontend/src/assets/images/information.svg
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
오... 처음 알았습니다 감사용

2024-08-19 14:29 UTC, hwinkr commented on frontend/src/assets/images/information.svg
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
[Q]

그러면 해당 svg 파일을 사용하는 쪽에서 크기를 props로 전달할 수 있게 되는건가요?

2024-08-19 14:38 UTC, hwinkr commented on frontend/src/assets/images/information.svg
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
빙봉 의견...반영하겠습니다!!!

2024-08-19 14:58 UTC, Largopie commented on frontend/src/components/_common/Text/Text.styles.ts
> 태그를 감싸는 태그를 추가로 사용하는 방향으로 합성 컴포넌트 패턴을 사용해보자는 의견을 제안해주신게 맞을까요??

정확히 이해하셨네요 👍 해리가 제시하는 부분에 대해서 일리가 있다고 생각합니다!

제가 예상한 합성 컴포넌트의 예시로는  `<strong>` 태그처럼 글자를 강조하는 용도로도 내부 태그를 적용해서 사용할 수 있는 방법처럼 구현할 수 있지 않을까 싶은 마음에 제안드린 내용이였습니다!

`<strong>`태그와 같은 용도라면, 합성 컴포넌트 방식도 도입할만한 가치가 있지 않을까? 하는 생각이 드는데 어떻게 생각하시나용?!

```tsx
<Text typo="titleMedium">
  <Text.Accent>모모 런칭데이 회식</Text.Accent>
  약속 참여자들이 선택한 시간대를 알려드릴게요
</Text>
```

https://developer.mozilla.org/ko/docs/Web/HTML/Element/strong

2024-08-19 15:07 UTC, hwinkr commented on frontend/src/components/_common/Text/Text.styles.ts
오...`<strong />`을 사용하면 강조 폰트라는 것을 명시적으로 표현해줄 수도 있겠군요! 좋은데요?? 낙타가 제안해준 방법으로 하면 한 번의 Text 컴포넌트 호출로 강조폰트 + 기본폰트를 한 번에 사용할 수 있는 장점도 있겠지만 한 가지 걱정되는 것은 강조폰트나, 기본폰트 하나만 필요한 경우에도 모두 
```html
<div>
  <p>뭐시기 저시기...</p>
</div>
```
위 구조처럼 `<div />` 태그로 감싸진 구조로 그려져야할 것 같습니다! 하나의 `<p />` 태그만 사용하면 되는데 굳이 필요하지 않은 `<div />` 태그를 사용한다고 해야할까요? 그래서, 가독성을 조금 버리더리도 두 개의 Text 컴포넌트를 사용하는 쪽에서 `<div />` 태그를 사용하는 것으로 구현했던 것 같아요!! 흠... 또 `trade off` 이군요. 저와 낙타의 의견이 반대인 것 같은데 빙봉의 의견도 들어보고 유연하게 결정해 보시죠!! @Yoonkyoungme

2024-08-19 15:35 UTC, Yoonkyoungme commented on frontend/src/components/_common/Text/Text.styles.ts
wowowowowow 저를 호출해 주셨군요!
열띤 토론을 하고 있네요 🐫 vs 🍀

2024-08-19 16:32 UTC, Largopie commented on frontend/src/components/_common/Text/Text.styles.ts
`<div>` 태그를 사용해야하는 이유를 아직 정확하게 파악하지 못한 것 같습니다 😅

가장 최상위에 사용되는 Text 컴포넌트를 `<p>`태그로 구현한 뒤, 내부에 강조해야 할 색상들을 정의할 때는 `<span>`태그를 사용해서 구현하는 방식으로 하면 `<div>`태그를 사용하지 않아도 괜찮지 않을까요...?

```tsx

export function Text() {
  return <p css={사용할css}>{children}</p>
}

export function Accent() {
  return <span css={강조되는css}>{children}</span>
}

<Text>
  <Text.Accent>안녕하세요</Text.Accent>
  모모에용~
<Text>
```

2024-08-19 17:48 UTC, Yoonkyoungme reviewed
엥 답변 코멘트가 안 올라갔었네요

2024-08-20 06:12 UTC, hwinkr commented on frontend/src/components/_common/Text/Text.styles.ts
<img width="724" alt="image" src="https://github.com/user-attachments/assets/60467f9b-003d-44a8-8cb3-88462b0ab47d">

아 그렇게 하면 되겠군요 `<p />` 태그 내부에 다른 태그가 없어야 한다고 생각했던 것 같아요. GPT에게 물어보니 다른 블럭 요소가 아니면 충분히 `<p />` 태그 내부에 다른 태그를 활용할 수 있다고 하네요! 하나 배워갑니다!!! 🤩🤩🤩🤩🤩

2024-08-20 07:06 UTC, Largopie approved these changes
최: 최고다
현: 현세대 프론트엔드는
웅: 웅이가 최고야

2024-08-20 07:06 UTC, Largopie commented on frontend/src/components/_common/Text/Accent/index.tsx
👍👍👍💯💯💯

2024-08-20 07:13 UTC, merged

2024-08-20 07:15 UTC, Yoonkyoungme approved these changes
질문 하나 남겨두었어요 ~~ 반영 감사합니다!

2024-08-20 07:15 UTC, Yoonkyoungme commented on frontend/src/components/_common/Text/Text.stories.tsx
> +      <InformationIcon width="12" height="12" />
리뷰 반영 감사합니다👍👍

2024-08-20 07:15 UTC, Yoonkyoungme commented on frontend/src/components/_common/Text/Accent/index.tsx
> +}
[Q]
해당 컴포넌트는 텍스트를 강조하기 위한 목적일까요?
그렇다면 chidren 대신 string으로 제한하는 것이 어떨까요?

만약 Accent 컴포넌트에서 `<strong>` 태그 안에 텍스트뿐만 아니라 다른 인라인 요소들도 사용활 수 있게 하는 목적이라면 children 사용도 괜찮을 것 같네용

2024-08-20 07:18 UTC, hwinkr commented on frontend/src/components/_common/Text/Accent/index.tsx
> +}
오...일리네어가 있는 말씀이군요
Accent는 텍스트만 강조하기 위한 목적을 가진 컴포넌트입니다~ 그래서 `<strong />` 태그를 사용했던 것이구요. 빙봉의 말을 들어보니 `children` 으로 모든 타입의 props를 내려줄 수 있도록 열어두면 강조 스타일이 적용되지도 않는 `<img />`도 충분히 props로 내려주는 상황이 생기겠네요. 이미 merge를 눌려버려서 다음 이슈에 반영해보도록 할게요!