Refactor/255 time table UI
woowacourse-teams/2024-momo pull request #265
Opened 2024-08-20 04:11 UTC by hwinkr

## 관련 이슈

- resolves: #255 

- 약속 조회 페이지에서 사용되는 테이블 UI를 개선된 피그마 디자인 시안에 맞게 개선했습니다.

## 작업 내용

### 개선 사항 목록

1. 테이블 셀의 크기를 줄인다

테이블 UI에 대한 다른 디자인들을 참고하면서 테이블 셀의 크기를 어느 정도 줄여도 된다는 이야기를 나눴었습니다. 이를 반영하기 위해서 기존에는
```css
width : 4.8rem
height : 2.4rem
```
위 스타일 처럼 테이블 셀을 `고정 너비`로 뒀습니다. 하지만 서비스를 이용할 때 사용되는 디바이스의 크기가 다양했고, 너비가 넓은 디바이스는 상대적으로 테이블 셀의 너비가 너무 좁아보이는 문제가 생겼습니다. 그래서 `flex : 1` 스타일 속성을 사용해서, 동적으로 테이블 셀의 너비가 결정되도록 변경했습니다. 이렇게 하면, 만약 약속 날짜의 범위가 1일인 경우에는 테이블 셀의 너비가 너무 넓어지는 문제가 추가로 생겼습니다. 이를 해결하기 위해서, 테이블 셀에 `max-width` 속성을 추가해서 해결했습니다

2. 30분 단위로 시간을 표시한다.

초기 서비스 기획 단계에서 나눴던 이야기인 `30분 단위로 약속 조회 테이블을 구성한다`를 이번 PR에서 반영했습니다. 거의 한 달 반 만에 반영을 했네요... 다른 일들이 너무 많아서 너무 늦게 반영한 것 같아 아쉽습니다...😭

3.  오전, 오후 텍스트 구분을 없앤다

다른 팀원들의 피드백, UT, 디자인 피드백을 통해서 오전과 오후를 구분한 텍스트를 없애도 되겠다는 이야기를 나눴었습니다. 이를 이번 PR에서 반영했습니다. 

4. 툴팁 UI를 개선한다.

개선된 피그마 디자인 시안에서 확인할 수 있듯 툴팁 UI가 개선되었는데, 이를 이번 PR에서 반영했습니다. 

5. 비율 색상 프로그레시브바를 구현한다.

특정 시간에 참여자의 수가 아닌, 비율로 색상을 표시하기로 정책이 변경되었습니다. 이 방법으로 가면, 비율이 같으나 참석자 수가 다른 경우 툴팁에서 보여지는 참여자의 수가 달라지므로 사용자에게 혼란을 줄 수 있다는 우려가 있었습니다. 이를 해결하기 위해서 0%-100% 사이의 색상을 10% 단위로 나눈 색상 프로그레시브바를 사용자에게 보여주자는 이야기가 나와, 이를 이번 PR에 반영했습니다. 

## 특이 사항

### 날짜 페이지네이션 기준 5일로 수정

`useDatePage`, `usePagedTimePick` 커스텀 훅에서 3일 단위로 날짜를 페이지네이션 했는데, 도메인 정책이 변경 사항을 이번 PR에 반영했습니다. 

### 시간의 범위도 드래그가 되는 문제 해결 

<img width="317" alt="image" src="https://github.com/user-attachments/assets/d30d7abe-81fc-4cf4-a14c-e1c90cfce493">

기존 테이블 UI를 데스크탑에서 활용할 경우 시간의 범위도 함께 드래그가 되는 문제가 있었습니다. 이는 시간의 범위도 `<table />` 태그를 구성하는 요소에 포함되었기 때문이었습니다. 그래서 시간의 범위는 `<div />` 내부에서 구성하도록 마크업 구조를 변경했습니다.

### 버튼 스타일 개선은 다음 이슈에서

한 이슈에서 너무 많은 코드를 변경하면, 리뷰하는데도 어렵고 피드백 주기도 길어질 것 같아 버튼 스타일 개선은 다음 이슈에서 진행하도록 하겠습니다.

## 리뷰 요구사항 (선택)

### 리뷰 중점 사항

`file changed`가 많기는 하지만, 대부분 폴더 구조 변경 + 변경된 피그마 디자인 시안 반영이므로 리뷰하는데 그렇게 어렵지 않을 것 같아요. :) 스타일 관련해서 더 개선했으면 좋겠는 내용은 언제든 말씀 주세요~

2024-08-20 08:08 UTC, Largopie requested changes
해리~! UI 개선하느라 고생 많으셨습니다 :)

열심히 도움이 될 부분은 없는지 리뷰를 남겨보았어요! 🙌
확인하시구 답변 부탁드리겠습니다~!

2024-08-20 08:08 UTC, Largopie commented on frontend/src/components/Schedules/Schedules.util.ts
> +};
[P3]

요렇게 줄여볼 수도 있을 것 같네요! 명시적으로 나타내기 위해 변수를 사용한것이겠죠..?

```suggestion
  return Array.from({ length: end - start }, (_, index) => start + index);
};
```

2024-08-20 08:08 UTC, Largopie commented on frontend/src/components/Schedules/SchedulePicker/SchedulePickerContainer.tsx
> +  });
[P3]

요것도 개인적으로는 stores/server 폴더에 레이어를 분리하면 좋을 것 같아요!

2024-08-20 08:08 UTC, Largopie commented on frontend/src/components/Schedules/Schedules.styles.ts
>  `;
[P2]

 ```suggestion
export const s_scheduleTableContainer = css`
  display: flex;
  width: 90%;
  min-height: fit-content;

  span::selection {
    user-select: none;
  }
`;
```

드래그를 오른쪽에서 왼쪽으로 올릴 때 대비해서 user-select를 없애는 방법도 좋을 것 같네요 :)

2024-08-20 08:08 UTC, Largopie commented on frontend/src/components/Schedules/Schedules.styles.ts
> +  background-color: ${ratio > 0 ? getColorByRatio(ratio) : '#f4f4f5'};
[P2]

'#f4f4f5'색상을 정의해둔 토큰으로 사용하면 좋을 것 같아요! 해당 리뷰 외에도 몇 가지 있는 것 같네요!

2024-08-20 13:44 UTC, hwinkr commented on frontend/src/components/_common/Header/Header.styles.ts
> +// note : Header z-index 관련 문제 해결
앗...해당 주석은 사소하지만 알리면 좋은 변경사항이라고 생각해 일부러 지우지 않은 주석이었습니다! 
문장 끝에 (@해리)를 붙이는 것을 깜빡했네요 ㅎ

2024-08-20 13:45 UTC, hwinkr commented on frontend/src/hooks/usePagedTimePick/usePagedTimePick.ts
> +const DATES_PER_PAGE = 5;
예리하시군요! 해당 실수는 여러분이 제 코드를 꼼꼼하게 읽나 확인하기 위해서 심어놓은 이스터 에그였습니다~
장난이구요 저도 개발하면서 낙타와 같은 생각을 했었는데 작업량이 많다보니 깜빡한 것 같네요! 반영하겠습니다 😎😎😎

2024-08-20 13:46 UTC, hwinkr commented on frontend/src/components/Schedules/Schedules.styles.ts
> +  background-color: ${ratio > 0 ? getColorByRatio(ratio) : '#f4f4f5'};
앗...저도 해당 부분에 대해서 불편함을 느끼긴 했지만 grey 디자인 토큰을 `SEMENTIC_COLORS`로 옮기는 작업이 테이블 UI를 개선하는 작업과 컨텍스트가 다른 작업이라고 판단해서 새로운 이슈에서 변경하는 것이 좋다고 판단했었습니다!! 아마 해당 작업이 끝나고 나면 다음 이슈에서 반영할 것 같아요! red, blue도 함께요!

2024-08-20 13:52 UTC, hwinkr commented on frontend/src/components/Schedules/Schedules.styles.ts
>  `;
앗...이 부분에 대한 드래그는 놓쳤는데 섬세한 피드백 감사합니다! 반영하도록 하겠습니다 :)

2024-08-20 13:52 UTC, hwinkr commented on frontend/src/components/Schedules/SchedulePicker/SchedulePickerContainer.tsx
> +  });
좋습니다! 데이터 페칭과 관련된 책임은 `stores/server` 내부에 두기로 했으니, 옮기도록 하겠습니다!

2024-08-20 13:53 UTC, hwinkr commented on frontend/src/components/Schedules/Schedules.util.ts
> +};
네넵 가독성을 위해서 만든 변수입니다! 

짧고 간단한 코드보다는 읽는 사람이 편한 즉, 가독성이 좋은 코드가 빛을 낼 때도 있으니까요!! ✨✨✨

2024-08-20 16:19 UTC, hwinkr commented
@Largopie 

낙타님, 코드 리뷰 변경을 완료하였사옵니다.

2024-08-21 03:44 UTC, Yoonkyoungme commented
해리 고생하셨습니다👏👏👏

디렉터리 구조를 수정하거나 파일명 수정에는 chore라는 커밋 type 대신 rename 쓰는 것을 권장드려봅니다 :)
<img width="684" alt="스크린샷 2024-08-21 오후 12 43 00" src="https://github.com/user-attachments/assets/5a1ea9d8-56f8-4823-b58c-cce4e31eb68a">

2024-08-21 03:45 UTC, Yoonkyoungme requested changes
해리 고생하셨습니다👏👏👏 해리의 빛나는 노력 덕분에 테이블 UI가 정말 이쁘게 개선되었네요!!! 짱🍀

디렉터리 구조를 수정하거나 파일명 수정에는 chore라는 커밋 type 대신 rename 쓰는 것을 권장드려봅니다 :)
<img width="684" alt="스크린샷 2024-08-21 오후 12 43 00" src="https://github.com/user-attachments/assets/5a1ea9d8-56f8-4823-b58c-cce4e31eb68a">

2024-08-21 03:45 UTC, Yoonkyoungme commented on frontend/src/components/AttendeeTooltip/index.tsx
> +              <p key={index} css={s_attendeeText}>
[P2]
key 값을 index 대신 name으로 변경 제안 드립니다!

2024-08-21 03:45 UTC, Yoonkyoungme commented on frontend/src/hooks/useTimePick/useTimePick.utils.ts
> +  return { rowIndex, colIndex }; // 시간의 범위를 나타낸 tr, td를 제거했기 때문에 -1을 할 필요가 없어짐 (@해리)
주석으로 변경 사항 남겨두는 거 좋네요👍

2024-08-21 03:45 UTC, Yoonkyoungme commented on frontend/src/components/Schedules/Schedules.util.ts
>  };
[P1]

`formatTime` 함수를import 하는 파일들이 충돌날 것 같네요.
`formatTime`은 제가 [251 PR](https://github.com/woowacourse-teams/2024-momo/pull/251/commits/97260d6f3205c76fb0cb646a0a8e6f7f69696223)에서 현재 파일에서 삭제하고,  `utils/date` 파일에 유틸함수로 분리해 두었어요. 참고 부탁드립니다! 작업 중간 중간에 rebase full 하시는 거 추천드려요!

2024-08-21 03:55 UTC, Yoonkyoungme commented on frontend/src/components/_common/Header/Header.styles.ts
>    top: 0;
[Q]

z-index를 `3`으로 설정한 이유가 있나요? 3의 의미에 대해 궁금합니다!

2024-08-21 08:53 UTC, Largopie approved these changes
빠른 반영 고마워요 해리~~ 👍👍👍💯💯💯

2024-08-21 13:34 UTC, hwinkr commented
> 해리 고생하셨습니다👏👏👏 해리의 빛나는 노력 덕분에 테이블 UI가 정말 이쁘게 개선되었네요!!! 짱🍀
> 
> 디렉터리 구조를 수정하거나 파일명 수정하는 경우에는 chore라는 커밋 type 대신 rename 쓰는 것을 권장드려봅니다 :) <img alt="스크린샷 2024-08-21 오후 12 43 00" width="684" src="https://private-user-images.githubusercontent.com/100656920/359739189-5a1ea9d8-56f8-4823-b58c-cce4e31eb68a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDc1MDMsIm5iZiI6MTcyNDI0NzIwMywicGF0aCI6Ii8xMDA2NTY5MjAvMzU5NzM5MTg5LTVhMWVhOWQ4LTU2ZjgtNDgyMy1iNThjLWNjZTRlMzFlYjY4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMzMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTgwMDU5OTM4OTNmOWZmM2Y5NjYyNzNkZWJmZjFlZThkNTI1ZjIwNTE1MDIzOTBkMmRiOWQ3MjhkZTU3OWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eHuJ0xP-MebH8VMI3vDHmu7R3TmbD1TIoOIYiKh47RQ">

`rename` 컨벤션을 사용하는 것에 익숙하지 않아 계속 익숙한 `chore`를 사용했었네요...😂 컨벤션 잘 지켜볼게요 감사해용~

2024-08-21 13:35 UTC, hwinkr commented on frontend/src/components/Schedules/Schedules.util.ts
>  };
충돌 방지 교통 정리 감사합니다 빙봉뱅봉.

2024-08-21 13:50 UTC, hwinkr commented on frontend/src/components/AttendeeTooltip/index.tsx
> +              <p key={index} css={s_attendeeText}>
저도 동의합니다! index로 key를 사용하는 것은 공식문서에서도 지양하라고 하니까 얼른 수정하도록 할게요

2024-08-21 14:13 UTC, hwinkr commented on frontend/src/components/_common/Header/Header.styles.ts
>    top: 0;
오...좋은 질문 감사합니다 빙봉! 

빙봉의 질문에 답변을 하기 위해서 왜 헤더 컴포넌트가 테이블 컴포넌트 아래에 배치돼서 사라지는지에 대해서 알아봤어요. 

> _쌓임 맥락(Stacking Context): z-index는 요소의 쌓임 맥락을 결정합니다. 기본적으로, HTML 요소는 쌓임 순서(위에 배치되는 순서)가 정해져 있으며, position 속성(예: relative, absolute, sticky, fixed)이 설정된 요소가 쌓임 맥락을 형성할 수 있습니다. 하지만 이때 z-index가 명시적으로 지정되지 않으면, 기본값인 auto로 설정되며, 문서의 소스 코드 순서에 따라 쌓입니다._

Header 컴포넌트 스타일에는 기존에 z-index가 명시적으로 설정되어 있지 않았기 때문에, 문서의 소스 코드 순서에 따라 쌓임 맥락이 결정되어서 아래로 배치되었던 것이었어요. 3은 이전 프로젝트 할 때 헤더 컴포넌트의 z-index를 3으로 설정했어서 솔직히 말씀드리면 객관적인 기준으로 사용한 것은 아니고 제 개인의 경험을 다시 끌어서 쓴 것 같습니다...ㅎ 숫자를 이리저리 변경해 보니 1로만 설정해도 테이블위에 배치되어서 Header 컴포넌트가 가려지는 문제가 해결이 되더라구요. 그래서 1로 수정하도록 할게요!

2024-08-21 14:14 UTC, hwinkr commented on frontend/src/components/_common/Header/Header.styles.ts
>    top: 0;
<img width="942" alt="image" src="https://github.com/user-attachments/assets/dca44523-e7ad-45ee-9ec7-8e6fbb51b52a">

혹시 `sticky`로 설정해서 그런가 하고 `fixed`로 변경하고 해봐도 z-index를 명시적으로 설정해 주지 않으면 `auto`로 설정되어서 문서 순서에 따라 쌓임 맥락이 결정되어 가려지게 되네요...빙봉의 질문 하나로 많이 배워갑니다!!

2024-08-21 15:04 UTC, Yoonkyoungme approved these changes
해리의 의견을 잘 정리해서 코멘트로 남겨주신 점이 좋았어요 :)
반영 감사합니다 해리포터와마법사의돌🍀

2024-08-21 17:58 UTC, merged