[FE] 런칭데이에서 받은 달력 UI 피드백 반영
woowacourse-teams/2024-momo pull request #346
Opened 2024-09-15 08:12 UTC by hwinkr

## 관련 이슈

- resolves: #338 

런칭데이에서 받은 달력 UI 피드백을 반영했습니다. 

- [x] 오늘을 표시하는 방법을 초록색 점이 아닌, 오늘 텍스트로 변경
- [ ]  여러 날짜를 선택할 수 있다는 텍스트를 추가
  - 단계별로 입력을 받는 퍼널 패턴 도입 작업을 하면서 텍스트도 함께 추가할 예정입니다.
- [x]  holidays-kr 라이브러리를 도입하여 실제 대한민국 공휴일을 표시하는 기능 추가
- [x]  시작 날짜, 끝 날짜만 선택하여 연속된 날짜를 편하게 선택할 수 있도록 하는 기능 추가

## 작업 내용

### 오늘을 표시하는 방법을 오늘 텍스트로 변경

기존에는 초록색 점을 활용해서 `오늘` 인것을 표현했었습니다. 런칭데이 피드백을 받으면서,
> _아래 초록색 점으로 인해서 오늘이 이미 선택된 줄 알았어요._  

의 내용이 있었습니다. 해결 방법을 함께 논의하면서 `오늘` 텍스트로 변경하자는 의견으로 결정되었습니다. 

```js
const DATE_INFO_TEXTS = {
  today: '오늘',
  rangeStart: '시작',
  rangeEnd: '끝',
  default: '\u00A0',
};

```
날짜의 추가 정보를 알려주는 텍스트를 상수화 한 객체를 정의했습니다.

```tsx
export default function DateExtraInfo({
  isToday,
  isRangeStart,
  isRangeEnd,
  holidayName,
}: DateInfoProps) {
  return (
    <span css={s_dateExtraInfoText}>
      {getDateInfoText({ isToday, isRangeStart, isRangeEnd, holidayName })}
    </span>
  );
}
```
그리고 날짜 추가 정보를 텍스트로 알려주는 `DateExtraInfo` 컴포넌트를 구현했어요. 
![image](https://github.com/user-attachments/assets/bcda834b-51d3-4e3d-b17c-d5ff893e0b3e)
이제 사용자는 오늘이 어떤 날짜인지를 더 확실하게 인지할 수 있게 되었어요.

### holidays-kr 라이브러리를 도입하여 실제 대한민국 공휴일을 표시하는 기능 추가

런칭데이 피드백 중,
> `공휴일도 함께 표시되었으면 좋겠어요.  `

피드백이 있었습니다. 실제로 저희 서비스에 약속 주최자가 접속해서 약속을 생성할 때, 어떤 날이 공휴일인지를 함께 알려주면 **다른 서비스의 달력을 확인하러 가지 않아도 서비스 내부에서 약속 후보 날짜들을 결정할 수 있게 됩니다.**
다른 서비스, 모모 서비스를 왔다갔다 하면서 날짜를 비교하는 것은 사용자 입장에서 불편하다고 생각되어 반영할 만한 가치가 있는 피드백이라 판단했어요. 자바스크립트 Date 객체는 공휴일 정보까지 제공해주지 않기에 일단 `holidays-kr` 라이브러리를 활용해서 공휴일을 빠르게 그릴 수 있더록 했어요! 

![image](https://github.com/user-attachments/assets/24d614a1-6287-4c4c-b718-9735c7fd11b8)

### 시작 날짜, 끝 날짜만 선택하여 연속된 날짜를 편하게 선택할 수 있도록 하는 기능 추가

런칭데이 피드백 중 아래와 같은 피드백도 있었습니다.
> `긴 범위의 연속된 날짜를 선택할 때, 하나씩 다 눌러야 하니 불편해요...ㅠ`  

그래서, 시작과 끝 날짜만 클릭하면 사이의 모든 날짜가 선택되도록 하는 해결책을 떠올렸고 서비스에 적용해 보기로 했어요.
```ts
const useDateSelect = () => {
  const [selectedDates, setSelectedDates] = useState<string[]>([]);
  const [dateSelectMode, setDateSelectMode] = useState<DateSelectMode>('single');
  const [rangeStartDate, setRangeStartDate] = useState<string | null>(null);
  const [rangeEndDate, setRangeEndDate] = useState<string | null>(null);
```
`useDateSelect` 훅은 아래와 같은 책임을 가집니다.

- 선택된 날짜들을 상태로 관리
- 하나씩 선택하는 모드인지, 범위로 선택하는 모드인지 상태로 관리
- 범위로 선택할 경우의 시작, 끝 날짜를 상태로 관리
- 시작, 끝 날짜가 모두 선택될 경우 그 사이 모든 날짜를 구하고 상태에 반영

추가로, 시작 날짜를 선택한 후 끝 날짜를 선택했는데 끝 날짜가 시작 날짜보다 이른 경우는 해당 끝 날짜가 다시 시작 날짜가 되도록 예외 처리를 했어요. 그리고 시작과 끝 날짜를 더 확실하게 표현해줄 수 있는 UI를 고민하던 중 오른쪽 왼쪽 삼각형을 활용해서 시작과 끝 사이에 특정 날짜들이 포함된다는 컨텍스트를 쉽게 제공할 수 있도록 해줬습니다. 그리고 삼각형 UI도 부족할 수 있을 것 같아서, `DateExtraInfo` 컴포넌트를 활용해서 시작, 끝 텍스트를 추가해줬어요.

![image](https://github.com/user-attachments/assets/66c4206c-e9df-4657-94b5-4ce72e647b79)

## 특이 사항

### 달력 컴포넌트 구조 변경

[feat: 재사용할 수 있는 달력 공통 컴포넌트 구현](https://github.com/woowacourse-teams/2024-momo/commit/82e8f4651ac260a57c5bc537c4880c2b7b7eb9bf)을 보면 확인할 수 있겠지만, 달력 컴포넌트 구조를 변경했어요. render props, Context API + 합성 컴포넌트 패턴을 활용해서 조금 더 유연하게 달력 컴포넌트를 구현했어요. 최대한 날짜 관련 데이터만 다루는 책임만 가지고 마크업, 디자인, 달력 내부에서 일어날 수 있는 사용자의 행동과 관련된 요소들은 외부에서 결정할 수 있도록 해봤습니다. 아마 여기서 조금만 더 재사용성을 고려해 본다면 @Largopie 가 구현해야 하는 날짜만 선택하는 약속 기능에도 재사용할 수 있을 것 같아요. 

### 스토리북 에러 임시 해결

![image](https://github.com/user-attachments/assets/3b82dca8-772f-429c-a5a4-19c4a20670a0)

변경된 달력 컴포넌트를 스토리북 환경에서 UI 테스트를 진행하려고 하니, `React is not defined` 예외가 발생했습니다. 여러 해결책을 찾던 중, 달력 컴포넌트를 구성하는 컴포넌트들에 import React from 'react'를 추가해서 임시 방편으로 해결했어요. 분명 이 문제는 @Largopie 가 해결해준 것 같은데 다시 에러가 발생하더군요...ㅠ 

## 리뷰 요구사항 (선택)

2024-09-18 18:35 UTC, Largopie requested changes
오우.. 해리 굉장히 많은 작업을 해주셨네요..! 일단 굉장히 고생하셨습니다 👏👏👏
제가 꼼꼼하게 리뷰를 하려고했지만, 제 실력이 아직은 부족한 탓에 완벽히 로직을 파악하지는 못한 것 같아요! 그래도 최대한 이해한 선에서 리뷰를 남겨보았습니다!

추가적으로 하나만 고르는 컴포넌트에서 선택되는 모양이 디자인적으로 은근 어색하게 느껴진 것 같습니다. 물론 사용하기에 불편하지 않은 수준이라서 우선순위로 개선할 필요는 없겠지만, 나중에 디자인을 개선할 시간이 주어진다면 한 번 개선해봐도 좋을 것 같아요!

<img width="376" alt="image" src="https://github.com/user-attachments/assets/cb8a4773-bccf-4db2-8b7b-6ff78b732ecb">


그리고, Storybook에서 react is not defined가 나오는 이유는 제가 import를 자동으로 포함시키는 것을 webpack에서만 설정해주었기 때문인 것 같아요. Stroybook 설정에서 별도로 react 선언과 관련된 설정을 건드리거나, 별도로 전체적으로 적용될 수 있게 설정해야 할 것 같네요!

```tsx
// webpack.common.js
new webpack.ProvidePlugin({
      React: 'react',
    }),

```

일단 한 번의 RC는 드리겠지만, 이펙티브한 부분은 없어서 확인 한 번 부탁드리겠습니다용~ 고생했어요 해리 🍀

2024-09-18 18:35 UTC, Largopie commented on frontend/src/components/MeetingCalendar/Date/RangeDate.tsx
> +      <span css={[s_baseDateText]}>{date}</span>
[P3]

하나의 css prop을 사용하니 없어도 괜찮을 것 같아요 :)
```suggestion
      <span css={s_baseDateText}>{date}</span>
```

2024-09-18 18:35 UTC, Largopie commented on frontend/src/components/MeetingCalendar/Date/DateExtraInfo.tsx
> +  default: '\u00A0',
[Q]

'\u00A0' 이 문자는 무슨뜻일까요?

2024-09-18 18:35 UTC, Largopie commented on frontend/src/components/MeetingCalendar/Date/DateExtraInfo.tsx
> +export default function DateExtraInfo({
[Q]

DateExtraInfo라는 컴포넌트명을 선택하신 이유가 있을까요? 
제 개인적인 견해로는 이름을 처음 보고 해당 컴포넌트의 역할이 무엇인지 파악하기 어려웠던 것 같아요!

2024-09-18 18:35 UTC, Largopie commented on frontend/src/components/MeetingCalendar/Date/DateExtraInfo.tsx
> +  default: '\u00A0',
[P3]

++ 해당 컴포넌트 내에서 한번만 사용되는 문자열이라면 분리안해도 괜찮지 않을까 조심스레 의견 던져봅니다!

2024-09-19 06:20 UTC, Yoonkyoungme requested changes
해리🍀 추석 동안 쉬지 않고 달력 UI 개선하느라 고생 많으셨어요👏👏
2024 추석은 모모와 함께 ~
몇 가지 간단한 피드백 남겨두었습니다 :) 확인해 주셔요!

2024-09-19 06:20 UTC, Yoonkyoungme commented on frontend/src/types/calendar.ts
> +export type MonthStatus = 'prevMonth' | 'currentMonth' | 'nextMonth';
type명에서 Month와 관련있다는 것이 유추 가능해서 'Month' 접미사를 생략해도 괜찮을 것 같아요!
```suggestion
export type MonthStatus = 'prev' | 'current' | 'next';
```

2024-09-21 02:28 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.ts
> +  const [currentFullDate, setCurrentFullDate] = useState(new Date());
커밋 흐름 신경쓰도록 하겠습니다~ 👍👍👍 저도 커밋 단위로 리뷰 하는데 신경쓰지 못했네요...😢

2024-09-21 02:40 UTC, hwinkr commented on frontend/src/hooks/useCalendarContext/useCalendarContext.ts
동의합니다~

2024-09-21 02:40 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.ts
> +  };
ㅋㅋ

2024-09-21 02:41 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.ts
> +  };
개행개행~

2024-09-21 02:51 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Date/Date.styles.ts
> +`;
엥 왜 저렇게 했을까요..ㅋㅋ

2024-09-21 02:53 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Date/Date.styles.ts
> +};
그러네요~ 저도 선언을 위 라인에 하고 아래 라인에서 참조해서 사용하는 것에 동의합니다! 디테일적인 부분에 대한 피드백 감사합니다~

2024-09-21 03:04 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Date/DateExtraInfo.tsx
> +  default: '\u00A0',
`\u00A0`는 줄바꿈을 하지 않는 빈칸을 의미하는 HMTL 특수 문자표(Entity)입니다. 해당 문자표를 사용한 이유는, 

const DATE_INFO_TEXTS = {
  today: '오늘',
  rangeStart: '시작',
  rangeEnd: '끝',
  default: '',
};

위와 같이 빈 문자열로 설정할 경우, 
<img width="366" alt="image" src="https://github.com/user-attachments/assets/8c6ce00c-0b7d-42d2-a6ba-91d1903c2f3c">
공휴일인 달과 그렇지 않은 달의 행간이 맞지 않는 문제가 있습니다. `' '`와 같이 빈 칸을 추가해도 마찬가지였구요. 그래서 사용하게 되었습니다. [HTML Entities Table](https://www.webatic.com/html-entities-table)에서도 확인할 수 있어요:)

2024-09-21 03:11 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Date/DateExtraInfo.tsx
> +export default function DateExtraInfo({
저도 해당 컴포넌트의 네이밍에 대해서 굉장히 많은 고민을 했었는데요! 공휴일, 시작, 끝, 오늘, 빈 문자...등등 다향한 정보를 추가적으로 알려준다는 느낌을 표현하고자 했습니다. 기본적으로 날짜 정보(숫자)는 알려주니까 **추가적이라는** 느낌을 주고 싶었어요. 아직도 애매모호함이 남아있긴 하네요...

`DateAdditionalText`는 어떤가요~? 괜찮다구요? 알겠어요!

2024-09-21 03:16 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Date/Date.styles.ts
> +  if (isSunday) return DAY_SLOT_TEXT_STYLES.holiday;
오..find 메서드를 활용해서 조건에 맞는 배열의 첫 번째 요소를 반환하면 우선순위와 관련된 문제도 자연스럽게 해결할 수 있겠네요.

2024-09-21 04:41 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Date/Date.utils.ts
> +  const todayFullDate = getFullDate(today);
좋습니다~ 기존에 날짜 도메인 용어를 맞췄던 것을 최대한 지킬 수 있도록 변수명을 수정하도록 할게요!

2024-09-21 04:46 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Header/index.tsx
> +        </TabButton>
정말 디테일하게 피드백을 주시네요~ `aria-label`을 추가해서 더 접근성 높은 달력 컴포넌트를 만들어보도록 할게요!

2024-09-21 04:52 UTC, hwinkr commented on frontend/src/components/_common/Calendar/index.tsx
> +import React from 'react';
Fragment가 저희를 엄청 괴롭히네요...render props 패턴을 활용하고 있고, 부모 컴포넌트로 감쌀 필요가 없다고 생각해서 Fragment를 제거하는 방향으로 변경해 볼게요

```tsx
return <>{render(weekDays)}</>;
```
->
```tsx
return render(weekDays);
```

2024-09-21 04:53 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.ts
> +    body: {
피드백 반영을 위해서 둘 다 복수형으로 하려고 bodies로 변경하니 뭔가 이상하네요...굳이 headers가 복수형이 아니어도 충분히 의미를 전달할 수 있을 것 같으니, headers -> header로 변경해 볼게요.

2024-09-21 04:56 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.utils.ts
> + * ]
깃허브에서 코드 리뷰를 할 때는, 콘솔에서 직접 확인을 하기 힘드니 코드를 읽을 때 반환값 예시가 있으면 이해하기 더 쉬울 것 같다고 생각해서 작성했었습니다. 저는 다른 사람의 코드를 리뷰할 때, 콘솔에서 직접 확인하지 않으니 반환값 예시를 그대로 두면 좋을 것 같다고 생각해요~ 주석의 경우는 프로덕션 빌드에서 제거가 되니 번들 사이즈 관련 문제도 없을 것 같아요

2024-09-21 04:56 UTC, hwinkr commented on frontend/src/types/calendar.ts
> +export type MonthStatus = 'prevMonth' | 'currentMonth' | 'nextMonth';
좋은 피드백인 것 같아요~ month가 중복되고 있네요.

2024-09-21 05:03 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.utils.ts
> +  });
훨씬 보기 좋고 깔끔하네용~

2024-09-21 05:52 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.utils.ts
> +  return (firstOfMonth.getDay() + 7) % 7;
로직 상 실수가 있었네요...ㅎ

2024-09-21 06:24 UTC, hwinkr commented on frontend/package.json
> +    "@hyunbinseo/holidays-kr": "3.2025.1",
우선 공휴일을 직접 매년 업데이트 하는 것도 방법이지만, 배꼽이 더 커지는 구현이라고 생각해 라이브러리를 활용하기로 결정했습니다. 

![image](https://github.com/user-attachments/assets/93ee47b5-e2fe-4109-a623-ccdb30847e0d)

위 이미지에서 확인할 수 있듯, 세 라이브러리를 비교해 본 결과 현재 사용하고 있는 라이브러리의 다운로드 수가 가장 많은 것을 확인할 수 있었습니다. 그리고 가장 최근 커밋도 2주 전이고 계속해서 버젼 업데이트가 되는 것을 확인할 수 있었습니다. 기왕 라이브러리를 활용하기로 한 거, 다운로드 수도 많고 가장 활발히 업데이트 되고 있는 라이브러리를 사용하고자 했습니다.

2024-09-21 06:43 UTC, hwinkr commented on frontend/src/utils/date.ts
> +export const getDate = (date: Date) => date.getDate();
저는 `.`을 사용해서 객체의 메서드를 호출하는 것 보다 위 구현처럼 함수로 만드는 것이 더 가독성 측면에서 괜찮다고 생각해서 저렇게 구현한 것인데... 나중에 확장성을 위해서라도 일단 저렇게 분리해서 구현하는 것이 어떨까요??!!

2024-09-22 14:54 UTC, Largopie commented on frontend/src/utils/date.ts
> +export const getDate = (date: Date) => date.getDate();
추후에 확장을 한다면 어떠한 형태로 확장할 수 있을까요?  특별하게 확장성이 있는 함수의 경우에만 추후에 별도로 분리하여 구현하는 방법도 괜찮다고 생각합니다 :)

실질적으로 1, 2번의 방법이 속도차이에서 큰 변화가 있지는 않으며, 가독성이 좋을 수는 있다고 생각합니다.

하지만 개인적으로 느끼기에는 1번의 경우보다 2번의 경우가 같은 결과를 반환하는 함수를 중복적으로 선언하지 않기 때문에 더 낫다는 생각이 드네요!

1. getMonth 함수 호출 -> Date 객체 내장 함수 호출 -> Date 내장 함수 결과 반환 -> getMonth 함수 결과 반환
2. Date 객체 내장 함수 호출 -> Date 내장 함수 결과 반환

그럼에도 해리가 생각하기에 확장 가능성이 있고, 가독성이 편리하다면 그대로 구현해도 괜찮을 것 같아요!

2024-09-22 15:20 UTC, Largopie requested changes
핼리콥터~! 빠르게 RC를 들고 나타난 낙타🐫에요~
수정사항 반영 부탁드려요~!

2024-09-23 14:25 UTC, Yoonkyoungme reviewed
헬리콥터~! 조금 느리지만 Comment를 들고 나타난 빙봉🔮이에요~ (낙타가 달리기가 빠르네요! 이랴 이랴)
가벼운 코멘트 1개 확인 부탁드려요~
앞서 낙타가 RC를 준 부분이 반영되면 다시 한번 멘션 주세요! 바로 Approve 하러 달려오겠습니다

2024-09-23 14:25 UTC, Yoonkyoungme commented on frontend/src/components/MeetingCalendar/Date/DateAdditionalText.tsx
> +};
[P3]

`DATE_INFO_TEXTS` 객체에 `as const`를 추가하여 타입 안정성을 높여볼 수 있을 것 같네요!

2024-09-23 14:25 UTC, Yoonkyoungme commented on frontend/src/components/MeetingCalendar/Header/index.tsx
> +          aria-label="하나씩 선택하기"
👍👍👍

2024-09-24 12:01 UTC, hwinkr commented on frontend/src/components/_common/Buttons/TabButton/index.tsx
> +  children: React.ReactNode;
동의합니다! 수정할게요~

2024-09-24 12:01 UTC, hwinkr commented on frontend/src/components/MeetingCalendar/Date/Date.styles.ts
> +  if (!isValidArrayType<string, DateStatus>(Object.keys(dateStatusMap), dateStatusArray)) return;
> _[P2]_

> _해당 반환 함수를 편하게 확인할 수 있도록 테스트케이스를 구현해보는 것은 어떨까요? 🤓_

낙타가 빠르게 쓰셔야 한다고 하니,,,일단 머지를 한 후 테코톡이 끝난 후 테스트를 진행해 보도록 할게요,,,ㅎ

2024-09-24 12:13 UTC, merged