[FE] 체크박스 공통 컴포넌트 구현
woowacourse-teams/2024-momo pull request #359
Opened 2024-09-22 14:45 UTC by Largopie

## 관련 이슈

- resolves: #358 

## 작업 내용

- [x] 공통 체크박스 컴포넌트 구현
- [x] 스토리북 작성

가장 작은 단위의 체크박스 공통 컴포넌트를 만들었습니다. 디자인적인 요소는 아직 고려하지 않았습니다. 현재 SVG를 react-icons로 대체할 가능성이 있어, 기능적으로 동작하기 위한 컴포넌트로 우선적으로 제작했습니다. 

따라서 가장 기본적인 형태의 ipnut을 통해 구현했습니다.

화면 기록 2024-09-22 오후 11.36.36.mov

## 특이 사항

## 리뷰 요구사항 (선택)

2024-09-23 14:59 UTC, Yoonkyoungme requested changes
낙타🐪🐫
체크 박스 컴포넌트 잘 만들어주셨네요~~~~✅
몇 가지 코멘트 확인 부탁드려요 :)

2024-09-23 14:59 UTC, Yoonkyoungme commented on frontend/src/components/_common/Checkbox/index.tsx
> +import React from 'react';
[P2]

React 17부터는 JSX를 사용하더라도 React를 명시적으로 import하지 않아도 되기 때문에
해당 import문은 지워도 될 것 같아요!

2024-09-23 14:59 UTC, Yoonkyoungme commented on frontend/src/components/_common/Checkbox/Checkbox.stories.tsx
> +  tags: ['autodocs'],
[P3]

낙타~~ `tag: [autodocs]`를 따로 기입하지 않아도 자동으로 문서가 생성됩니다! (생략 가능)

`.storybook/main.ts`에 아래와 같이 코드가 작성되어있어요 :)
```ts
const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-webpack5-compiler-babel',
    '@storybook/addon-onboarding',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@chromatic-com/storybook',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
  docs: {
    autodocs: true, // 이 부분 때문에 문서가 자동으로 생성됩니다.
  },
  ```

2024-09-23 14:59 UTC, Yoonkyoungme commented on frontend/src/components/_common/Checkbox/Checkbox.styles.ts
> +  gap: 0.2rem;
[P3]

아래 사진처럼 Stylelint 경고가 발생하고 있어요!
🚨gap 속성이 align-items보다 앞에 와야 한다는 경고가 발생🚨

<img width="703" alt="image" src="https://github.com/user-attachments/assets/c800f875-821d-4146-b3ee-1accc3373785">

제 VSCode에서 확인해 봤을 때 command + S 누르면 자동 순서 정렬이 잘 되는 것 같습니다! 한 번 확인해 보셔용~~

2024-09-24 11:34 UTC, Largopie reviewed
빙봉 반영완!

2024-09-24 11:34 UTC, Largopie commented on frontend/src/components/_common/Checkbox/Checkbox.stories.tsx
> +  tags: ['autodocs'],
좋은데요 빙봉~~~👍

2024-09-24 11:34 UTC, Largopie commented on frontend/src/components/_common/Checkbox/Checkbox.styles.ts
> +  gap: 0.2rem;
제가 frontend 폴더 내부로 들어가서 작업했어야했는데 이 부분을 놓치고 말았어요 ㅠ 감사합니다 수정할게요 :)

2024-09-24 11:34 UTC, Largopie commented on frontend/src/components/_common/Checkbox/index.tsx
> +import React from 'react';
Fragment를 사용했다가 지웠는데 이걸 안지워줬군요 ㅠ 수정하겠습니다!

2024-09-24 11:42 UTC, Yoonkyoungme approved these changes
꼼꼼한 반영 감사합니다👍 행운의 Approve를 드려요🐪

2024-09-24 14:19 UTC, hwinkr reviewed
체크박스 빠른 구현 고생하셨습니다 낙타~ 

스토리북 훅 관련 궁금증이 있어서, 답 해주시면 감사할 것 같습니다!! 🐫🐫🐫

2024-09-24 14:19 UTC, hwinkr commented on frontend/src/components/_common/Checkbox/Checkbox.styles.ts
> +  gap: 0.2rem;
엥 저는 frontend 폴더 내부로 이동하지 않더라도 잘 되던데용

2024-09-24 14:19 UTC, hwinkr commented on frontend/src/components/_common/Checkbox/Checkbox.stories.tsx
> +      const [{ isChecked }, setArgState] = useArgs();
### [Q]

`useArgs`훅은 `useState`훅이랑 뭐가 다른가용? 

```tsx
  decorators: [
    (Story, context) => {
      const [selectedDates, setSelectedDates] = useState<string[]>([]);

      const hasDate = (date: string) => selectedDates.includes(date);

      const handleDateClick = (date: string) => {
        setSelectedDates((prevDates) =>
          hasDate(date) ? prevDates.filter((d) => d !== date) : [...prevDates, date],
        );
      };
```

이전 달력 컴포넌트를 테스트할 때는, 리액트의 훅을 써서 테스트를 했어서 차이가 궁금하군요!

2024-09-24 14:20 UTC, hwinkr approved these changes
일단 로직, 마크업, 접근성 부분에서 개선할 부분은 보이지 않아서 approve로 변경합니다!

2024-09-26 11:01 UTC, Largopie commented on frontend/src/components/_common/Checkbox/Checkbox.stories.tsx
> +      const [{ isChecked }, setArgState] = useArgs();
## 이 부분은 나중에 답변 달아드리도록 하겠습니다.

스토리북 하단의 값과 동기화 시키기 위해 useArgs를 사용했습니다.
해당 자료를 보면서 참고했던 것 같네요!

https://handhand.tistory.com/330

2024-09-26 11:04 UTC, merged