[FE] 달력 테스트 코드 작성
woowacourse-teams/2024-momo pull request #383
Opened 2024-10-04 11:34 UTC by hwinkr

## 관련 이슈

- resolves: #382 
- jsDoc을 삭제하고 jest, RTL을 활용해서 달력 데이터 생성 로직에 대한 테스트 코드를 작성했습니다.

## 작업 내용

- 현재 달력 데이터를 생성하는 모듈은 이전 달, 다음 달 데이터를 함께 생성하게 됩니다.  
-> UI에서 이전 달, 다음 달 데이터를 활용할 수도 있기에 유연하게 해당 모듈을 사용하기 위해서 이 방식으로 구현했었습니다.
-> 현재 저희 서비스에서는 사용하고 있지는 않지만, 학습 겸 어떻게 더 달력 데이터를 유연하게 만들 수 있을까 하다가 이 방식을 떠올렸고 구현했습니다. 

### useCalendar.utils.test.ts

- 주, 월 별 달력 데이터를 올바르게 생성하는지 확인합니다.
- 생성된 달력 데이터들의 날짜가 올바른 상태(prev, current, next)를 가지는지 확인합니다.

### useCalender.test.ts

- 달력 데이터를 변경할 수 있는 책임을 가집니다.
- 이전 달, 다음 달로 이동했을 때 데이터가 이에 맞게 올바르게 변경되는지 테스트 합니다. 

## 특이 사항

달력 로직이 생각보다 복잡해서 시간이 많이 소요되었네요...원래는 스토리북도 더 직관적으로 확인할 수 있도록 날짜 상태에 따른 날짜 UI도 구분해서 UI 테스트를 진행하려고 했는데 이슈를 한 번 더 파야할 것 같아요! 테스트 초록불이 뜨니 안전한 달력을 만들었다는 느낌이 들어 안심이 되네요..ㅎ 

자바스크립트는 달(Month)의 인덱스를 0부터 시작해서 테스트 코드를 작성할 때 1씩 빼주고 테스트를 진행했습니다. UI영역에서 현재 달에 +1을 해준 것을 확인할 수 있는데, 0부터 시작하는 예외를 처리해주기 위함이었습니다! 리뷰하실 때, 참고바랍니다 🙏🙏🙏

## 리뷰 요구사항 (선택)

2024-10-07 08:24 UTC, Largopie requested changes
해리 테스트케이스까지 구현하니 너무 좋은 것 같아요~! 멋쨍이에요~🍀

조금 더 멋진 테스트 케이스가 되기 위한 리뷰를 남겨두었으니 해리 생각을 자유롭게 말해주세요~!
복잡한 로직에 대한 테스트케이스 구현하느라 고생 많았어요~

![18668cc83cf51756a](https://github.com/user-attachments/assets/58f3c2db-0f8e-4bd5-906c-5abcb16b279c)

2024-10-07 08:24 UTC, Largopie commented on frontend/src/hooks/useCalendar/useCalendar.test.ts
> +      jest.setSystemTime(new Date(TEST_YEAR, TEST_MONTH, TEST_DATE));
[P3]

반복되는 로직이므로 beforeAll에 추가시켜도 좋겠네요 :)

2024-10-07 08:24 UTC, Largopie commented on frontend/src/hooks/useCalendar/useCalendar.test.ts
> +    it('다음 년도로 이동하면, 년도가 변경되어야 한다.', async () => {
[P3]
"이전 년도로 이동한다"라고 되어있는데 moveNextMonth로 다음 달로 이동하고 있기 때문에 구체적으로 명시하면 좋을 것 같아요!🙌

"마지막 달이 되었을 때, 다음 달로 이동하면 년도가 1년 추가된다"와 같이 구체적인 테스트케이스 명세는 어떨까요?
바로 아래 테스트케이스인 "이전 년도 이동하면, 년도가 변경되어야 한다."도 비슷합니다.

2024-10-07 08:24 UTC, Largopie commented on frontend/src/hooks/useCalendar/useCalendar.test.ts
> +    it('이전 달로 이동하면, 달 데이터가 변경되어야 한다.', () => {
[Q]
async가 붙은 테스트케이스도 있고, 안붙은 테스트케이스도 있는데 어떤 차이가 있을까요?

2024-10-07 08:50 UTC, Yoonkyoungme requested changes
해리~~ 풍부한 테스트 코드 작성하느라 고생 많았어요!

[P2]
`2월`, `윤년`, `연말` 등 **경계 날짜**에서도 테스트가 잘 돌아가는지 확인해보면 좋을 것 같아요 :)

2024-10-07 08:50 UTC, Yoonkyoungme commented on frontend/package.json
> +    "test": "jest --watch",
박수👏👏👏👏👏👏👏

2024-10-07 08:50 UTC, Yoonkyoungme commented on frontend/src/hooks/useCalendar/useCalendar.utils.ts
> +    newDate.setDate(getDate(monthStartDate) + CALENDAR_PROPERTIES.daysInOneWeek * i);
[P3]
정말 정말 * 1000000000 가벼운 제안입니다!
`monthStartDate`  → `startDateOfMonth` 로 바꿔보는 것도 괜찮을 것 같네요! 뭔가 확 눈에 띄는 느낌입니다 ㅎㅎ

2024-10-07 08:50 UTC, Yoonkyoungme commented on frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
> +      expect(getDate(result)).not.toBe(TEST_DATE);
[P3]

제 생각에는 `getDate(result)`가 `not.toBe(TEST_DATE)`인지를 검사하는 부분은 큰 의미가 없어 보입니당!`setFirstDate(testDate)`는 첫 번째 날짜로 변경하는 함수이므로 테스트의 본질은 그 날짜가 1이 되는지를 확인하는 것이라고 생각합니다.

2024-10-10 02:45 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
> +    it('getYear 함수는 올바른 년도를 반환한다.', () => {
getYear, getDate 함수는 2024, 31일 처럼 예상되는 값을 반환해 주는데,

- getMonth: 현재 달에서 1을 뺀 값을 반환
- getDay: 일요일을 인덱스 0으로 설정, 각 요일마다 인덱스를 부여한 후 숫자를 반환

해당 두 메서드는 처음 사용할 때 많이 당황스러웠던 부분이었어요. 그래서, 테스트를 통해서 혼란을 줄여보고자 했습니다. 그래서 getMonth, getDay 함수 테스트는 남겨놓았으면 하는데 어떠신가요?

2024-10-10 02:49 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.test.ts
> +      jest.setSystemTime(new Date(TEST_YEAR, TEST_MONTH, TEST_DATE));
저도 초반에는 그렇게 구현을 했었는데요. 달력 년도 이동을 테스트 하는 코드를 잘 보면 모든 테스트 케이스에서 같은 날짜를 사용하지 않는 것을 확인할 수 있습니다. 그래서 beforeAll 메서드는 사용할 수 없게 되었습니다.

2024-10-10 02:52 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.test.ts
> +    it('이전 달로 이동하면, 달 데이터가 변경되어야 한다.', () => {
실수입니다~

2024-10-10 02:55 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
> +      expect(getDate(result)).not.toBe(TEST_DATE);
동의합니다.

2024-10-10 03:01 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
> +      const { status } =
해당 테스트 케이스들은 `getWeeklyDate` 함수를 테스트하기 위한 목적이라서 전체 테스트를 한다기 보다는 전체를 만들기 위한 조각을 테스트한다고 생각해 주시면 될 것 같습니다!

2024-10-10 03:01 UTC, hwinkr commented on frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
> +      const { status } =
filter를 사용하는 것으로 수정하고, 모든 날짜들이 예상되는 상태를 가지는지 테스트해 보도록 할게요~

2024-10-10 04:14 UTC, hwinkr commented
> 해리~~ 풍부한 테스트 코드 작성하느라 고생 많았어요!
> 
> [P2] `2월`, `윤년`, `연말` 등 **경계 날짜**에서도 테스트가 잘 돌아가는지 확인해보면 좋을 것 같아요 :)

연말, 1월에 대한 테스트는 진행되어 있습니다.

윤년의 경우, 날짜가 29일까지 있는지 확인하는 것으로 테스트를 진행해 볼게요!

2024-10-11 06:38 UTC, Yoonkyoungme approved these changes
고생하셨어요 해리! 리뷰 반영해줘서 고마워용🍀
<img width="272" alt="image" src="https://github.com/user-attachments/assets/f80cae4a-0182-4824-ad06-bf682562254d">

2024-10-13 11:27 UTC, Largopie commented on frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
> +    it('getYear 함수는 올바른 년도를 반환한다.', () => {
그런 이유라면 좋아요 :)

2024-10-13 11:42 UTC, Largopie approved these changes
반영 잘 해주셧네요 해리~ 감사합니다~!!! 👍👍👍👍

2024-10-13 12:14 UTC, merged