[FE] 약속 초대 페이지 구현 및 바로 약속 등록하기 페이지에서 바로 드래그/클릭으로 약속 등록이 가능하게 구현
woowacourse-teams/2024-momo pull request #403
Opened 2024-10-11 17:07 UTC by Yoonkyoungme

## 관련 이슈

- resolves: #388 

## 작업 내용

### 유저 피드백 (개선 전)
4차 데모데이 때 유저들한테 아래와 같은 피드백을 받았습니다.
> 👤 참여자가 전달 받은 링크로 접속 시, 시간 테이블이 아닌 로그인 화면을 먼저 보여주도록 개선
👤 참여자가 등록 또는 수정 버튼을 클릭한 후 로그인을 진행하고, 다시 등록/수정 버튼을 눌러야만 가능한 시간을 입력하는 플로우가 어렵다.
👤 버튼으로 등록하기/수정하기를 하기 보다는 테이블을 바로 드래그해서 시간 표현이 가능하도록 하는게 어떨까
>

<br />

### 개선한 서비스 플로우
![image](https://github.com/user-attachments/assets/8e7f8eef-f322-49be-a798-b6f7f8cab854)
1. **참여자가 전달 받은 링크로 접속 시, 약속 입장 페이지로 이동하도록 수정**
    - 참여자가 전달 받은 링크로 접속하면 바로 ‘약속 현황 조회/등록 페이지’로 이동하는 것이 아니라, '약속 초대 페이지’를 먼저 보여준다.
2. **약속 초대 페이지 선택지 제공**
    약속 초대 페이지에서는 아래 두 가지 선택지를 제공한다.
     2-1. 약속 등록하기
            - 비회원 로그인을 진행한 후, 본인의 가능한 일정을 등록할 수 있다.
            - 아무 것도 드래그하거나 클릭하지 않은 상태라면 ‘등록하기’ 버튼은 비활성화된다.     
  
  |            | disabled                    | enabled                   |
  |------------|-----------------------------|---------------------------|
  | 날짜+시간  | ![image1](https://github.com/user-attachments/assets/a13f408e-db54-45e3-89de-e0c6cb8e8252) | ![image2](https://github.com/user-attachments/assets/b9c6a671-1604-48e8-b3bc-017c972d387b) |
  | 날짜        | ![image3](https://github.com/user-attachments/assets/d73c8238-e8f6-4f8e-91c6-614ed94e564a) | ![image4](https://github.com/user-attachments/assets/3040e7d0-829d-4e49-88b8-304c0b8489b5) |

    2-2. 약속 조회하기 + 수정하기
        - 사용자는 자신을 포함하여 약속에 참여한 사람들이 등록한 일정을 조회할 수 있다. 또한, 본인의 일정을 업데이트할 수 있다.
        - 약속 등록 페이지와 달리, 아무 것도 드래그하거나 클릭하지 않아도 '등록하기' 버튼이 활성화되어 업데이트할 수 있다.

|            날짜+시간           | 날짜                     |
|-----------------------------|-------------------------|
| ![image1](https://github.com/user-attachments/assets/d0627913-4bd6-44bf-90e8-547cb6e152f9) | ![image2](https://github.com/user-attachments/assets/1d9c2167-88bd-4eed-945c-0451e056fd6e) |

<br />

## 참고 자료

[작업 현황 정리 노션 링크](https://paper-mass-5ff.notion.site/7a1d97ab41a34c5fb1ea7caa57c842a8?pvs=4)

<br />

## 특이 사항

## 리뷰 요구사항 (선택)

2024-10-12 12:50 UTC, Largopie approved these changes
전반적으로 깔끔하게 구현하셨네요 👍
특별히 많이 개선해야될 부분은 보이지 않아서 Approve 드립니다 :)


### 🎯 추가 반영 요청 사항

약속 초대 페이지에 사용되는 API에 대한 MSW가 구현되어 있지 않아서 로컬에서 서버를 켜서 확인해야하는 작업이 필요합니다 🥹
전달 받은 JSON 데이터를 기반으로 추후에 MSW도 구현해주시면 좋을 것 같아요!

고생했어요 빙봉 🔮

2024-10-12 12:50 UTC, Largopie commented on frontend/src/stores/servers/schedule/mutations.ts
> +      callback?.();
오.. 이렇게 사용할 수도 있군요 신기방기네요

https://ko.javascript.info/optional-chaining#ref-480

2024-10-12 12:50 UTC, Largopie commented on frontend/src/stores/servers/meeting/queries.ts
> +    retry: 1,
[Q]

retry를 1로 설정한 이유가 있나요?

2024-10-13 12:09 UTC, hwinkr requested changes
빙봉뱅봉 고생하셨습니다!!! 

얘기나누고 싶은 부분이 있어서, RC 드려요 ㅎㅎ 

fetch 함수 사용에 관해서는 이야기 나눠서 의문이 해결됐네요 ㅎㅎㅎ!!

2024-10-14 09:22 UTC, Yoonkyoungme commented on frontend/src/components/MeetingConfirmCalendar/Picker/index.tsx
> +  };
추상화 하면 유틸 함수가 아래처럼 될 것 같은데, 어떻게 생각하시나용? 더 좋은 방법이 있을까요? @hwinkr 

```ts
import type { Mode } from 'types/schedule';

import type { PostScheduleRequest } from '@apis/schedules';

interface SubmitScheduleChangesProps {
  mode: Mode;
  selectedDates: string[];
  convertedData: PostScheduleRequest;
  convertSelectedDatesToRequest: (data: string[]) => PostScheduleRequest;
  registerSchedule: (data: PostScheduleRequest) => void;
  updateSchedule: (data: PostScheduleRequest) => void;
}

export const submitScheduleChanges = ({
  mode,
  selectedDates,
  convertSelectedDatesToRequest,
  registerSchedule,
  updateSchedule,
}: SubmitScheduleChangesProps) => {
  if (mode === 'register' && selectedDates.length === 0) {
    return;
  }

  const convertedData = convertSelectedDatesToRequest(selectedDates);

  mode === 'register' ? registerSchedule(convertedData) : updateSchedule(convertedData);
};

```

2024-10-14 11:08 UTC, hwinkr approved these changes
고생하셨어요 빙봉!

2024-10-14 11:08 UTC, hwinkr commented on frontend/src/components/MeetingConfirmCalendar/Picker/index.tsx
> +  };
제가 말한 추상화는 유틸 함수가 아니라, 커스텀 훅을 구현하는 것이긴 했습니다. mode에 따라서 어떤 뮤테이션을 발생시킬지 커스텀 훅 내부에서 결정만 해주면 두 컴포넌트에서 동일한 커스텀 훅 내부 로직을 재사용할 수 있을 것이라 생각했기 때문이에요! 꼭 반영해 주지 않으셔도 됩니다. 제가 P[n]룰 지키는 것을 깜빡했네요...😭

2024-10-15 13:17 UTC, Yoonkyoungme commented on frontend/src/router.tsx
> +        element: SuspenseWrapper(MeetingInvitePage),
좋은 피드백 감사해요👍

반영 커밋: 306895c9428fe7f80cc0f79b0faefe5fe0fb384a

2024-10-15 13:24 UTC, Yoonkyoungme commented on frontend/src/stores/servers/meeting/queries.ts
> +    retry: 1,
@Largopie 

`retry` 값을 1로 설정한 이유는 명확한 컨벤션이 없었기 때문에, 적절한 값을 고민한 끝에 결정하게 되었습니다. 

tanstack query의 `retry` 옵션은 기본적으로 3으로 설정되어 있가 때문에 네트워크 요청이 실패하면 최대 3번까지 자동으로 재시도됩니다. 하지만 기본값을 사용하는 경우, 사용자가 데이터를 불러오는 동안 여러 번의 실패와 재시도가 발생해 피드백이 늦어진다고 판단했습니다. 
따라서 `retry` 값을 1로 설정하여, 최초 요청 실패 시 단 한 번만 재시도하고, 사용자가 빠르게 오류를 인지하고 필요한 조치를 취할 수 있도록 피드백 속도를 높이고자 하였습니다.

<img width="625" alt="image" src="https://github.com/user-attachments/assets/8e448641-a5de-4902-bc72-0ab965bc6f1d">

retry에 대한 이야기도 함께 나눠보면 좋을 것 같아용

2024-10-15 13:28 UTC, merged