[BE] 최소 시간을 보장 추천 로직 추가
woowacourse-teams/2024-momo pull request #404
Opened 2024-10-13 13:53 UTC by ikjo39

## 관련 이슈

- resolves: #398 

## 작업 내용

최소 시간을 보장하는 로직을 추가하였습니다.

### 최소 시간 기준
최소 시간의 경우 30분, 60분, 120분과 같이 현재 시간 로직과 동일하게 30분 단위로 기준을 잡았습니다.

### 최소 시간 보장 로직
최소 시간 보장하는 로직을 어디에 둘지 고민했는데요. 제가 생각한 최소 요구사항은 아래와 같았습니다.
- sort 기준을 `Duration` 크기의 역순으로 걸고 최소 시간보다 작은 것은 필터링한다.
- 출력할 땐 참가자가 많은 순서대로 정렬 후 시간이 빠른 순(Earliest)으로 정렬한다.

처음엔 `ScheduleRecommender`의 아래 메서드 반환 로직에 `filter()`문을 추가하였다가 불필요하게 모든 요소를 탐색하므로 수정하였습니다.

```java
public abstract class ScheduleRecommender {

    public List<CandidateSchedule> recommend(
            AttendeeGroup group, String recommendType, MeetingType meetingType, int minTime
    ) {
        //...//
        return mergedCandidateSchedules.stream()
                .filter(candidateSchedule -> candidateSchedule.duration().getSeconds() >= HALF_HOUR_INTERVAL * 60)
                .limit(getMaxRecommendCount())
                .toList();
```

때문에 `CandidateSchedule`내에 `mergeContinuous` 안에 위치시켰습니다.
반복문을 필연적으로 돌아야 하는 곳에서 분기 처리 하는게 효율적이라 생각하였어요 :)

## 특이 사항

추천 로직 API 에 대해 요구사항이 변경되었습니다!
다만, 기존 로직과 충돌을 방지하기 위해 새로 추가된 `@RequestParam`인  `minTime`에 기본 값을 설정해두었습니다.

## 리뷰 요구사항

전체적으로 로직에서 불합리한 부분이 없는지와 테스트가 부족한 부분이 없는지 확인 부탁 드려요~

2024-10-17 06:46 UTC, seokmyungham requested changes
다온 고생하셨습니다 😁
받으면 기분이 좋아지는 RC를 드립니다 🚀

2024-10-17 06:46 UTC, seokmyungham commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +        }
서비스에서 이 검증을 수행한 다음에 추천 로직을 수행하는게 자연스러울 것 같아요

2024-10-17 06:46 UTC, seokmyungham commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +                .ifPresent(mergedSchedules::add);
```suggestion
        if (subList.size() >= minSize) {
            subList.stream()
                    .reduce(CandidateSchedule::merge)
                    .ifPresent(mergedSchedules::add);
        }
```

이건 어떤가요??

2024-10-17 06:46 UTC, seokmyungham commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +        );
다온이 만든 코드는 아니지만 😅
지금 dto 변환 작업을 두 번에 나눠서 하고 있는데 한 번에 하면 더 좋을 것 같아요

2024-10-17 06:46 UTC, seokmyungham commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleControllerDocs.java
> +            @RequestParam @Schema(description = "추천 기준(이른 시간 순 / 길게 볼 수 있는 순 / 최소 시간 보장 순)", example = "earliest")
최소 시간 보장은 추천 기능의 하나의 옵션이라고 보는게 맞는 것 같아요.
함께 논의해봅시다.

2024-10-17 06:47 UTC, hw0603 requested changes
고생하셨습니다 다온!
정책 관련된 부분은 다른 팀원들이랑 전체 논의가 한 번 필요해 보이네요🤔

2024-10-17 06:47 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +            List<CandidateSchedule> subList, List<CandidateSchedule> mergedSchedules, int minSize
```suggestion
    private static void addIfLongerThanOrEqualToMinTime(
```
일반적으로 사용되는 메서드 명명법을 따라 볼까요? 🙂

2024-10-17 06:47 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +        if (minSize > subList.size()) {
`minSize` 검증의 책임은 `SeheduleService`에게 있지 않을까요?

2024-10-17 13:21 UTC, ehBeak requested changes
다온 구현하시느라 고생 많으셨습니다~

간단한 코멘트 남겨요 :)
추가로, `minSize`에 대한 네이밍을 조금 더 구체적으로 바꾼다면, 가독성이 더 좋아질 것 같아요~~!~!

2024-10-19 09:21 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +        }
흠 그러면 controller의 parameter 단에서 `validation` 라이브러리를 통해 검증하는건 어떨까요?

2024-10-19 09:22 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +                .ifPresent(mergedSchedules::add);
Early Return을 하는 것과 가독성을 고민하였는데요. 
아래가 더 가독성이 좋아보이네요 :)

2024-10-19 09:22 UTC, ikjo39 commented on backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
> +        );
이 작업은 리팩토링 이슈로 분리하여 다뤄봐도 좋을 것 같네요

2024-10-19 10:14 UTC, ikjo39 commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleControllerDocs.java
> +            @RequestParam @Schema(description = "추천 기준(이른 시간 순 / 길게 볼 수 있는 순 / 최소 시간 보장 순)", example = "earliest")
함께 결정하고 싶었던 사안이라 우선 구현이 잘 보이는 분리된 추천으로 시작하였는데요.
스크럼에서 얘기 나눈대로 이 부분은 최소 시간 보장의 옵션으로 수정하도록 할게요!

2024-10-19 10:14 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/RecommendedScheduleSortStandard.java
> +    MIN_TIME_EARLIER_ORDER("minTime", new EarliestFirstSorter())
스크럼에서 얘기 나눴듯이 옵션으로 통일하겠습니다!

2024-10-19 10:15 UTC, ikjo39 commented on backend/src/main/java/kr/momo/controller/schedule/ScheduleControllerDocs.java
> +            int minTime
이 부분도 정책적인 사인이라 스크럼으로 얘기 나눴었죠.
시간 단위로 나누는 것으로 결론내었으니 반영해보도록 할게요!

2024-10-19 10:17 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +            List<CandidateSchedule> subList, List<CandidateSchedule> mergedSchedules, int minSize
오호 이 부분은 흥미롭네요.
일반적으로 사용되는 메서드 명명법을 참고할 만한 곳이 있으면 공유 요청 드려도 될까요?
추후 메서드  명명에 도움이 될 것 같습니다!

2024-10-19 10:18 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +        if (minSize > subList.size()) {
동의합니다!
재즈 리뷰에도 질문 남겼지만 그러면 controller의 parameter 단에서 validation 라이브러리를 통해 검증하는건 어떨까요?

2024-10-19 11:36 UTC, ikjo39 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/RecommendedScheduleSortStandard.java
> +    MIN_TIME_EARLIER_ORDER("minTime", new EarliestFirstSorter())
최소 시간 보장이 '빠르게 만나요'의 옵션으로 정책이 수정되면서 `MIN_TIME_EARLIER_ORDER`이 필요하지 않아 삭제하였습니다!

2024-10-19 11:38 UTC, ikjo39 commented on backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
> +                .queryParams("recommendType", EARLIEST_ORDER.getType(), "attendeeNames", attendee.name(), "minimumTime", 0)
반영하였습니다!

2024-10-20 07:15 UTC, seokmyungham commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +        }
비즈니스 정책에 해당한다고 생각해서 비즈니스 로직이 수행되는 위치에서 수행되어야 할 것 같아요.

2024-10-20 08:57 UTC, hw0603 commented on backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
> +            List<CandidateSchedule> subList, List<CandidateSchedule> mergedSchedules, int minSize
음.. 별도로 레퍼런스가 있다기보다는 보통 영문에서 `lt`, `lte`, `gt`, `gte` 와 같은 표기를 많이 사용해서 그게 자연스럽다고 느꼈던 것 같아요.

자바 계열에서는 JUnit의 검증 메서드 명명법을 참고하기는 합니다. 저 메서드 보자마자 JUnit의 `greaterThanOrEqualTo()` 가 떠올랐어요ㅋㅋㅋ

2024-10-27 06:48 UTC, seokmyungham approved these changes

2024-10-28 03:45 UTC, hw0603 approved these changes
🚀

2024-11-01 05:27 UTC, seunghye218 approved these changes
👍👍

2024-11-05 14:19 UTC, ehBeak approved these changes
고생 많으셨어요~!~!~!~!~~!!!~!!~!~!~!~!~!!~!🚀🚀

2024-11-06 06:42 UTC, merged