[FE] 헤더 뒤로가기 기능 구현
woowacourse-teams/2024-momo pull request #411
Opened 2024-10-16 15:23 UTC by Largopie

## 관련 이슈

- resolves: #394 

## 작업 내용

> 사진으로 자세히 보고 싶거나, 구현 내용을 자세하게 파악하고 싶다면? -> [노션 링크 바로가기](https://paper-mass-5ff.notion.site/8e55c81023334a869c8779094ba5f595?pvs=4)

### 각 페이지 별 헤더 사용처

|                            | 뒤로가기 이동 경로                                       | 제목(title)      |
| -------------------------- | -------------------------------------------------------- | ---------------- |
| 랜딩 페이지                | ❌                                                       | ❌               |
| 약속 생성 페이지           | → 첫 페이지라면 랜딩 페이지 <br /> → 퍼널 패턴 이전 단계 | "약속 만들기"    |
| 약속 생성 완료/공유 페이지 | ❌                                                       | "약속 공유하기"  |
| 약속 입장 페이지           | → 약속 생성 완료 페이지로 이동할까요?                    | "약속 입장하기"  |
| 로그인 페이지              | → 약속 입장 페이지                                       | "로그인"         |
| 약속 조회 페이지           | → 약속 입장 페이지                                       | "약속 현황 조회" |
| 약속 등록 페이지           | → 약속 입장 페이지                                       | "약속 등록하기"  |
| 약속 수정 페이지           | → 약속 조회 페이지                                       | "약속 변경하기"  |
| 약속 추천 페이지           | → 약속 조회 페이지                                       | "약속 추천받기"  |
| 약속 추천 페이지(주최자)           | → 약속 조회 페이지                                       | "약속 확정하기"  |
| 약속 확정 페이지           | ❌                                                       | "확정된 약속"    |
| 에러 페이지                | ❌                                                       | ❌               |
| Not Found 페이지           | ❌                                                       | ❌               |

## 특이 사항

## 리뷰 요구사항 (선택)

2024-10-18 08:35 UTC, Yoonkyoungme requested changes
드디어 뒤로가기 기능이 생기는군요!!!!!!!!
고생하셨습니다 낙타
특히 백로그를 잘 작성해 주셔서 어떤 고민들을 했는지 쉽게 확인할 수 있었습니다👍🍑

<br />

**[C]**
router 처리 과정에서 제가 고민해본 방법을 공유할게요 :)
어제 디스코드에서 간단히 이야기 나눈 부분이지만, PR에도 기록으로 남기면 좋을 것 같아서 다시 언급해요!

Header가 필요한 페이지와 Header가 필요 없는 페이지를 구분하기 위해 GlobalLayout에서 조건부로 헤더를 렌더링하는 방법을 고민해봤습니다. 아래와 같이 useLocation을 활용한 방식은 페이지별로 유동적으로 헤더를 제어할 수 있어서 좋다고 생각합니다.

```tsx
const location = useLocation();

// 헤더를 보여줄 경로들 ex
const HEADER_ROUTES = [
  '/meeting/create',
  '/meeting/:uuid/register',
  '/meeting/:uuid/viewer',
];

// 현재 경로가 헤더를 보여줄 경로들에 속하는지 확인
const showHeader = HEADER_ROUTES.some(route => location.pathname.startsWith(route));
```
이 방식을 사용하면, 특정 경로에 따라 헤더를 보여주거나 숨기는 처리가 가능해서 각 페이지별로 UI를 유연하게 제어할 수 있을 것 같아요. 특히 meeting 관련 페이지들에서 경로가 복잡해질 때, 이런 식으로 관리하면 유지보수도 쉬울 것으로 생각됩니다!

**[Q]**
위 제안에 대한 낙타의 의견이 궁금합니다💭

2024-10-18 08:35 UTC, Yoonkyoungme commented on frontend/src/mocks/meeting/meetingHandlers.ts
> +    if (!currentMeetingType) return HttpResponse.json(meetingEntranceDateTimeInfo, { status: 200 });
[P3]

굿👍

```suggestion
http.get(`${BASE_URL}/:uuid/home`, () => {
  if (!currentMeetingType || currentMeetingType === 'DATETIME') {
    return HttpResponse.json(meetingEntranceDateTimeInfo, { status: 200 });
  } else if (currentMeetingType === 'DAYSONLY') {
    return HttpResponse.json(meetingEntranceDaysOnlyInfo, { status: 200 });
  }
}),

```

2024-10-18 08:42 UTC, hwinkr requested changes
고생하셨습니다! 낙타~
 
저희 서비스가 언제 이렇게 페이지들이 많아졌는지 모르겠는데, 헤더에 페이지별로 고민한 흔적이 인상깊네요. 특히 노션에 정리해 놓은 것을 보니 리뷰하기 편했습니다.

사소한 변경 사항을 요청드리려고 합니다~ 나중에 다시 봐용 ㅎ

2024-10-18 08:42 UTC, hwinkr commented on frontend/src/pages/AttendeeLoginPage/index.tsx
> +        </button>
**[P2]**

로그인 페이지가 입장 페이지에서만 사용된다면, 뒤로가기 버튼을 클릭했을 때, 

```ts
routerTo(-1)
```

로 호출해 주면 되지 않을까요? useRouter 커스텀 훅 내부에서 뒤로가기 함수도 제공해 주면 될 것 같은데 어떻게 생각하시나요?

2024-10-18 08:42 UTC, hwinkr commented on frontend/src/pages/AttendeeLoginPage/index.tsx
> +        </button>
와 근데 저랑 충돌 심하게 나겠네요...

2024-10-18 08:42 UTC, hwinkr commented on frontend/src/pages/CreateMeetingPage/index.tsx
> +        </button>
**[P2]**

```tsx
<button css={s_backButton} onClick={() => navigate(-1)}>
    <BackSVG width="24" height="24" />
</button>
```
-> 
```tsx
<BackButton />
```
뒤로 이동 시키는 버튼 컴포넌트를 추상화해 보는 것은 어떨까요??

2024-10-18 08:42 UTC, hwinkr commented on frontend/src/mocks/meeting/meetingHandlers.ts
> +    if (!currentMeetingType) return HttpResponse.json(meetingEntranceDateTimeInfo, { status: 200 });
굿

2024-10-20 17:39 UTC, Largopie reviewed
@hwinkr @Yoonkyoungme 

리뷰 반영사항 반영하고 다시 요청합니다~!
변경된 자세한 사항은 노션 하단에 [해빙 리뷰 후 반영사항](https://paper-mass-5ff.notion.site/8e55c81023334a869c8779094ba5f595?pvs=4) 에서 확인할 수 있습니다.

## uuid 반환 로직 Context API & Layout 구성

```jsx
// UuidProvider.tsx
export const UuidContext = createContext<UuidState>({} as UuidState);

export default function UuidProvider({ children }: PropsWithChildren) {
  const { uuid } = useParams();

  return <UuidContext.Provider value={{ uuid: uuid ?? '' }}>{children}</UuidContext.Provider>;
}
```

```jsx
// UuidLayout.tsx
export default function UuidLayout() {
  return (
    <UuidProvider>
      <Outlet />
    </UuidProvider>
  );
}

// router.tsx

{
    path: ':uuid',
    element: <UuidLayout />,
    children: [
    // ...
```

## BackButton 컴포넌트 추상화

위와 같이 버튼 컴포넌트를 추상화하고 반영했습니다. 여기서 더 이상 "약속 변경하기" 즉, 약속 수정 모드에서는 뒤로 가기 기능을 사용할 수 없습니다.(이유는 노션에 자세히 기록해두었습니다.)

```tsx
interface BackButtonProps {
  path?: string;
}

export default function BackButton({ path }: BackButtonProps) {
  const { routeTo, goBack } = useRouter();

  const handleBackButtonClick = () => {
    if (path === undefined) goBack();
    else routeTo(path);
  };

  return (
    <button css={s_backButton} onClick={handleBackButtonClick}>
      <BackSVG width="24" height="24" />
    </button>
  );
}
```

![image](https://github.com/user-attachments/assets/e1c24404-0457-49be-9566-58ca1eb59982)

2024-10-20 18:04 UTC, Yoonkyoungme commented on frontend/src/hooks/useRouter/useRouter.ts
useRouter에서 router to 함수가 useNavigate 로 경로 이동하는 함수자나

그러면 지금 코드 내에서도
```
const navigate = useNavigate();
 <button onClick={() => navigate("/"}></button>
```

이렇게 이동하는 방식과

낙타가 만들어준 useRouger의 routerTo 함수 사용하는 방식이 혼용되어서 쓰이는건가여?
```
 const { routeTo } = useRouter();
<button onClick={() => routeTo(`/meeting/${uuid}`)}></button>
```

그런 관점에서 같은 기능을 하는거라면 굳이 useNavigate 하는거를 별도의 훅 함수로 뺄 필요가 없다고 생각했습니다

2024-10-20 18:35 UTC, Yoonkyoungme commented on frontend/src/hooks/useRouter/useRouter.ts
> +const useRouter = () => {
좋습니다🎈🎈

2024-10-21 04:47 UTC, Largopie commented
https://github.com/woowacourse-teams/2024-momo/pull/411#pullrequestreview-2376622314

@Yoonkyoungme 좋은 질문 남겨주셔서 감사합니다 :)

[Q]
> 경로 배열 선언 후 Header 라우팅처대한 낙타의 의견이 궁금합니다💭

변경사항에 대한 유연한 대처가 어렵다고 생각이 들었습니다.

지금 당장 헤더에 필요한 기능은 뒤로가기, 공유하기 버튼만 존재합니다. 그렇다면 뒤로가기 버튼, 공유하기 버튼을 보여줄 지 고민하는 상태가 필요합니다.(ex. isShareButton, isBackButton)

하지만 나중에 기능 추가(예를 들어 특정 페이지에서 메뉴 네비게이션 바 버튼 기능 추가) 되었을 때 마다 해당 버튼을 보여줄지 말지 여부를 판단하는 상태가 필요하며, 해당 상태를 헤더에 props로 내려줘야 하는 상황이 생길 것 같았어요.
따라서 각 페이지에 동작하는 기능 중 하나라고 생각하고 페이지마다 Header를 배치하는 것이 더 좋다고 판단이 들어서 위와 같이 구현하게 되었습니다.

2024-10-21 04:51 UTC, hwinkr commented on frontend/src/assets/images/attendeeCheck.svg
그 방법도 좋네요!

2024-10-21 05:01 UTC, hwinkr approved these changes
안정적인 뒤로가기 기능을 제공하기 위해서 열심히 코드를 작성하셨네요 낙타!  

정말 고생하셨습니다~ 빙봉과 티키타카 코드 리뷰 정말 인상적이네요. 모모 서비스에서 중심이 되는 기능을 개발하는 PR에는 코멘트가 기본적으로 30개는 달리는 것 같네요...ㅋㅋ~  

드디어 뒤로가기 기능이 생겼다니 백엔드 모모들이 정말 좋아할 것 같네요! 고생 많았어요~ 🐫

2024-10-21 05:05 UTC, Yoonkyoungme approved these changes
🐫 낙타 🐪 고생하셨습니다!!!!!! 코드 만 줄의 변경이라니~~~~ 엄청나군요
의견 교환하는 과정 재미있었습니다 ㅎㅅㅎ
다음은 웹 접근성 함께 작업하러 가시죠!

2024-10-21 05:17 UTC, merged