[FE] 프로젝트의 기본 폰트를 Spoqa Han Sans Neo로 설정
woowacourse-teams/2024-momo pull request #47
Opened 2024-07-22 06:35 UTC by Yoonkyoungme

## 관련 이슈

- resolves: #46

## 작업 내용

- 각 폰트 스타일에 대해 `.woff2` 파일을 추가하였습니다.
- `@font-face` 규칙을 사용하여 'Spoqa Han Sans Neo' 폰트 패밀리를 정의하였습니다.
  - Thin (100 weight)
  - Light (300 weight)
  - Regular (400 weight)
  - Medium (500 weight)
  - Bold (700 weight)

- 결과 (쉽게 결과 비교를 하기 위해서 사파리 브라우저 테스트 사진을 첨부합니다.)
  - 폰트 적용 전
    <img width="398" alt="image" src="https://github.com/user-attachments/assets/a4e780c2-e166-43f0-a581-8e6e0181b087">

  - 폰트 적용 후
    <img width="337" alt="image" src="https://github.com/user-attachments/assets/ae39aabe-9be7-4f5a-b511-15ec11919905">

## 특이 사항

## 리뷰 요구사항 (선택)

해당 작업과 관련된 내용을 notion에 기록해 보았습니다. [notion 링크](https://paper-mass-5ff.notion.site/font-2bdd90139f1a485cbff8e046bb1469f9?pvs=4)

2024-07-22 13:50 UTC, Largopie requested changes
빙봉! 에러 해결하느라 고생하셨습니다! 👊

오늘도 노션에 잘 작성된 글을 보고 이해하기 훨씬 수월했습니다.
woff를 woff2보다는 압축률이 낮지만 모든 브라우저에 호환되기 때문에 사용하신건가보네요!

커밋단위가 작아서 리뷰하기도 훨씬 수월한 것 같네요.. 저도 앞으로는 이렇게 작게 쪼개서 PR보내는 습관을 들여야겠어요..

질문 사항 몇 가지 남겨두었으니 확인해주세용!!

2024-07-22 13:50 UTC, Largopie commented on frontend/src/styles/fonts.ts
[P1] 현재 모든 `@font-face`에 정의된 `font-family`명이 똑같은 것으로 확인되었습니다. 따라서 가장 마지막에 적용한 `@font-face`로 해당 이름을 사용하면 적용이 된 것 같은데` font-family`명을 수정해야 하지 않을까 싶네요!
이것도 컨벤션으로 아마 맞춰야하지 않을까 싶습니다! 예를들어, spoque-100, spoque-300, ... 이런 식으로요!


[Q](진짜 몰라서 하는 질문)
또한, 각각 `font-weight`를 지정해줄 수 있는데 여러 종류의 폰트를 사용하신 이유가 있을까요?!

2024-07-22 13:50 UTC, Largopie commented on frontend/src/styles/global.ts
> +    font-family: 'Spoqa Han Sans Neo', sans-serif;
[Q]
제 육안상으로 확인했을 때, sans-serif를 붙였을 때와 붙이지 않았을 때의 차이가 없어 보이는데 뒤에 붙여주신 이유가 있을까요?!

2024-07-23 04:43 UTC, Yoonkyoungme reviewed
@Largopie 낙타🐪 코멘트에 대한 답변 달아두었습니다~!

2024-07-23 04:43 UTC, Yoonkyoungme commented on frontend/src/styles/fonts.ts
어제 게더에서 같이 확인해봤지만, 정리된 글로 기록을 남겨둘게요!

### 1. `font-family` 명칭

우선, 각 `@font-face`에 동일한 `font-family`명을 사용하는 이유는 여러 `font-weight`와 `font-style`을 한 폰트 패밀리 내에서 정의하기 위함입니다. (CSS의 일반적인 관례이며, 브라우저가 폰트를 선택하는 표준 방법)

아래와 같이 동일한 `font-family` 명칭을 사용하면서 `font-weight`를 다르게 설정하면, CSS에서 이 폰트 패밀리를 사용하는 모든 요소가 해당 `font-weight`에 맞는 글꼴을 자동으로 사용하게 됩니다.

```css
body {
  font-family: 'Spoqa Han Sans Neo', sans-serif;
  font-weight: 400; /* Regular weight */
}

h1 {
  font-family: 'Spoqa Han Sans Neo', sans-serif;
  font-weight: 700; /* Bold weight */
}
```

만약 각 `@font-face`에 대해 다른 `font-family`명을 사용한다면, CSS에서 각기 다른 글꼴명을 지정해야 하고, 이는 관리와 사용이 더 복잡해질 수 있습니다.

### 2. 여러 종류의 폰트 사용 이유

여러 종류의 폰트를 사용하는 이유는 텍스트의 가독성을 높이고 다양한 디자인 요구를 충족시키기 위함입니다.
각 폰트의 `font-weight`를 다르게 정의함으로써, 한 폰트 패밀리 내에서 다양한 굵기를 사용할 수 있습니다.

2024-07-23 05:07 UTC, hwinkr approved these changes
빙봉뱅봉~

ㅋ

2024-07-23 05:07 UTC, hwinkr commented on frontend/src/styles/fonts.ts
> +    src: url(${require('../assets/fonts/SpoqaHanSansNeo-Thin.woff2')}) format('woff2');
이전에 프로젝트에서 웹 폰트를 적용했을 때 저희와 같은 문제가 발생했었는데 문자열을 인식하지 못해서 생겼던 것이였군요...😭  

빙봉 덕분에 꿀팁 알아갑니다~

2024-07-23 05:12 UTC, Largopie commented on frontend/src/styles/fonts.ts
완저어어언히 이해됐습니다! 👍👍👍👍

2024-07-23 05:14 UTC, Largopie commented on frontend/src/styles/global.ts
> +    font-family: 'Spoqa Han Sans Neo', sans-serif;
브라우저에서 `Spoqua Han Sans Neo` 글꼴 자체가 호환되지 않을 경우를 대비해서 `sans-serif`를 사용하신 것으로 이해했습니다! 좋아요 👍

2024-07-23 05:15 UTC, Largopie approved these changes
답변 감사합니다 :) 완벽하게 이해 됐어요! 친절한 설명 감사드립니다요!

2024-07-23 05:24 UTC, Yoonkyoungme commented on frontend/src/styles/global.ts
> +    font-family: 'Spoqa Han Sans Neo', sans-serif;
사파리 브라우저의 경우 기본으로 `AppleMyungjo`(명조체, serif)를 사용하고 있기 때문에 폰트를 설정해주지 않으면, 아래 사진처럼 보입니다. 우리 서비스에서 사용하는 폰트는 `sans-serif` 계열이기에 `sans-serif`를 명시해 두었습니다☺️
![image](https://github.com/user-attachments/assets/ddd711a2-038f-47e0-8d99-9f532e8f4978)

아래 글 내용이 너무 좋네요👏👏 시간 되실 때 읽어보는 거 추천합니다~~
https://velog.io/@seop/Safari사파리-에서-폰트가-이상하게-보일경우-해결법-CSS-font-family-속성-총정리

2024-07-23 05:29 UTC, merged