[BE] 약속 생성 결과 조회 API 구현
woowacourse-teams/2024-momo pull request #52
Opened 2024-07-23 05:50 UTC by ikjo39

## 관련 이슈

- resolves: #50 

## 작업 내용

- 참가자용 테스트 fixture 추가
- 약속 생성 결과 조회 로직 추가
- 관련된 테스트 추가

## 특이 사항

## 리뷰 요구사항 (선택)

> 리뷰 중점 사항: 리뷰어가 특히 집중해서 봐야 할 부분이 있나요?

- 코드 컨벤션이 전체적으로 적용되었는지
- 메서드 이름이 적절하였는지 부탁드립니당

2024-07-23 11:42 UTC, seokmyungham requested changes
다온 고생하셨어요 🤗
전체적으로 코드가 깔끔하네요~
메서드 이름만 조금 뭔가뭔가...한데.. 이름을 뭐로 해야할지 고민하면 좋겠습니다 ㅎㅎ

2024-07-23 11:42 UTC, seokmyungham commented on backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
> +        MeetingCompletedResponse response = meetingService.findCompleted(uuid);
컨트롤러, 서비스 메서드 명을 `Completed` 라는 단어보다는 `Created`나 `Generated`는 어떤가요?
Complete는 뭔가 약속이 최종 완료된 느낌이 드는 것 같아요.

2024-07-24 01:01 UTC, ikjo39 commented on backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingCompletedResponse.java
> +    }
`MeetingSharingResponse`으로 변경해보았습니다 :)

2024-07-24 03:04 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingCompletedResponse.java
> +    }
좋네요~👍

2024-07-24 03:05 UTC, ehBeak submitted a review, later dismissed

2024-07-24 03:16 UTC, hw0603 requested changes
몇가지 리뷰 남겨드렸습니다😎

2024-07-24 03:16 UTC, hw0603 commented on backend/src/main/java/com/woowacourse/momo/exception/code/AttendeeErrorCode.java
> +    INVALID_ACCESS(HttpStatus.BAD_REQUEST, "유효하지 않는 접근입니다. 관리자에게 문의해주세요.");
유효하지 '않은' 접근이 좀 더 자연스럽게 읽히는 것 같아요!

2024-07-24 03:16 UTC, hw0603 commented on backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
> +@Slf4j
어노테이션은 붙어 있는데 로깅하는 곳이 없는 것 같아요🧐

2024-07-24 03:16 UTC, hw0603 commented on backend/src/test/java/com/woowacourse/momo/fixture/AttendeeFixture.java
Enum 픽스쳐 기가 막히네요👍🏻

2024-07-24 05:15 UTC, ikjo39 commented on backend/src/main/java/com/woowacourse/momo/exception/code/AttendeeErrorCode.java
> +    INVALID_ACCESS(HttpStatus.BAD_REQUEST, "유효하지 않는 접근입니다. 관리자에게 문의해주세요.");
ENUM 명을 신경쓰지 못했네요!
수정하려 했지만 다시 보니 해당 Enum 값은 사용하고 있지 않아 삭제하였습니다!

2024-07-24 05:19 UTC, ehBeak approved these changes

2024-07-24 05:20 UTC, seokmyungham approved these changes

2024-07-24 05:21 UTC, hw0603 approved these changes

2024-07-24 05:24 UTC, seunghye218 approved these changes
픽스쳐 활용이 좋네요. 테스트 작성할 때 참고할게요 👍

2024-07-24 05:26 UTC, merged