[BE] 약속 생성 API 구현
woowacourse-teams/2024-momo pull request #56
Opened 2024-07-23 10:11 UTC by ehBeak

## 관련 이슈

- resolves: #51 

## 작업 내용

약속을 생성하는 기능을 구현합니다.

로직은 아래와 같은 순서로 동작합니다.
* 주최자를 참여자로 등록(회원가입)합니다.
* 약속 허용날짜(avilableDates)를 저장합니다.
* 약속(Meeting)을 저장합니다.

요청
```http
POST /api/v1/meeting HTTP/1.1

{
    "hostName": "momo_host",
    "hostPassword": "momo_password",
    "meetingName": "momo_meeting",
    "meetingAttendeeLimit": "5",
    "meetingAvailableDates": [
        "2024-07-20",
        "2024-07-21",
        "2024-07-22"
    ],
    "meetingStartTime": "8:00",
    "meetingEndTime": "22:00"
}
```

응답
```http
HTTP/1.1 201 Created
Location: /meeting/{uuid}
```

## 특이 사항

1. PRG(Post-Redirect-Get)의 필요성
구현한 약속 생성 API는 아래와 같은 로직입니다.
>     (1) 약속 생성 등록 페이지에서 등록 버튼을 누르면 POST 요청
>     (2) 정보 페이지로 이동하면서 응답받은 값을 정보 페이지에 뿌려줌
그러나 이렇게 구현하면 사용자가 새로고침을 할 경우 POST 재요청되고, 또 다른 Meeting이 생성될 것으로 예상됩니다.
만약 예상한 대로 동작한다면, 리다이렉트하여 새로고침 시 GET 요청이 가도록 수정할 예정입니다.

2. UUID 라이브러리
UUID 버전은 사전에 논의한 내용과 아래 자료를 참고하여 v4로 선택했습니다.
[baeldung-java-uuid](https://www.baeldung.com/java-uuid)
[which-uuid-version-to-use](https://stackoverflow.com/questions/20342058/which-uuid-version-to-use)

## 리뷰 요구사항 (선택)

1. 약속 허용 날짜가 중복되었는지 검증하는 로직 위치
날짜(ex. `2023-07-01`)가 중복으로 2번 들어갔는지 확인하는 검증하는 로직(`validateDuplicatedDates`)을 `MeetingService`에 두었는데 적절한 위치인지 고민됩니다.
`request`나 `domain`에서 검증해야 할 것 같은데, 보통 어떻게 하시나요?

2. 생성된 `Meeting`의 uuid를 클라이언트에게 제공하는 방식
구현한 API는 생성된 `Meeting`의 `uuid`를 `Location`헤더를 통해 제공됩니다. 이것이 적절한 방식인지 의견을 나누고 싶어요!
이미 `Location` 헤더에 이미 존재하는데, 응답 바디를 통해 `uuid`를 따로 제공하는 것이 중복이라 생각하여 응답 바디를 따로 두지 않았습니다.
그러나 `Location`의 역할은 생성된 리소스의 위치를 알려주는 것이지 `uuid`라는 식별자를 알려주는 것이 아닌 것 같아서 고민이 됩니다 🤔

2024-07-23 12:29 UTC, ikjo39 reviewed
고생하셨어요 배키!!
몇가지 코멘트 남겨보았으니 확인 부탁드립니다 😄

2024-07-23 12:29 UTC, ikjo39 commented on backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
> +    }
팀원들끼리 이미 얘기를 나눠보았듯이
필요할 때는 `ResponseEntity` 객체를 사용해 보는 것이 더 가독성이 좋아질 것 같아요!

2024-07-23 12:29 UTC, ikjo39 commented on backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingCreateRequest.java
> +        LocalTime meetingEndTime
다른 파라미터들에는 검증을 안 넣은 이유가 궁금해요 :)

2024-07-23 12:29 UTC, ikjo39 commented on backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
> +        assertThat(attendee).extracting("role").isEqualTo(Role.HOST);
`extracting()`메서드는 자바 리플랙션을 이용하여 동일한 이름의 필드로 직접 접근하는데요.
만약 `role`이라는 필드명이 변경될 경우 컴파일 시점에 에러를 잡아주지 못할 것 같아요!
getter로 변경하여 컴파일 시점에 오류를 잡아주는건 어떨까요?
```suggestion
        assertThat(attendee.getRole()).isEqualTo(Role.HOST);
```

2024-07-23 12:29 UTC, ikjo39 commented on backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
> +        //then
`//when`에 해당하는 메서드가 없어 해당 주석으로 인해 불필요한 줄바꿈이 있어보여요!
아래처럼 하나로 합쳐 나타내보는건 어떨까요?
불필요한 줄바꿈을 줄일 수 있을 것 같아요!
```suggestion

        //when //then
```

2024-07-23 12:29 UTC, ikjo39 commented on backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
> +    }
메서드 체인으로 보여 아래처럼 줄바꿈이 필요해 보입니다!
```suggestion
        assertThatThrownBy(() -> meetingService.create(request))
                .isInstanceOf(MomoException.class);
    }
```

2024-07-23 12:30 UTC, seokmyungham requested changes
배키 고생하셨습니다.
몇가지 수정했으면 하는 부분이 있는데 확인 부탁드려요~ 😊

> 구현한 API는 생성된 Meeting의 uuid를 Location헤더를 통해 제공됩니다. 이것이 적절한 방식인지 의견을 나누고 싶어요!
이미 Location 헤더에 이미 존재하는데, 응답 바디를 통해 uuid를 따로 제공하는 것이 중복이라 생각하여 응답 바디를 따로 두지 않았습니다.

그리고 이 부분은 프론트엔드와 같이 얘기해보면 좋을 것 같네요.

2024-07-23 12:30 UTC, seokmyungham commented on backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
> +                .toList();
`AvailableDate`에 대한 일급컬렉션에 책임을 위임할 수 있을 것 같아요.

2024-07-23 12:30 UTC, seokmyungham commented on backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
> +        attendeeRepository.save(new Attendee(savedMeeting, request.hostName(), request.hostPassword(), Role.HOST));
개인적인 생각인데, 객체를 메서드 밖에서 생성하면 가독성에 더 좋을 것 같아요 ㅎㅎ

2024-07-23 12:30 UTC, seokmyungham commented on backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
> +        response.addHeader(HttpHeaders.LOCATION, "/meeting/" + uuid);
앗 ㅋㅋ 
응답 HTTP의 여러 요소들을 다뤄야 할 때는, 스프링이 제공하는 `ResponseEntity`를 사용하는 게 더 나을 것 같네요

2024-07-24 04:25 UTC, seunghye218 requested changes
다른 리뷰어들이 짚어준 부분을 제외하면 좋아보이네요. 그 부분들만 수정하면 될것같아요~!

2024-07-24 05:27 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDate.java
> +    }
`@AllArgsConstructor`어노테이션이 있는 걸 인지하지 못했네요..! 반영했습니다~

2024-07-24 05:35 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
> +    }
네 좋습니다~!
추가로, `ResponseEnitiy`에서 `httpStatus`도 수정할 수 있기 때문에 `@ResponseStatus`도 삭제했습니다!

2024-07-24 05:37 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingCreateRequest.java
> +        LocalTime meetingEndTime
앗 실수했네요..🥲 추가했습니다!

2024-07-24 05:55 UTC, ehBeak commented on backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
> +        assertThat(attendee).extracting("role").isEqualTo(Role.HOST);
오 그건 처음 알았네요! 반영하겠습니다👍

2024-07-24 05:57 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
> +        );
헉..😢 그렇네요! 이래서 리뷰가 필요하군요..ㅎ

2024-07-24 06:00 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
> +        response.addHeader(HttpHeaders.LOCATION, "/meeting/" + uuid);
넵 `@ResponseStauts`도 빼고 `ResponseEntity`에서 status까지 해결하도록 수정했습니다~!

2024-07-24 06:15 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
> +                .toList();
넵 수정했습니다! 뭔가 익숙하지 않아서 다시 한번 확인 부탁드려요😊

2024-07-24 07:27 UTC, ehBeak commented
약속을 생성할 때, `firstTimeslot`이 `lastTimeslot`보다 이전이거나 같은지 확인하는 검증 로직 추가했습니다. 확인 부탁드립니다!

2024-07-24 07:36 UTC, ikjo39 reviewed
진짜 찐찐찐막입니다!

2024-07-24 07:43 UTC, ehBeak commented on backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
> +        return ResponseEntity.created(URI.create("/meeting/" + uuid)).build();
아악.. 그렇네요🥲 수정하겠습니다!

2024-07-24 08:24 UTC, ikjo39 submitted a review, later dismissed

2024-07-24 08:25 UTC, hw0603 submitted a review, later dismissed
고생하셨습니다 👍

2024-07-24 08:39 UTC, seokmyungham requested changes
배키 고생하셨어요 😄
조금 더 개선할 수 있을 것 같아서 한 번 더 Request Change 드려요!

2024-07-24 08:39 UTC, seokmyungham commented on backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDates.java
> +
좋아요 👍

2024-07-24 08:39 UTC, seokmyungham commented on backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
> +        );
(`Meeting 생성과 저장`) (`Attendee 생성과 저장`)
맥락을 나눠서 메서드를 분리하면 더 가독성이 좋을 것 같아요. 😊

최대한 한 메서드가 하나의 책임만 갖도록 해봅시다!

2024-07-24 10:16 UTC, seokmyungham requested changes

2024-07-24 10:16 UTC, seokmyungham commented on backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
> +            throw new MomoException(MeetingErrorCode.INVALID_TIME_RANGE);
부정 연산자는 가급적 조건문에 안썼으면 좋겠어요 😥

2024-07-24 10:29 UTC, seunghye218 approved these changes

2024-07-24 11:05 UTC, ikjo39 approved these changes

2024-07-24 11:14 UTC, hw0603 approved these changes
고생하셨습니다👍

2024-07-24 11:16 UTC, merged