[FE] 헤더 컴포넌트 구현
woowacourse-teams/2024-momo pull request #63
Opened 2024-07-24 05:34 UTC by Largopie

## 관련 이슈

- resolves: #54 

## 작업 내용

 - [x] 헤더 컴포넌트 구현

## 특이 사항

- 당일 오전에 정한 css prop 네이밍 컨벤션에 맞추었습니다.
- 스토리북도 추가로 연결할 예정이였지만, 아래와 같은 오류 발생 및 시간 관계상 추후에 작업해야할 것 같습니다.

```
Failed to execute 'createElement' on 'Document': The tag name provided ('static/media/src/assets/images/menu.svg') is not a valid name.
````

## 리뷰 요구사항 (선택)

2024-07-24 13:30 UTC, Yoonkyoungme submitted a review, later dismissed
낙타 빠르게 작업해 주셨네요! 깔끔 합니다~~~🎨 사소한 코멘트 달아두었습니다!!
스토리북에서 svg 에러나는거 같이 해결 방법 찾아봅시다!

2024-07-24 13:35 UTC, Largopie commented on frontend/src/components/_common/Header/Header.styles.ts
> +`;
앗, 수정해야겠네요! 알려줘서 고마워요 빙봉~

2024-07-24 13:40 UTC, Yoonkyoungme submitted a review, later dismissed
굿굿 좋습니다⭐️

2024-07-24 14:39 UTC, hwinkr requested changes
헤더 만드느라 고생하셨습니다 낙타~ 🐪

2024-07-24 14:39 UTC, hwinkr commented on frontend/src/layouts/GlobalLayout.styles.ts
> +  padding: 1.6rem;
피그마 시안에는 양 옆 패딩만 `1.6rem` 으로 되어있는데, 해당 속성은 상하좌우 모두 패딩을 주게될 것 같아요!

2024-07-24 16:36 UTC, Largopie commented on frontend/src/layouts/GlobalLayout.styles.ts
> +  padding: 1.6rem;
앗차차 이 부분 수정해서 반영하겠습니다 감사합니다 해리~!

2024-07-24 16:57 UTC, hwinkr approved these changes
🐪👏

2024-07-25 01:46 UTC, Yoonkyoungme approved these changes

2024-07-25 01:54 UTC, Yoonkyoungme approved these changes

2024-07-25 02:08 UTC, hwinkr approved these changes

2024-07-25 02:16 UTC, hwinkr approved these changes

2024-07-25 02:17 UTC, Yoonkyoungme approved these changes

2024-07-25 02:17 UTC, merged