[FE] Input, Field 컴포넌트 구현
woowacourse-teams/2024-momo pull request #64
Opened 2024-07-24 06:50 UTC by Yoonkyoungme

## 관련 이슈

- resolves: #61 

## 작업 내용

- Input
  - Input 컴포넌트 구현
  - Input 스토리북 작성

- Field 
  - Field 컴포넌트 구현
  - Field 스토리북 작성

## 특이 사항

스토리북에서 한국어로 작성된 예제들을 포함하였으며, 각 컴포넌트의 다양한 상태를 확인할 수 있습니다.

## 리뷰 요구사항 (선택)

2024-07-24 11:10 UTC, Largopie requested changes
빠르게 구현해주셨네요! 고생하셨습니다 빙봉! 역시 빙봉!

코멘트 몇개 남겨두었는데 확인 후 다시 요청해주세요! 🐫

2024-07-24 11:10 UTC, Largopie commented on frontend/src/hooks/useInput/useInput.ts
> +import { ChangeEvent, useState } from 'react';
[P1] ChangeEvent는 type으로 import 명시해주어야 할 것 같아요! 👀

2024-07-24 11:10 UTC, Largopie commented on frontend/src/components/_common/Field/index.tsx
> +export default function Field({ label, description = '', inputProps }: FieldProps) {
[P3] `label`이라는 prop 이름이 htmlFor과 input의 id를 명시한다는 것이 제가 느끼기엔 이해하기 조금 어려운 것 같아요!
label보다는 직접적으로 id라고 명시하는 것은 어떨까요?

2024-07-24 11:10 UTC, Largopie commented on frontend/src/components/_common/Input/Input.styles.ts
> +  box-sizing: border-box;
[P2]
해당 속성도 전역 GlobalStyle에 정의되어 있어서 제외하셔도 좋을 것 같습니다!

2024-07-24 11:10 UTC, Largopie commented on frontend/src/components/_common/Field/index.tsx
> +export default function Field({ label, description = '', inputProps }: FieldProps) {
[P3]

```suggestion
interface FieldProps extends InputHTMLAttributes<HTMLInputElement> {
  label: string;
  description?: string;
}

export default function Field({ label, description = '', ...props }: FieldProps) {
```

이렇게 표현해볼 수도 있을 것 같습니다! 가벼운 제안입니다!

2024-07-24 14:53 UTC, hwinkr requested changes
빙봉 소소한 코멘트 남깁니다~

2024-07-24 14:53 UTC, hwinkr commented on frontend/src/components/_common/Input/Input.styles.ts
> +  width: 20rem;
[p2]

피그마 시안이랑 `width`가 다른 것 같아요! rem으로 정의해두는 것 보다 디바이스 크기에 따라 Input 컴포넌트가 차지하는 공간의 비율이 달리지게 될 것 같은데 100%으로 설정해두는게 어떨까요~?

2024-07-24 14:53 UTC, hwinkr commented on frontend/src/hooks/useInput/useInput.ts
> +  const handleValueChange = (event: ChangeEvent<HTMLInputElement>) => {
이벤트 핸들러 함수 컨벤션 잊지 않고 잘 챙기고 있군요~ 좋습니다!

2024-07-24 14:53 UTC, hwinkr commented on frontend/src/components/_common/Field/index.tsx
> +export default function Field({ label, description = '', inputProps }: FieldProps) {
[C]

아니면 현재 `label` props를 지우고 `InputHTMLAttributes<HTMLInputElement>`의 타입을 활용해서 id를 직접 내려준 다음 필요한 곳에 할당하는 것은 어떨까요~?

2024-07-24 17:27 UTC, Yoonkyoungme reviewed
@Largopie @hwinkr
낙타, 해리! 남겨주신 코멘트를 반영하였습니다🐫🍀 좋은 의견 공유 감사해요!

2024-07-24 17:27 UTC, Yoonkyoungme commented on frontend/src/hooks/useInput/useInput.ts
> +import { ChangeEvent, useState } from 'react';
앗 자동 import 하면서 놓쳤네요ㅜㅜ 꼼꼼히 확인해 주셔서 감사해요!! 반영하였습니다!

2024-07-24 17:27 UTC, Yoonkyoungme commented on frontend/src/components/_common/Input/Input.styles.ts
> +  width: 20rem;
좋은 의견이네요~!~! 반영하였습니다!

2024-07-24 17:27 UTC, Yoonkyoungme commented on frontend/src/components/_common/Field/index.tsx
> +export default function Field({ label, description = '', inputProps }: FieldProps) {
오옷!!! 낙타🐫 좋은 의견이네요! `InputHTMLAttributes`를 확장하는 것이 훨씬 깔끔한 것 같습니다. 반영하였습니다~

2024-07-24 17:27 UTC, Yoonkyoungme commented on frontend/src/components/_common/Field/index.tsx
> +export default function Field({ label, description = '', inputProps }: FieldProps) {
확실히 그러네요 label을 id, htmlFor 값으로 같이 사용하고 있어서 어색하게 느껴지는 것 같습니다🥹
낙타와 해리 코멘트를 확인하고 변경해 보았어요.

### 변경 사항
- `label` prop을 `labelText`로 변경 (해당 prop의 네이밍을 명확하게 하기 위함)
- `Field` 컴포넌트에서 `labelText`와 `id`를 명시적으로 받아서 `label`과 `Input`의 `id`에 적용하도록 수정

반영 커밋: ace237b3e41f79d66c1accf3d2baa076fb7c4b91

2024-07-24 17:34 UTC, hwinkr approved these changes
뱅뱅봉봉빙빙방방, 리뷰 반영하느라 고생했어요~ 🔮

2024-07-25 01:45 UTC, Largopie approved these changes
의견 반영 감사합니다 👍👍👍 💯💯💯

2024-07-25 01:52 UTC, merged