[FE]: 날짜를 선택할 수 있는 캘린더 UI 구현
woowacourse-teams/2024-momo pull request #68
Opened 2024-07-24 10:23 UTC by hwinkr

## 관련 이슈

- resolves: #60

## 작업 내용

- [ ] 달력 UI를 통해 약속 날짜들을 선택할 수 있도록 한다.
- [ ] 2024.07 부터 `>` 버튼을 클릭해서 다음 달로 이동할 수 있다, `<`를 클릭해서 이전 달로 돌아갈 수 있다. 
- [ ] 스토리북으로 달력 UI를 테스트한다.

## 특이 사항
### 컴포넌트 사용법

```tsx
export default function MeetingTimePickPage() {
  const [selectedDates, setSelectedDates] = useState<string[]>([]);

  const hasDate = (date: string) => selectedDates.includes(date);

  const handleDateClick = (date: string) => {
    setSelectedDates((prevDates) =>
      hasDate(date) ? prevDates.filter((d) => d !== date) : [...prevDates, date],
    );
  };

  return (
    <div>
      <Calendar hasDate={hasDate} onDateClick={handleDateClick} />
    </div>
  );
}
```

아래 props들을 주입한다.

- selectedDates: 선택된 날짜들의 배열 (string[], ['2024-07-12']
- hasDate: 해당 날짜가 selectedDates에 포함됐는지 확인하는 함수
=> `useCalendar` 과 같은 훅으로 분리할 수 있다.

### 2차 스프린트가 끝난 후 개선해야 하는 사항들  

- [ ]  오늘 기준 지난 날은 선택할 수 없도록 한다 (현재는 지난 달을 선택할 수 없도록 했음.)
- [ ]  실제 공휴일도 표시할 것 인지 결정
	- 자바스크립트 `Date` 객체로는 한국의 공휴일을 판단할 수 없음.
	- 한국 공휴일을 찾아주는 라이브러리가 있다고 함. 
	- 참고 : https://github.com/hyunbinseo/holidays-kr
- [ ]  isToday 변수로 확인할 수 있듯, ‘오늘’을 어떻게 표시할 것인지 의견 나누기
- [ ]  props 구조 수정
    - accentColor를 외부에서 주입받을 수 있도록 하기
- [ ]  웹 접근성 높이기 위한 `aria-label` 적극 활용
- [ ]  스토리북 mdx 사용해서 캘린더 UI 설명하기

## 리뷰 요구사항 (선택)

2024-07-24 13:25 UTC, Largopie requested changes
단기간에 굉장히 짜임새 있게 잘 구현하셨네요..
역시 해리 👍 잘 읽었고, 리뷰 몇 가지 남겼는데 확인 부탁드리겠습니다 :)

2024-07-24 13:25 UTC, Largopie commented on frontend/src/components/_common/Calendar/index.tsx
> +            </button>
[P3]
날짜 선택을 할 수 없는 첫 줄의 빈 공간에도 button이 삽입되는데, 웹 표준에 맞게 구현하기 위해서는 버튼이 없도록 만들어야 할 것 같아요! 급한 것은 아니니 추후에 수정해도 괜찮구요!

2024-07-24 14:19 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +  min-height: 40px;
rem으로 통일하기로 했는데 완전히 잊고 있었네요..수정할게요!!

2024-07-24 14:28 UTC, hwinkr commented on frontend/src/components/_common/Calendar/index.tsx
> +            </button>
oh...모든 요소들을 다 버튼으로 하니 날짜가 아닌 경우에도 `cursor : pointer` 속성이 적용되고 있었네요...! 이 부분은 접근성을 위해서라도 빠르게 수정할게요!!

2024-07-24 14:34 UTC, hwinkr commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
> +) {
한 날짜와 관련된 정보들이 꽤 많았는데,
- 공휴일인지
- 선택된 날짜인지
- index를 사용하는 것에서 실제 날짜로 표시해야 하거나
- 날짜인지 아닌지 즉, 빈칸으로 표시해야하는 것인지 아닌지
- 오늘인지 아닌지
등등,,,

여러개의 함수로 분리해서 한 날짜와 관련된 정보를 구할 수 있겠지만, `날짜와 관련된 정보`라는 하나의 관심사로 보고 함수의 역할이 조금 많은 것 같더라도 한 함수에서 날짜와 관련된 정보를 구하도록 했습니다~ 그래서 인자도 자연스럽게 많아진 것 같아요. 인자가 많은 경우, 객체를 사용하지 않으면 인자 전달 순서를 모두 기억하고 있어야 하니 낙타 말 처럼, 객체 형태로 바꾸는 것이 좋을 것 같네요!

2024-07-24 15:09 UTC, Yoonkyoungme requested changes
해리리해 빠른 시간 내에 완성도 높은 캘린더를 구현해 주셨네요🍀
감탄하고 갑니다~!~!~!
간단한 코멘트 남겨두었어요 :)

+ 다크모드일 때 버튼 배경 색상이 아래 사진처럼 보이네요ㅜㅜ
<img width="1214" alt="스크린샷 2024-07-24 오후 11 55 46" src="https://github.com/user-attachments/assets/936790fa-1141-4310-8c17-5bf96eb1ecd3">

2024-07-24 16:15 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +// TODO : 공휴일 색 변경 논의 필요(@해리)
오...좋은데요?

2024-07-24 16:51 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +// TODO : 공휴일 색 변경 논의 필요(@해리)
익스텐션 뭐죵!?

2024-07-24 16:52 UTC, hwinkr commented on frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
> +  const lastDate = endDate.getDate();
다시 보니까, 이해하기 힘든 것 같긴 하군요...빙봉 추천대로 수정할게요~

2024-07-24 16:55 UTC, hwinkr commented
> 해리리해 빠른 시간 내에 완성도 높은 캘린더를 구현해 주셨네요🍀 감탄하고 갑니다~!~!~! 간단한 코멘트 남겨두었어요 :)
> 
> ++ 다크모드일 때 버튼 배경 색상이 아래 사진처럼 보이네요ㅜㅜ <img alt="스크린샷 2024-07-24 오후 11 55 46" width="1214" src="https://private-user-images.githubusercontent.com/100656920/351769091-936790fa-1141-4310-8c17-5bf96eb1ecd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Mzc5NzIsIm5iZiI6MTcyMTgzNzY3MiwicGF0aCI6Ii8xMDA2NTY5MjAvMzUxNzY5MDkxLTkzNjc5MGZhLTExNDEtNDMxMC04YzE3LTViZjk2ZWIxZWNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNjE0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTc0YmZhYTJiZjJhMzMxNWE0NzY4MTkzZjVhNDM3ODg0YTc1NmU2YjU2Mzc4YjE1NzEzZGIyMDdjNGI0YmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o9vv9GHLR_Bok5-DO0u2h7McMCCmXOA6J0DtEK7takc">

스토리북에서도 전역 스타일을 적용할 수 있도록 했었는데 (abf87060fbc069f9092e83790395e7329601d5d0) 다크모드가 적용된 것이 아니라, 눈 고통 이슈로 모모 앱 배경 색을 어두운 회색으로 했었는데, 해당 배경색이 적용된 것 같아요..ㅎㅋㅋ

2024-07-24 17:29 UTC, Yoonkyoungme commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +// TODO : 공휴일 색 변경 논의 필요(@해리)
@hwinkr 혹시 자동완성 익스텐션이 있어야 가능한가요? 지금 해리는 안 되나요?

2024-07-24 17:29 UTC, Yoonkyoungme approved these changes

2024-07-24 17:35 UTC, hwinkr commented on frontend/src/components/_common/Calendar/Calendar.styles.ts
> +// TODO : 공휴일 색 변경 논의 필요(@해리)
안돼요...ㅋㅋㅋ

2024-07-25 04:20 UTC, Largopie approved these changes
사항 반영 야무지게 해주셨네요 감사합니다

👍👍👍 💯💯💯 🐫🐫🐫

2024-07-25 04:20 UTC, Largopie commented on frontend/src/components/_common/Calendar/index.tsx
> +            <div key={dateString} css={s_daySlotButton}></div>
👍👍👍 💯💯💯

2024-07-25 04:37 UTC, merged