[FE] Dropdown 컴포넌트 제작 및 시간 선택 hook 구현
woowacourse-teams/2024-momo pull request #71
Opened 2024-07-24 16:35 UTC by Largopie

## 관련 이슈

- resolves: #70 

## 작업 내용

<img width="504" alt="image" src="https://github.com/user-attachments/assets/14bc9293-5d7a-4801-aa8c-f2fdd2e76fac">

- 드롭다운 컴포넌트 구현
- 시간 선택 hook 구현
  - 시간 선택 시, startTime이 endTime을 느리거나 endTime이 startTime보다 빠르면 선택되지 않도록 구현
- 시간 선택 hook이 정상적으로 동작하는지 테스트케이스 작성

## 특이 사항

- 시간 선택 시, startTime이 endTime을 느리거나 endTime이 startTime보다 빠르면 선택되지 않도록 구현

이 부분은 추후에 변경사항이 생길 수도 있지만 일단은 구현해두었습니다!

## 리뷰 요구사항 (선택)

2024-07-24 17:26 UTC, hwinkr requested changes
구현 빠르네요! 고생하셨습니다~🐪 사소한 코멘트 몇개 남겼습니다!

2024-07-24 17:26 UTC, hwinkr commented on frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
> +  else if (endHours === startHours && endMinutes < startMinutes) return false;
```suggestion
if (endHours < startHours) return false;
if (endHours === startHours && endMinutes < startMinutes) return false;
```

early return을 해주기 때문에, `else if`문을 사용할 필요는 없을 것 같아요 :)

2024-07-24 17:26 UTC, hwinkr commented on frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
> +export function compareTimes(startTime: string, endTime: string) {
함수명이 **시간을 비교한다**는 의미를 내포하고 있는 것 같은데, 보다 확실하게 어떤 동작을 하고 무엇을 반환하는지를 더 잘 표현하도록 함수명을 변경해보는 것은 어떨까요?

예를들어, checkStartTimeEarlier 와 같은...?

2024-07-24 17:26 UTC, hwinkr commented on frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
> +    expect(result.current.endTime).toBe('23:00');
시간이 된다면 해당 매직 넘버에 대한 상수화를 진행해보는 것이 괜찮을 것 같네요!!

저도 이번 스프린트가 끝나면 엄청난 상수화를 해야 하기에....매직 넘버가 눈에 띄네요 ㅋㅋ

2024-07-24 17:26 UTC, hwinkr commented on frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
> +    expect(result.current.startTime).not.toBe(CHANGE_TIME);
not을 사용해서 검증하기 보다는, 변경되지 않을 때의 값과 비교해보는 것은 어떨까요? 현재는 `CHANGE_TIME`만 아니면 통과하기 때문에, 더 정확한 테스트를 위해서 특정 값 자체와 동등 연산자로 비교하는 것이 괜찮을 것 같다는 생각이 들어요~

2024-07-25 01:43 UTC, Yoonkyoungme requested changes
낙타 고생했습니다!! 작업 속도가 엄청 빠르네요~! 간단한 코멘트 남겼는데, 천천히 확인해 보세요!

2024-07-25 05:13 UTC, Largopie reviewed
리뷰 반영 완료했습니다 :)

현재는 시작시간은 끝 시간을 초과할 수 없고, 끝 시간은 시작 시간 이전으로 설정할 수 없게끔 옵션값이 변경되도록 수정했습니다.

하지만 추후에 아래의 동영상과 hover되었을 때 끝 시간이 변경되도록 수정하면 좋을 것 같네요!


https://github.com/user-attachments/assets/c870ac0b-c2dd-4828-aa92-77da647918fc

2024-07-25 05:13 UTC, Largopie commented on frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
> +export function compareTimes(startTime: string, endTime: string) {
이게 좋네요! 👍👍👍

2024-07-25 05:13 UTC, Largopie commented on frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
> +  else if (endHours === startHours && endMinutes < startMinutes) return false;
그렇네요! 수정하도록 하겠습니다 🐫👍

2024-07-25 08:32 UTC, hwinkr approved these changes
낙타 좋은데요~??

2024-07-25 08:58 UTC, Yoonkyoungme approved these changes
낙타👍👍 열심히 고민하고, 리뷰 반영해 주셨네요!

2024-07-25 08:58 UTC, Yoonkyoungme commented on frontend/src/hooks/useTimeRangeDropdown/constants.ts
hooks, components 내에서만 사용하는 **상수파일**을 어떤 파일로 분리할지 (ex: constants.ts / hook명.constants.ts, ... 등)에 대해서도 스프린트 끝나고 이야기 나누면 좋을 것 같네요! 
스프린트 이후 TODO 작업으로 남겨두겠습니다~

2024-07-25 10:31 UTC, merged